enum
{
			SYS=0,
			LAN,
			PPPOE,
			WAN_MAC, //heyanpingadd
			PORT_FORWARD,
			WAN_STATIC,
			WLAN,
			MID_DDNS,
			MID_SCHED,
			WPS,
			MID_AUTH,
			QOS,
			TRIGGER,
			RESERVEIP_IP, //13 heyanpingadd
			PARENTAL_CONTROL,
			SROUTE, //  15 heyanping add
			EMAIL, //  16 heyanping add
			FTP_SERVER,
			USB_HTTP//18 liuchao add
};
#define TW_SUCCESS	0x0000
#define TW_FAILED	0xffff
#define SKIP 0X00ff
#define SKIPMASK 0Xff00
#define ERR_BASE_ADDR                   	1000
#define ERR_CVT(err)           				((((unsigned short)(err)) << 16))
#define ERR_CVT2(err)           			(unsigned short)(err) //add by xieyiyong in 2012/12/07

/* 模块基址 */
#define ERR_MODULE_BASE_ADDR(mid)        	(ERR_BASE_ADDR + ((mid & 0x00ff)) * 100)

#define TW_ERR_INTERNAL(err)                (unsigned short)(((unsigned long)err) >> 16)

/*-----------SYS----------------*/			
#define ERR_SYS_BAEGIN_ADD			ERR_MODULE_BASE_ADDR(SYS)

#define ERR_OUTOF_MEM				       ERR_CVT(ERR_SYS_BAEGIN_ADD + 1) //内存用完
#define ERR_NULL_PIONTER			       ERR_CVT(ERR_SYS_BAEGIN_ADD + 2) //空指针错误
#define ERR_OVER_LEN				       ERR_CVT(ERR_SYS_BAEGIN_ADD + 3) //变量超长
#define ERR_INSUFFICIENT_LEN			ERR_CVT(ERR_SYS_BAEGIN_ADD + 4) //变量长度不足
#define ERR_OVER_RANGE				       ERR_CVT(ERR_SYS_BAEGIN_ADD + 5) //变量超出范围
#define ERR_MODE_NAME_NOT_MATCH	       ERR_CVT(ERR_SYS_BAEGIN_ADD + 6) //模块名未匹配
#define ERR_IP_INVALID_FORMAT			ERR_CVT(ERR_SYS_BAEGIN_ADD + 7) //IP格式错误
#define ERR_IP_IS_WRONG_NET_SECTION	ERR_CVT(ERR_SYS_BAEGIN_ADD + 8) //IP超出范围
#define ERR_WAN_MAC_FORMAT_ERR		ERR_CVT(ERR_SYS_BAEGIN_ADD + 9)//MAC地址格式错误
#define ERR_IP_MASK_NOT_MATCH			ERR_CVT(ERR_SYS_BAEGIN_ADD + 10) //IP与Mask不匹配
#define ERR_NETMASK_FORMAT_ERR		ERR_CVT(ERR_SYS_BAEGIN_ADD + 11) //子网掩码格式错误
#define ERR_ACTION_NOT_MATCH			ERR_CVT(ERR_SYS_BAEGIN_ADD + 12) //action 未匹配
#define ERR_HOSTNAME_FORMAT_ERR		ERR_CVT(ERR_SYS_BAEGIN_ADD + 13) //主机名格式错误
#define ERR_WANCHANGED_AP_MODE		ERR_CVT(ERR_SYS_BAEGIN_ADD + 14) //桥模式下不允许配置WAN连接
#define ERR_ENABLE_INVALID_VALUE		ERR_CVT(ERR_SYS_BAEGIN_ADD + 15)
#define ERR_INVALID_GW_ADDR			ERR_CVT(ERR_SYS_BAEGIN_ADD + 16)
#define ERR_INVALID_PORT_RANGE		ERR_CVT(ERR_SYS_BAEGIN_ADD + 17)//端口号超出范围
#define ERR_UNSUPPORT_PROTOCOL_ERR	ERR_CVT(ERR_SYS_BAEGIN_ADD + 18)//协议不支持
#define ERR_INVALID_UINT_VAL			ERR_CVT(ERR_SYS_BAEGIN_ADD + 19)//只允许输入正整数
#define ERR_AUTH_TIME_OUT			ERR_CVT(ERR_SYS_BAEGIN_ADD + 20)//只允许输入正整数

/*-----------LAN模块------------*/
#define ERR_LAN_BEGIN_ADDR               	       ERR_MODULE_BASE_ADDR(LAN)    //LAN模块基址 
#define ERR_BR0_IP_CONFILCT_WITH_BR1     	ERR_CVT(ERR_LAN_BEGIN_ADDR + 1)  //br0 网段与br1 网段重叠
#define ERR_BR0_IP_CONFILCT_WITH_WAN     	ERR_CVT(ERR_LAN_BEGIN_ADDR + 2) //LAN地址与WAN地址冲突
#define ERR_DHCPPOOL_OUTOF_RANGE			ERR_CVT(ERR_LAN_BEGIN_ADDR + 3)  //DHCP地址池不在br0 范围之内
#define ERR_DHCPPOOL_INVAILD				ERR_CVT(ERR_LAN_BEGIN_ADDR + 4)  //地址池范围非法
#define ERR_DHCPPOOLCHANGED_AP_MODE      	ERR_CVT(ERR_LAN_BEGIN_ADDR + 5) //桥模式下修改了地址池范围
#define ERR_DHCPLEASECHANGED_AP_MODE     	ERR_CVT(ERR_LAN_BEGIN_ADDR + 6) //桥模式下修改了租约时间
#define ERR_DHCPDOMAINCHANGED_AP_MODE   ERR_CVT(ERR_LAN_BEGIN_ADDR + 7) //桥模式下修改了本地域名
#define ERR_DHCPSWITCH_AP_MODE    			ERR_CVT(ERR_LAN_BEGIN_ADDR + 8) //桥模式下修改了DHCP开关
#define ERR_BR0_IN_DHCP_POOL    			ERR_CVT(ERR_LAN_BEGIN_ADDR + 9) //BR0在DHCP地址池范围内
#define ERR_RESERV_IP_OUTOF_DHCPPOOL    	ERR_CVT(ERR_LAN_BEGIN_ADDR + 10) //保留地址不在DHCP地址池范围内

/*-----------WLAN模块------------*/
#define ERR_WLAN_BEGIN_ADDR					ERR_MODULE_BASE_ADDR(WLAN)
#define ERR_WLAN_INVALID_2G_CHANNEL_VAL     ERR_CVT(ERR_WLAN_BEGIN_ADDR + 1)
#define ERR_WLAN_INVALID_5G_CHANNEL_VAL     ERR_CVT(ERR_WLAN_BEGIN_ADDR + 2)
#define ERR_WLAN_INVALID_SSID_VAL     		ERR_CVT(ERR_WLAN_BEGIN_ADDR + 3)
#define ERR_WLAN_INVALID_1_WEP_KEY_VAL     	ERR_CVT(ERR_WLAN_BEGIN_ADDR + 4)
#define ERR_WLAN_INVALID_2_WEP_KEY_VAL     	ERR_CVT(ERR_WLAN_BEGIN_ADDR + 5)
#define ERR_WLAN_INVALID_3_WEP_KEY_VAL     	ERR_CVT(ERR_WLAN_BEGIN_ADDR + 6)
#define ERR_WLAN_INVALID_4_WEP_KEY_VAL     	ERR_CVT(ERR_WLAN_BEGIN_ADDR + 7)
#define ERR_WLAN_INVALID_WPA_PSK_VAL     	ERR_CVT(ERR_WLAN_BEGIN_ADDR + 8)
#define ERR_WLAN_SSID_CONFLICT			    ERR_CVT(ERR_WLAN_BEGIN_ADDR + 9)
#define ERR_WLAN_INVALID_SSID_LENGTH_VAL    ERR_CVT(ERR_WLAN_BEGIN_ADDR + 10)
#define ERR_WLAN_INVALID_WEP_KEY_VAL     	ERR_CVT(ERR_WLAN_BEGIN_ADDR + 11)
#define ERR_WLAN_INVALID_WEP_64_KEY_VAL     	ERR_CVT(ERR_WLAN_BEGIN_ADDR + 12)
#define ERR_WLAN_INVALID_WEP_128_KEY_VAL     	ERR_CVT(ERR_WLAN_BEGIN_ADDR + 13)


/*-----------WPS模块------------*/
#define ERR_WPS_BEGIN_ADDR					ERR_MODULE_BASE_ADDR(WPS)
#define ERR_WPS_PIN_ERROR     				ERR_CVT(ERR_WPS_BEGIN_ADDR + 1)
#define ERR_WPS_ACTION_ERROR     			ERR_CVT(ERR_WPS_BEGIN_ADDR + 2)
#define ERR_WPS_CONFIGURE_ERROR     		ERR_CVT(ERR_WPS_BEGIN_ADDR + 3)



/*----------PPPOE模块------------*/
#define ERR_PPPOE_BEGIN_ADDR              	ERR_MODULE_BASE_ADDR(PPPOE)    //PPPOE模块基址

#define ERR_PPPOE_USERNAME    				ERR_CVT(ERR_PPPOE_BEGIN_ADDR + 1)
#define ERR_PPPOE_PASSWORD             		ERR_CVT(ERR_PPPOE_BEGIN_ADDR + 2)
#define ERR_PPPOE_SERVICE             		ERR_CVT(ERR_PPPOE_BEGIN_ADDR + 3)
#define ERR_PPPOE_IDLETIME                	ERR_CVT(ERR_PPPOE_BEGIN_ADDR + 4)
#define ERR_PPPOE_MTUWORD               	ERR_CVT(ERR_PPPOE_BEGIN_ADDR + 5)
#define ERR_PPPOE_MRUWORD               	ERR_CVT(ERR_PPPOE_BEGIN_ADDR + 6)
#define ERR_PPPOE_IDLETIME_INVALID		ERR_CVT(ERR_PPPOE_BEGIN_ADDR + 7)
#define ERR_PPTP_MTUWORD			ERR_CVT(ERR_PPPOE_BEGIN_ADDR + 8)
#define ERR_PPTP_MRUWORD			ERR_CVT(ERR_PPPOE_BEGIN_ADDR + 9)
#define ERR_L2TP_MTUWORD			ERR_CVT(ERR_PPPOE_BEGIN_ADDR + 10)
#define ERR_L2TP_MRUWORD			ERR_CVT(ERR_PPPOE_BEGIN_ADDR + 11)



/*----------WAN MAC CPOY MODULE------------*/ //heyanping add
#define ERR_WAN_MAC_BEGIN_ADDR             	ERR_MODULE_BASE_ADDR(WAN_MAC)    //MAC COPY模块基址

/*-----------PORT_FORWARD模块----------------*/			
#define ERR_PORTFORWARD_BAEGIN_ADD 			ERR_MODULE_BASE_ADDR(PORT_FORWARD)



#define ERR_PORTFORWARD_PORT_OUT_RANGE	            			ERR_CVT2(ERR_PORTFORWARD_BAEGIN_ADD + 1) //port range is invalid
#define ERR_PORTFORWARD_NEED_SRC_PORT_RANGE	       				ERR_CVT2(ERR_PORTFORWARD_BAEGIN_ADD + 2) //must specify a source port Range
#define ERR_PORTFORWARD_NEED_LAN_ADDRESS	    					ERR_CVT2(ERR_PORTFORWARD_BAEGIN_ADD + 3)//must specify a LAN IP Address
#define ERR_PORTFORWARD_NEED_DST_PORT_RANGE	   					ERR_CVT2(ERR_PORTFORWARD_BAEGIN_ADD + 4)//must specify a Destination Port Range
#define ERR_PORTFORWARD_SRC_STARTPORT_GT_ENDPORT   		    	ERR_CVT2(ERR_PORTFORWARD_BAEGIN_ADD + 5)//source start port greater than end port
#define ERR_PORTFORWARD_DST_STARTPORT_GT_ENDPORT   		    	ERR_CVT2(ERR_PORTFORWARD_BAEGIN_ADD + 6)//Destination start port greater than end
#define ERR_PORTFORWARD_LAN_AND_WAN_PORTRANGE_NOT_SAME    		ERR_CVT2(ERR_PORTFORWARD_BAEGIN_ADD + 7)//WAN Port Range and LAN Port Range must be the same size

#define ERR_PORTFORWARD_PROTO_INVALID    	                		ERR_CVT2(ERR_PORTFORWARD_BAEGIN_ADD + 8)//protocal tcp,udp,tcp/udp is invalid
#define ERR_PORTFORWARD_IP_INVALID    	                	    ERR_CVT2(ERR_PORTFORWARD_BAEGIN_ADD + 9)//not an IP address
#define ERR_PORTFORWARD_ISNOT_LAN_IP_INVALID     	            ERR_CVT2(ERR_PORTFORWARD_BAEGIN_ADD + 10)//not in the lan range
#define ERR_PORTFORWARD_IS_NETWORD_IP_INVALID    	            ERR_CVT2(ERR_PORTFORWARD_BAEGIN_ADD + 11)//cannot be the network address
#define ERR_PORTFORWARD_IS_BROADCAST_IP_INVALID    	            ERR_CVT2(ERR_PORTFORWARD_BAEGIN_ADD + 12)//cannot be the broadcast address
#define ERR_PORTFORWARD_PORT_CONFLICT            	            ERR_CVT2(ERR_PORTFORWARD_BAEGIN_ADD + 13)//port conflict


/*----------WAN_STATIC 模块------------*/
#define ERR_WAN_STATIC_BAEGIN_ADD 				ERR_MODULE_BASE_ADDR(WAN_STATIC)

#define ERR_WAN_IP_AND_GW_NOT_IN_SAME_RANGE			ERR_CVT(ERR_WAN_STATIC_BAEGIN_ADD + 1)
#define ERR_WAN_IP_CONFILCT_WITH_BR0             		ERR_CVT(ERR_WAN_STATIC_BAEGIN_ADD + 2)
#define ERR_WAN_IP_CONFILCT_WITH_BR1             		ERR_CVT(ERR_WAN_STATIC_BAEGIN_ADD + 3)

/* DDNS */
#define ERR_DDNS_BEGIN_ADDR                 ERR_MODULE_BASE_ADDR(MID_DDNS)

#define ERR_DDNS_INVALID_DDNSPROVIDER       ERR_CVT(ERR_DDNS_BEGIN_ADDR + 1)
#define ERR_DDNS_INVALID_HOSTNAME           ERR_CVT(ERR_DDNS_BEGIN_ADDR + 2)
#define ERR_DDNS_HOSTNAME_LENGTH_OVER       ERR_CVT(ERR_DDNS_BEGIN_ADDR + 3)
#define ERR_DDNS_INVALID_USERNAME           ERR_CVT(ERR_DDNS_BEGIN_ADDR + 5)
#define ERR_DDNS_USERNAME_LENGTH_OVER       ERR_CVT(ERR_DDNS_BEGIN_ADDR + 6)
#define ERR_DDNS_INVALID_PASSWORD           ERR_CVT(ERR_DDNS_BEGIN_ADDR + 7)
#define ERR_DDNS_PASSWORD_LENGTH_OVER       ERR_CVT(ERR_DDNS_BEGIN_ADDR + 8)
#define ERR_DDNS_HOSTNAME_CONFLICT          ERR_CVT(ERR_DDNS_BEGIN_ADDR + 13)
#define ERR_DDNS_INVALID_DDNS_HOST          ERR_CVT(ERR_DDNS_BEGIN_ADDR + 14)
#define ERR_DDNS_DDNS_HOST_LENGTH_OVER      ERR_CVT(ERR_DDNS_BEGIN_ADDR + 15)
#define ERR_DDNS_HOSTNAME_ILLEGAL           ERR_CVT(ERR_DDNS_BEGIN_ADDR + 16)


/* Schedule */
#define ERR_SCHEDULE_BEGIN_ADDR             ERR_MODULE_BASE_ADDR(MID_SCHED)

#define ERR_SCHEDULE_INVALID_STARTTIME      ERR_CVT(ERR_SCHEDULE_BEGIN_ADDR+1)
#define ERR_SCHEDULE_INVALID_SCHEDULEDAYS   ERR_CVT(ERR_SCHEDULE_BEGIN_ADDR+2)




/*Auth*/
#define ERR_AUTH_BEGIN_ADDR             ERR_MODULE_BASE_ADDR(MID_AUTH)

#define ERR_AUTH_WRONG_USER          ERR_CVT(ERR_AUTH_BEGIN_ADDR + 1)
#define ERR_AUTH_WRONG_PSW          ERR_CVT(ERR_AUTH_BEGIN_ADDR + 2)
#define ERR_AUTH_TOOMANY_USR          ERR_CVT(ERR_AUTH_BEGIN_ADDR + 3)
#define ERR_AUTH_WRONG_OLDPSW          ERR_CVT(ERR_AUTH_BEGIN_ADDR + 4)
#define ERR_AUTH_WRONG_CONFIRMPSW          ERR_CVT(ERR_AUTH_BEGIN_ADDR + 5)
#define ERR_AUTH_WRONG_TIMEOUT          ERR_CVT(ERR_AUTH_BEGIN_ADDR + 6)
#define ERR_AUTH_NO_RIGTH          		ERR_CVT(ERR_AUTH_BEGIN_ADDR + 7)


/* QOS */
#define ERR_QOS_BEGIN_ADDR             ERR_MODULE_BASE_ADDR(QOS)


/* Trigger */
#define ERR_TRIGGER_BEGIN_ADDR             ERR_MODULE_BASE_ADDR(TRIGGER)
#define ERR_PORT_RANGE                      ERR_CVT2(ERR_TRIGGER_BEGIN_ADDR + 1)
#define ERR_TRIGGER_NEED_LAN_ADDRESS	      ERR_CVT2(ERR_TRIGGER_BEGIN_ADDR + 2)//must specify a LAN IP Address
#define ERR_TRIGGER_LAN_IP_CONFICT		  ERR_CVT2(ERR_TRIGGER_BEGIN_ADDR + 3)

/*reserve ip*/
#define ERR_RESERVEIP_IP_BEGIN_ADDR             ERR_MODULE_BASE_ADDR(RESERVEIP_IP)
#define ERR_RESERVEIP_IP_DUPLICATE                      ERR_CVT(ERR_RESERVEIP_IP_BEGIN_ADDR + 1)
#define ERR_RESERVEIP_MAC_DUPLICATE             ERR_CVT(ERR_RESERVEIP_IP_BEGIN_ADDR + 2)

/*parental control*/
#define ERR_PARENTAL_CONTROL_BEGIN_ADDR             ERR_MODULE_BASE_ADDR(PARENTAL_CONTROL)
#define ERR_PARENTAL_CONTROL_INVALID_CAHR           ERR_CVT2(ERR_PARENTAL_CONTROL_BEGIN_ADDR + 1)

/*sroute*/
#define ERR_SROUTE_BEGIN_ADDR             ERR_MODULE_BASE_ADDR(SROUTE)
#define ERR_SROUTE_INVALID_GATEWAY     ERR_CVT(ERR_SROUTE_BEGIN_ADDR + 1)
#define ERR_SROUTE_INVALID_METRIC		ERR_CVT(ERR_SROUTE_BEGIN_ADDR + 2)
#define ERR_SROUTE_CONFLICT			ERR_CVT(ERR_SROUTE_BEGIN_ADDR + 3)
#define ERR_SROUTE_INVALID_IPMASK			ERR_CVT(ERR_SROUTE_BEGIN_ADDR + 4)
#define ERR_SROUTE_DESC_ERR			ERR_CVT(ERR_SROUTE_BEGIN_ADDR + 5)
#define ERR_SROUTE_INVALID_IP			ERR_CVT(ERR_SROUTE_BEGIN_ADDR + 6)
#define ERR_SROUTE_GENERAL_FAILD			ERR_CVT(ERR_SROUTE_BEGIN_ADDR + 7)
/*EMAIL*/
#define ERR_EMAIL_BEGIN_ADDR             ERR_MODULE_BASE_ADDR(EMAIL)
#define ERR_EMAIL_SERVER_ERR    ERR_CVT(ERR_EMAIL_BEGIN_ADDR + 1)
#define ERR_EMAIL_ADDR_ERR		ERR_CVT(ERR_EMAIL_BEGIN_ADDR + 2)

/* ftp_server */
#define ERR_FTP_BEGIN_ADDR             ERR_MODULE_BASE_ADDR(FTP_SERVER)
#define ERR_FTP_MAX_USER               ERR_CVT2(ERR_FTP_BEGIN_ADDR + 1)//over max user 
#define ERR_FTP_UNUNIQUE_USER_NAME	 ERR_CVT2(ERR_FTP_BEGIN_ADDR + 2)//must specify a LAN IP Address


/* USB_HTTP */
#define ERR_USB_HTTP_BEGIN_ADDR        ERR_MODULE_BASE_ADDR(USB_HTTP)
#define ERR_USB_HTTP_DOMAIN_FRAMAT     ERR_CVT(ERR_USB_HTTP_BEGIN_ADDR + 1)//format error
#define ERR_USB_HTTP_DOMAIN_LENGTH     ERR_CVT(ERR_USB_HTTP_BEGIN_ADDR + 2)//length error

