FLAC: FLAC::Metadata::Unknown Class Reference
FLAC::Metadata::Unknown Class Reference
[FLAC++/metadata.h: metadata object classes]
#include <metadata.h>
Public Member Functions
Unknown (::FLAC__StreamMetadata *object, bool copy)
Unknown & assign (::FLAC__StreamMetadata *object, bool copy)
const FLAC__byte * get_data () const
bool set_data (const FLAC__byte *data, unsigned length)
bool set_data (FLAC__byte *data, unsigned length, bool copy)
bool is_valid () const
bool get_is_last () const
::FLAC__MetadataType get_type () const
unsigned get_length () const
void set_is_last (bool)
operator const ::FLAC__StreamMetadata * () const
Unknown (const Unknown &object)
Unknown (const ::FLAC__StreamMetadata &object)
Unknown (const ::FLAC__StreamMetadata *object)
Unknown & operator= (const Unknown &object)
Unknown & operator= (const ::FLAC__StreamMetadata &object)
Unknown & operator= (const ::FLAC__StreamMetadata *object)
bool operator== (const Unknown &object) const
bool operator== (const ::FLAC__StreamMetadata &object) const
bool operator== (const ::FLAC__StreamMetadata *object) const
bool operator!= (const Unknown &object) const
bool operator!= (const ::FLAC__StreamMetadata &object) const
bool operator!= (const ::FLAC__StreamMetadata *object) const
Protected Member Functions
Prototype & assign_object (::FLAC__StreamMetadata *object, bool copy)
virtual void clear ()
Protected Attributes
::FLAC__StreamMetadata * object_
Friends
class SimpleIterator
class Iterator
Detailed Description
Opaque metadata block for storing unknown types. This should not be used unless you know what you are doing; it is currently used only internally to support forward compatibility of metadata blocks. See the overview for more,
Constructor & Destructor Documentation
FLAC::Metadata::Unknown::Unknown (const Unknown & object) [inline]
Constructs a copy of the given object. This form always performs a deep copy.
FLAC::Metadata::Unknown::Unknown (const ::FLAC__StreamMetadata & object) [inline]
Constructs a copy of the given object. This form always performs a deep copy.
FLAC::Metadata::Unknown::Unknown (const ::FLAC__StreamMetadata * object) [inline]
Constructs a copy of the given object. This form always performs a deep copy.
FLAC::Metadata::Unknown::Unknown (::FLAC__StreamMetadata * object, bool copy) [inline]
Constructs an object with copy control. See Prototype(::FLAC__StreamMetadata *object, bool copy).
Member Function Documentation
Unknown& FLAC::Metadata::Unknown::operator= (const Unknown & object) [inline]
Assign from another object. Always performs a deep copy.
Reimplemented from FLAC::Metadata::Prototype.
References FLAC::Metadata::Prototype::operator=().
Unknown& FLAC::Metadata::Unknown::operator= (const ::FLAC__StreamMetadata & object) [inline]
Constructs a copy of the given object. This form always performs a deep copy.
Reimplemented from FLAC::Metadata::Prototype.
References FLAC::Metadata::Prototype::operator=().
Unknown& FLAC::Metadata::Unknown::operator= (const ::FLAC__StreamMetadata * object) [inline]
Constructs a copy of the given object. This form always performs a deep copy.
Reimplemented from FLAC::Metadata::Prototype.
References FLAC::Metadata::Prototype::operator=().
Unknown& FLAC::Metadata::Unknown::assign (::FLAC__StreamMetadata * object, bool copy) [inline]
Assigns an object with copy control. See Prototype::assign_object(::FLAC__StreamMetadata *object, bool copy).
References FLAC::Metadata::Prototype::assign_object().
bool FLAC::Metadata::Unknown::operator== (const Unknown & object) const [inline]
Check for equality, performing a deep compare by following pointers.
Reimplemented from FLAC::Metadata::Prototype.
References FLAC::Metadata::Prototype::operator==().
bool FLAC::Metadata::Unknown::operator== (const ::FLAC__StreamMetadata & object) const [inline]
Constructs a copy of the given object. This form always performs a deep copy.
Reimplemented from FLAC::Metadata::Prototype.
References FLAC::Metadata::Prototype::operator==().
bool FLAC::Metadata::Unknown::operator== (const ::FLAC__StreamMetadata * object) const [inline]
Constructs a copy of the given object. This form always performs a deep copy.
Reimplemented from FLAC::Metadata::Prototype.
References FLAC::Metadata::Prototype::operator==().
bool FLAC::Metadata::Unknown::operator!= (const Unknown & object) const [inline]
Check for inequality, performing a deep compare by following pointers.
Reimplemented from FLAC::Metadata::Prototype.
References FLAC::Metadata::Prototype::operator!=().
bool FLAC::Metadata::Unknown::operator!= (const ::FLAC__StreamMetadata & object) const [inline]
Constructs a copy of the given object. This form always performs a deep copy.
Reimplemented from FLAC::Metadata::Prototype.
References FLAC::Metadata::Prototype::operator!=().
bool FLAC::Metadata::Unknown::operator!= (const ::FLAC__StreamMetadata * object) const [inline]
Constructs a copy of the given object. This form always performs a deep copy.
Reimplemented from FLAC::Metadata::Prototype.
References FLAC::Metadata::Prototype::operator!=().
bool FLAC::Metadata::Unknown::set_data (const FLAC__byte * data, unsigned length)
This form always copies data.
Prototype& FLAC::Metadata::Prototype::assign_object (::FLAC__StreamMetadata * object, bool copy) [protected, inherited]
Assigns an object with copy control. See Prototype(::FLAC__StreamMetadata *object, bool copy).
Referenced by assign(), FLAC::Metadata::Picture::assign(), FLAC::Metadata::CueSheet::assign(), FLAC::Metadata::VorbisComment::assign(), FLAC::Metadata::SeekTable::assign(), FLAC::Metadata::Application::assign(), FLAC::Metadata::Padding::assign(), and FLAC::Metadata::StreamInfo::assign().
virtual void FLAC::Metadata::Prototype::clear () [protected, virtual, inherited]
Deletes the underlying FLAC__StreamMetadata object.
bool FLAC::Metadata::Prototype::get_is_last () const [inherited]
Returns true if this block is the last block in a stream, else false.
Assertions:
 is_valid()
::FLAC__MetadataType FLAC::Metadata::Prototype::get_type () const [inherited]
Returns the type of the block.
Assertions:
 is_valid()
Reimplemented in FLAC::Metadata::Picture.
unsigned FLAC::Metadata::Prototype::get_length () const [inherited]
Returns the stream length of the metadata block.
Note:
The length does not include the metadata block header, per spec.
Assertions:
 is_valid()
void FLAC::Metadata::Prototype::set_is_last (bool) [inherited]
Sets the "is_last" flag for the block. When using the iterators it is not necessary to set this flag; they will do it for you.
Assertions:
 is_valid()
The documentation for this class was generated from the following file:
include/FLAC++/metadata.h
Copyright (c) 2000,2001,2002,2003,2004,2005,2006,2007 Josh Coalson