FLAC: FLAC::Metadata::SeekTable Class Reference
FLAC::Metadata::SeekTable Class Reference
[FLAC++/metadata.h: metadata object classes]
#include <metadata.h>
Public Member Functions
SeekTable (::FLAC__StreamMetadata *object, bool copy)
SeekTable & assign (::FLAC__StreamMetadata *object, bool copy)
unsigned get_num_points () const
::FLAC__StreamMetadata_SeekPoint get_point (unsigned index) const
void set_point (unsigned index, const ::FLAC__StreamMetadata_SeekPoint &point)
bool insert_point (unsigned index, const ::FLAC__StreamMetadata_SeekPoint &point)
bool delete_point (unsigned index)
bool is_legal () const
bool is_valid () const
bool get_is_last () const
::FLAC__MetadataType get_type () const
unsigned get_length () const
void set_is_last (bool)
operator const ::FLAC__StreamMetadata * () const
SeekTable (const SeekTable &object)
SeekTable (const ::FLAC__StreamMetadata &object)
SeekTable (const ::FLAC__StreamMetadata *object)
SeekTable & operator= (const SeekTable &object)
SeekTable & operator= (const ::FLAC__StreamMetadata &object)
SeekTable & operator= (const ::FLAC__StreamMetadata *object)
bool operator== (const SeekTable &object) const
bool operator== (const ::FLAC__StreamMetadata &object) const
bool operator== (const ::FLAC__StreamMetadata *object) const
bool operator!= (const SeekTable &object) const
bool operator!= (const ::FLAC__StreamMetadata &object) const
bool operator!= (const ::FLAC__StreamMetadata *object) const
Protected Member Functions
Prototype & assign_object (::FLAC__StreamMetadata *object, bool copy)
virtual void clear ()
Protected Attributes
::FLAC__StreamMetadata * object_
Friends
class SimpleIterator
class Iterator
Detailed Description
SEEKTABLE metadata block. See the overview for more, and the format specification.
Constructor & Destructor Documentation
FLAC::Metadata::SeekTable::SeekTable (const SeekTable & object) [inline]
Constructs a copy of the given object. This form always performs a deep copy.
FLAC::Metadata::SeekTable::SeekTable (const ::FLAC__StreamMetadata & object) [inline]
Constructs a copy of the given object. This form always performs a deep copy.
FLAC::Metadata::SeekTable::SeekTable (const ::FLAC__StreamMetadata * object) [inline]
Constructs a copy of the given object. This form always performs a deep copy.
FLAC::Metadata::SeekTable::SeekTable (::FLAC__StreamMetadata * object, bool copy) [inline]
Constructs an object with copy control. See Prototype(::FLAC__StreamMetadata *object, bool copy).
Member Function Documentation
SeekTable& FLAC::Metadata::SeekTable::operator= (const SeekTable & object) [inline]
Assign from another object. Always performs a deep copy.
Reimplemented from FLAC::Metadata::Prototype.
References FLAC::Metadata::Prototype::operator=().
SeekTable& FLAC::Metadata::SeekTable::operator= (const ::FLAC__StreamMetadata & object) [inline]
Constructs a copy of the given object. This form always performs a deep copy.
Reimplemented from FLAC::Metadata::Prototype.
References FLAC::Metadata::Prototype::operator=().
SeekTable& FLAC::Metadata::SeekTable::operator= (const ::FLAC__StreamMetadata * object) [inline]
Constructs a copy of the given object. This form always performs a deep copy.
Reimplemented from FLAC::Metadata::Prototype.
References FLAC::Metadata::Prototype::operator=().
SeekTable& FLAC::Metadata::SeekTable::assign (::FLAC__StreamMetadata * object, bool copy) [inline]
Assigns an object with copy control. See Prototype::assign_object(::FLAC__StreamMetadata *object, bool copy).
References FLAC::Metadata::Prototype::assign_object().
bool FLAC::Metadata::SeekTable::operator== (const SeekTable & object) const [inline]
Check for equality, performing a deep compare by following pointers.
Reimplemented from FLAC::Metadata::Prototype.
References FLAC::Metadata::Prototype::operator==().
bool FLAC::Metadata::SeekTable::operator== (const ::FLAC__StreamMetadata & object) const [inline]
Constructs a copy of the given object. This form always performs a deep copy.
Reimplemented from FLAC::Metadata::Prototype.
References FLAC::Metadata::Prototype::operator==().
bool FLAC::Metadata::SeekTable::operator== (const ::FLAC__StreamMetadata * object) const [inline]
Constructs a copy of the given object. This form always performs a deep copy.
Reimplemented from FLAC::Metadata::Prototype.
References FLAC::Metadata::Prototype::operator==().
bool FLAC::Metadata::SeekTable::operator!= (const SeekTable & object) const [inline]
Check for inequality, performing a deep compare by following pointers.
Reimplemented from FLAC::Metadata::Prototype.
References FLAC::Metadata::Prototype::operator!=().
bool FLAC::Metadata::SeekTable::operator!= (const ::FLAC__StreamMetadata & object) const [inline]
Constructs a copy of the given object. This form always performs a deep copy.
Reimplemented from FLAC::Metadata::Prototype.
References FLAC::Metadata::Prototype::operator!=().
bool FLAC::Metadata::SeekTable::operator!= (const ::FLAC__StreamMetadata * object) const [inline]
Constructs a copy of the given object. This form always performs a deep copy.
Reimplemented from FLAC::Metadata::Prototype.
References FLAC::Metadata::Prototype::operator!=().
void FLAC::Metadata::SeekTable::set_point (unsigned index, const ::FLAC__StreamMetadata_SeekPoint & point)
See FLAC__metadata_object_seektable_set_point().
bool FLAC::Metadata::SeekTable::insert_point (unsigned index, const ::FLAC__StreamMetadata_SeekPoint & point)
See FLAC__metadata_object_seektable_insert_point().
bool FLAC::Metadata::SeekTable::delete_point (unsigned index)
See FLAC__metadata_object_seektable_delete_point().
bool FLAC::Metadata::SeekTable::is_legal () const
See FLAC__metadata_object_seektable_is_legal().
Prototype& FLAC::Metadata::Prototype::assign_object (::FLAC__StreamMetadata * object, bool copy) [protected, inherited]
Assigns an object with copy control. See Prototype(::FLAC__StreamMetadata *object, bool copy).
Referenced by FLAC::Metadata::Unknown::assign(), FLAC::Metadata::Picture::assign(), FLAC::Metadata::CueSheet::assign(), FLAC::Metadata::VorbisComment::assign(), assign(), FLAC::Metadata::Application::assign(), FLAC::Metadata::Padding::assign(), and FLAC::Metadata::StreamInfo::assign().
virtual void FLAC::Metadata::Prototype::clear () [protected, virtual, inherited]
Deletes the underlying FLAC__StreamMetadata object.
bool FLAC::Metadata::Prototype::get_is_last () const [inherited]
Returns true if this block is the last block in a stream, else false.
Assertions:
 is_valid()
::FLAC__MetadataType FLAC::Metadata::Prototype::get_type () const [inherited]
Returns the type of the block.
Assertions:
 is_valid()
Reimplemented in FLAC::Metadata::Picture.
unsigned FLAC::Metadata::Prototype::get_length () const [inherited]
Returns the stream length of the metadata block.
Note:
The length does not include the metadata block header, per spec.
Assertions:
 is_valid()
void FLAC::Metadata::Prototype::set_is_last (bool) [inherited]
Sets the "is_last" flag for the block. When using the iterators it is not necessary to set this flag; they will do it for you.
Assertions:
 is_valid()
The documentation for this class was generated from the following file:
include/FLAC++/metadata.h
Copyright (c) 2000,2001,2002,2003,2004,2005,2006,2007 Josh Coalson