/*
 * Automatically generated C config: don't edit
 */
#define AUTOCONF_INCLUDED

/*
 * Library Configuration
 */

/*
 * Force build (Normally built when required)
 */
#define CONFIG_LIB_LIBGMP_FORCE 1
#define CONFIG_LIB_LIBPTHREAD_FORCE 1
#define CONFIG_LIB_LIBNVRAM_FORCE 1
#undef  CONFIG_LIB_LIBNTFS3G_FORCE
#undef  CONFIG_LIB_LIBBT_FORCE
#undef  CONFIG_LIB_READLINE_FORCE
#undef  CONFIG_LIB_NL_FORCE
#undef  CONFIG_LIB_LIBPCAP_FORCE
#undef  CONFIG_LIB_LIBEVENT_FORCE
#undef  CONFIG_LIB_NCURSE_FORCE
#define CONFIG_LIB_FLEX_FORCE 1
#define CONFIG_LIB_LIBUPNP_FORCE 1
#undef  CONFIG_LIB_LIBDLNA_FORCE
#define CONFIG_LIB_LIBFFMPEG_FORCE 1
#undef  CONFIG_LIB_LIBGDBM_FORCE
#define CONFIG_LIB_LIBID3TAG_FORCE 1
#define CONFIG_LIB_LIBSQLITE3_FORCE 1
#define CONFIG_LIB_LIBEXIF_FORCE 1
#define CONFIG_LIB_LIBOGG_FORCE 1
#define CONFIG_LIB_LIBVORBIS_FORCE 1
#define CONFIG_LIB_LIBFLAC_FORCE 1
#define CONFIG_LIB_LIBJPEG_FORCE 1
#undef  CONFIG_LIB_LIBDB_FORCE
#undef  CONFIG_LIB_USB0112_FORCE
#define CONFIG_LIB_USB100_FORCE 1
#define CONFIG_LIB_PCRE_FORCE 1
#undef  CONFIG_LIB_VSTR_FORCE
#define CONFIG_LIB_ZLIB_FORCE 1
#undef  CONFIG_LIB_LZO_FORCE
#undef  CONFIG_LIB_E2FSPROGS_FORCE
#undef  CONFIG_LIB_LIBSTDC_PLUS_FORCE
#define CONFIG_LIB_NSL_FORCE 1
#undef  CONFIG_USER_HELLO_WORLD
#define CONFIG_LIB_LIBPTHREAD_FORCE 1

/*
 * MTD utils
 */
#undef  CONFIG_USER_MTDUTILS
#undef  CONFIG_USER_MTDUTILS_DOCFDISK
#undef  CONFIG_USER_MTDUTILS_DOC_LOADBIOS
#undef  CONFIG_USER_MTDUTILS_FLASHCP
#undef  CONFIG_USER_MTDUTILS_FLASH_ERASE
#undef  CONFIG_USER_MTDUTILS_FLASH_ERASEALL
#undef  CONFIG_USER_MTDUTILS_FLASH_LOCK
#undef  CONFIG_USER_MTDUTILS_FLASH_OTP_DUMP
#undef  CONFIG_USER_MTDUTILS_FLASH_OTP_INFO
#undef  CONFIG_USER_MTDUTILS_FLASH_UNLOCK
#undef  CONFIG_USER_MTDUTILS_FTL_CHECK
#undef  CONFIG_USER_MTDUTILS_FTL_FORMAT
#undef  CONFIG_USER_MTDUTILS_JFFS2DUMP
#undef  CONFIG_USER_MTDUTILS_JFFS2READER
#undef  CONFIG_USER_MTDUTILS_MKFSJFFS2
#undef  CONFIG_USER_MTDUTILS_MTD_DEBUG
#undef  CONFIG_USER_MTDUTILS_NANDDUMP
#undef  CONFIG_USER_MTDUTILS_NANDTEST
#undef  CONFIG_USER_MTDUTILS_NANDWRITE
#undef  CONFIG_USER_MTDUTILS_NFTLDUMP
#undef  CONFIG_USER_MTDUTILS_NFTL_FORMAT
#undef  CONFIG_USER_MTDUTILS_RECV_IMAGE
#undef  CONFIG_USER_MTDUTILS_RFDDUMP
#undef  CONFIG_USER_MTDUTILS_RFDFORMAT
#undef  CONFIG_USER_MTDUTILS_SERVE_IMAGE
#undef  CONFIG_USER_MTDUTILS_SUMTOOL
#undef  CONFIG_USER_MTDUTILS_MKFSUBIFS
#undef  CONFIG_USER_MTDUTILS_MTDINFO
#undef  CONFIG_USER_MTDUTILS_UBIATTACH
#undef  CONFIG_USER_MTDUTILS_UBICRC32
#undef  CONFIG_USER_MTDUTILS_UBIDETACH
#undef  CONFIG_USER_MTDUTILS_UBIFORMAT
#undef  CONFIG_USER_MTDUTILS_UBIMKVOL
#undef  CONFIG_USER_MTDUTILS_UBINFO
#undef  CONFIG_USER_MTDUTILS_UBINIZE
#undef  CONFIG_USER_MTDUTILS_UBIRENAME
#undef  CONFIG_USER_MTDUTILS_UBIRMVOL
#undef  CONFIG_USER_MTDUTILS_UBIRSVOL
#undef  CONFIG_USER_MTDUTILS_UBIUPDATEVOL

/*
 * Network Applications
 */
#undef  CONFIG_USER_3G
#define CONFIG_USER_ACCEL_PPTP 1
#define CONFIG_USER_PPPD_WITH_PPTP 1
#undef  CONFIG_USER_ARPTABLES
#undef  CONFIG_USER_BRCTL_BRCTL
#undef  CONFIG_USER_BIGPOND
#undef  CONFIG_USER_BT_UTILS
#undef  CONFIG_USER_BT_AVINFO
#undef  CONFIG_USER_BT_BCCMD
#undef  CONFIG_USER_BT_CIPTOOL
#undef  CONFIG_USER_BT_HCICONFIG
#undef  CONFIG_USER_BT_HCIATTACH
#undef  CONFIG_USER_BT_HCISECFILTER
#undef  CONFIG_USER_BT_HCITOOL
#undef  CONFIG_USER_BT_L2PING
#undef  CONFIG_USER_BT_PPPORC
#undef  CONFIG_USER_BT_SDPTOOL
#undef  CONFIG_USER_CTORRENT
#undef  CONFIG_USER_CPU
#undef  CONFIG_USER_DHCP6
#undef  CONFIG_USER_DHCP6_SERVER
#undef  CONFIG_USER_DHCP6_CLIENT
#define CONFIG_USER_WIDE_DHCPV6 1
#undef  CONFIG_IPV6_CE_ROUTER_TEST_DEBUG
#undef  CONFIG_USER_ISC_DHCP
#undef  CONFIG_USER_DROPBEAR
#define CONFIG_USER_USB_FW 1
#define CONFIG_USER_DNSMASQ 1
#undef  CONFIG_SAMBA_3_0_2
#define CONFIG_SAMBA_3_0_24 1
#undef  CONFIG_SAMBA_4_0_24
#undef  CONFIG_TIME_MACHINE
#undef  CONFIG_USER_NMBD_ONLY
#undef  CONFIG_USER_SAMBA_ALL
#define CONFIG_USER_LLMNR_NBNS 1
#define CONFIG_USER_MDNS 1
#define CONFIG_USER_XL2TPD 1
#undef  CONFIG_USER_DISKTYPE
#undef  CONFIG_USER_ECHO_SERVER
#undef  CONFIG_USER_EBTABLES
#undef  CONFIG_USER_HOSTAPD
#define CONFIG_UDHCPD 1
#define CONFIG_USER_STORAGE 1
#define CONFIG_USER_STUPID_FTPD 1
#define CONFIG_USER_PROFTPD 1
#define CONFIG_LIB_CRYPT_FORCE 1
#undef  CONFIG_USER_SAMBA
#define CONFIG_USER_MINIDLNA 1
#define CONFIG_LIB_LIBFFMPEG_FORCE 1
#define CONFIG_LIB_LIBID3TAG_FORCE 1
#define CONFIG_LIB_LIBSQLITE3_FORCE 1
#define CONFIG_LIB_LIBEXIF_FORCE 1
#define CONFIG_LIB_LIBOGG_FORCE 1
#define CONFIG_LIB_LIBVORBIS_FORCE 1
#define CONFIG_LIB_LIBFLAC_FORCE 1
#define CONFIG_LIB_LIBJPEG_FORCE 1
#define CONFIG_LIB_ZLIB_FORCE 1
#define CONFIG_USER_LIGHTY 1
#define CONFIG_LIB_PCRE_FORCE 1
#define CONFIG_LIB_ZLIB_FORCE 1
#undef  CONFIG_USER_ECMH
#define CONFIG_USER_IGMP_PROXY 1
#undef  CONFIG_USER_INADYN
#define CONFIG_USER_INADYN_MT 1
#define CONFIG_USER_IPTABLES_IPTABLES 1
#define CONFIG_LIB_LIBM_FORCE 1
#define CONFIG_USER_IPTABLES_IP6TABLES 1
#define CONFIG_USER_IPROUTE2 1
#undef  CONFIG_USER_IPROUTE2_SS
#undef  CONFIG_USER_IPROUTE2_ARPD
#undef  CONFIG_USER_IPROUTE2_NSTAT
#undef  CONFIG_USER_IPROUTE2_IFSTAT
#undef  CONFIG_USER_IPROUTE2_RTACCT
#undef  CONFIG_USER_IPROUTE2_LNSTAT
#define CONFIG_USER_IPROUTE2_IP 1
#undef  CONFIG_USER_IPROUTE2_RTMON
#define CONFIG_USER_IPROUTE2_TC 1
#define CONFIG_LIB_LIBM_FORCE 1
#undef  CONFIG_USER_MATRIXSSL
#define CONFIG_USER_MINIUPNPD 1
#undef  CONFIG_USER_MKDOSFS
#define CONFIG_USER_NTPCLIENT_NTPCLIENT 1
#undef  CONFIG_USER_NTPCLIENT_ADJTIMEX
#define CONFIG_USER_OPENSSL 1
#define CONFIG_USER_OPENL2TP 1
#define CONFIG_USER_PPPD_WITH_L2TP 1
#define CONFIG_LIB_FLEX_FORCE 1
#define CONFIG_USER_OPENSWAN 1
#undef  CONFIG_USER_P910ND
#undef  CONFIG_USER_PARPROUTED
#define CONFIG_USER_PPP_PPPOE 1
#undef  CONFIG_USER_OPENL2TP_MTK
#undef  CONFIG_USER_PPP_MTK
#define CONFIG_USER_PPPD 1
#undef  CONFIG_USER_PPPD_WITH_PPPOE
#define CONFIG_USER_PPPD_WITH_L2TP 1
#define CONFIG_USER_PPPD_WITH_PPTP 1
#undef  CONFIG_USER_PPPD_PPPSTATS
#undef  CONFIG_USER_PPPD_PPPDUMP
#undef  CONFIG_USER_PPPD_PPPCHAT
#define CONFIG_USER_RPPPPOE_RELAY 1
#undef  CONFIG_USER_RPPPPOE_SNIFF
#undef  CONFIG_USER_PPPOECD
#undef  CONFIG_USER_PPTP_CLIENT
#undef  CONFIG_USER_ZEBRA
#undef  CONFIG_LIB_LIBZEBRA_FORCE
#define CONFIG_USER_QUAGGA 1
#undef  CONFIG_USER_RP_L2TP
#define CONFIG_USER_RADVD 1
#undef  CONFIG_USER_RADVD_DUMP
#define CONFIG_USER_802_1X 1
#undef  CONFIG_USER_RT2561_802_1X
#undef  CONFIG_SIGMA_DUT
#undef  CONFIG_USER_SNORT
#undef  CONFIG_USER_SNMPD
#undef  CONFIG_USER_TOTD
#undef  CONFIG_USER_UVC_STREAM
#undef  CONFIG_USER_UPNP_IGD
#undef  CONFIG_USER_WPA_SUPPLICANT
#undef  CONFIG_USER_WSC
#define CONFIG_USER_BNDSTRG 1

/*
 * Wireless-tools
 */
#define CONFIG_USER_WIRELESS_TOOLS 1
#define CONFIG_USER_WIRELESS_TOOLS_IWCONFIG 1
#undef  CONFIG_USER_WIRELESS_TOOLS_IWGETID
#undef  CONFIG_USER_WIRELESS_TOOLS_IWLIST
#define CONFIG_USER_WIRELESS_TOOLS_IWPRIV 1
#undef  CONFIG_USER_WIRELESS_TOOLS_IWSPY
#undef  CONFIG_USER_WIRELESS_TOOLS_IWEVENT
#undef  CONFIG_USER_RALINKIAPPD
#undef  CONFIG_USER_MTKIAPPD

/*
 * Bluetooth-apps
 */
#undef  CONFIG_USER_BLUEANGEL
#undef  CONFIG_USER_BLUEANGEL_MTKBT
#undef  CONFIG_USER_BLUEANGEL_BTCLI
#undef  CONFIG_USER_BTCLI_ON
#undef  CONFIG_USER_BLUEANGEL_RELAYER
#define CONFIG_ARP_SPOOFING_PROTECT 1
#define CONFIG_SYN_UPGRADE_SUPPORT 1
#define CONFIG_MULTI_WAN_SUPPORT 1

/*
 * Miscellaneous Applications
 */
#define CONFIG_USER_BUSYBOX_BUSYBOX 1
#undef  CONFIG_USER_BONNIE
#undef  CONFIG_USER_CACHEBENCH
#undef  CONFIG_USER_ETHTOOL
#undef  CONFIG_DHRYSTONE
#undef  CONFIG_DHCPFWD
#undef  CONFIG_USER_GDBREPLAY
#undef  CONFIG_USER_GDBSERVER
#undef  CONFIG_USER_IXIA_ENDPOINT
#undef  CONFIG_USER_IPERF
#undef  CONFIG_USER_I2C_TOOLS
#undef  CONFIG_USER_LMBENCH3
#define CONFIG_USER_MTD_WRITE 1
#define CONFIG_USER_MPSTAT 1
#undef  CONFIG_USER_NBENCH
#undef  CONFIG_USER_NETCAT
#undef  CONFIG_USER_NETSTAT_NAT
#undef  CONFIG_USER_NTFS3G
#undef  CONFIG_USER_NTFSPROGS
#undef  CONFIG_LIB_LIBNTFS3G_FORCE
#undef  CONFIG_USER_STRACE_STRACE
#undef  CONFIG_USER_TCPDUMP
#undef  CONFIG_USER_TASKSET
#define CONFIG_USER_PCIUTIL_LSPCI 1
#undef  CONFIG_USER_PCIUTIL_SETPCI
#define CONFIG_LIB_ZLIB_FORCE 1
#define CONFIG_USER_LSUSB 1
#define CONFIG_LIB_USB100_FORCE 1
#undef  CONFIG_USER_USBMODESWITCH
#undef  CONFIG_USER_COMGT
#undef  CONFIG_USER_SDPARM
#undef  CONFIG_USER_WATCHDOG
#undef  CONFIG_USER_VMSTAT
#undef  CONFIG_USER_MOCAD2

/*
 * Proprietary Application
 */
#define CONFIG_RALINKAPP 1
#define CONFIG_RALINKAPP_ATED 1
#define CONFIG_RALINKAPP_REG_RW 1
#undef  CONFIG_RALINKAPP_CSR
#define CONFIG_RALINKAPP_FLASH 1
#define CONFIG_FLASH_TOOL 1
#define CONFIG_ETHMAC_TOOL 1
#define CONFIG_RALINKAPP_HWNAT 1
#define CONFIG_RALINKAPP_MII_MGR 1
#define CONFIG_RALINKAPP_NVRAM 1
#define CONFIG_LIB_LIBNVRAM_FORCE 1
#undef  CONFIG_RALINKAPP_L2_MANAGE
#define CONFIG_RALINKAPP_GPIO 1
#undef  CONFIG_RALINKAPP_SPI
#define CONFIG_RALINKAPP_I2C 1
#define CONFIG_USER_QOS 1
#define CONFIG_RALINKAPP_HWQOS 1
#undef  CONFIG_RALINKAPP_SWQOS
#define CONFIG_USER_IPROUTE2 1
#undef  CONFIG_RALINKAPP_SUPERDMZ
#define CONFIG_RALINKAPP_SWITCH 1
#undef  CONFIG_RALINKAPP_QDMA
#define CONFIG_RALINKAPP_SMART_SPEED 1
#define CONFIG_RALINKAPP_I2S 1
#define CONFIG_RALINKAPP_PCM 1
#define CONFIG_RALINKAPP_SPDIF 1
#define CONFIG_RALINKAPP_PCIE_PHY 1
#undef  CONFIG_RALINKAPP_CLS
#define CONFIG_RALINKAPP_HOTSPOT 1
#define CONFIG_RALINKAPP_SCRIPTS 1
#define CONFIG_RALINKAPP_BUSARB 1
#undef  CONFIG_RALINKAPP_KPROFILE
#undef  CONFIG_USER_NFCSD
#undef  CONFIG_USER_NFCHOD
#define CONFIG_DLINKAPP_ONETOUCH 1
#undef  CONFIG_SUPPORT_WIFI_CERT
#undef  CONFIG_IMG_CRYPT
#undef  CONFIG_MYDLINK_SUPPORT
#undef  CONFIG_OOKLA_SUPPORT
#undef  CONFIG_KWILT_SUPPORT
#undef  CONFIG_MCAFEE_SUPPORT
#undef  CONFIG_USER_IPSET
#undef  CONFIG_USE_NAND_FLASH

/*
 * Windows Rally Program
 */
#define CONFIG_USER_LLTD 1

/*
 * Phone Management
 */
#undef  CONFIG_MTK_VOIP

/*
 * Time Machine
 */
#define CONFIG_LIB_DB 1
#define CONFIG_LIB_GPGERROR 1
#define CONFIG_LIB_CRYPT151 1

/*
 * Remote Management
 */
#undef  CONFIG_MTK_TR069
#define CONFIG_CUSTOM_PRODUCT "DIR-882"
#define CONFIG_CUSTOM_SW_EX_VERSION "V1.11"
#define CONFIG_CUSTOM_SW_IN_VERSION "B01"
#define CONFIG_CUSTOM_HW_VERSION "A1"
#define CONFIG_VENDOR "Mediatek"
#define CONFIG_PRODUCT "DIR_882_VLAN"
#define CONFIG_LINUXDIR "linux-3.10.14.x"
#define CONFIG_LIBCDIR ""
#define CONFIG_LANGUAGE ""
#define VENDORS_AUTOCONF_INCLUDED
#undef AUTOCONF_INCLUDED
