/******************************************************************************
  Copyright (c), 1991-2007, T&W ELECTRONICS(SHENTHEN) Co., Ltd.

  文件名称: tbserror.h
  文件描述: 统一TBS内部错误码定义及处理
  函数列表:
            inline const char *tbsstrerr (int errnum)
  修订记录:
         1. 作者: tbs
            日期: 2007-12-28
            内容: 创建文件
         2. 作者: huangce
            日期: 2008-03-19
            内容: 修改文件
 ******************************************************************************/


#ifndef __TBS_TBSERROR_H__
#define __TBS_TBSERROR_H__

#include <stdio.h>
#include <stdlib.h>
#include "tbstype.h"
#include "autoconf.h"

/*--------------------错误码列表--------------------------*/
enum
{
        /*--------------------通用错误码返回值定义--------------------------*/
    TBS_SUCCESS                                 = 0,        /* 成功/正常*/
    TBS_FAILED                                    = -1,   /* 失败/一般错误*/
    TBS_MSG_SEND_ERR                        = -2,   /* 消息发送失败*/
    TBS_OUT_OF_MEM                            = -3,   /* 内存不足*/
    TBS_PARAM_ERR                                = -4,   /* 参数不正确*/
    TBS_OUT_OF_SRC                            = -5,   /* 其它资源不足, 如控制块...*/
    TBS_TIME_OUT                                = -6,   /* 超时*/
    TBS_COLLISION                                = -7,   /* 冲突, 如共享错误/非法重入...*/
    TBS_NULL_PTR                                = -8,   /* 空指针 */

    /* 下面是双链表的常用错误码 */
    TBS_LIST_NOT_EMPTY                    = -9,    /* List is not empty */
    TBS_LIST_EMPTY                            = -10,   /* List is empty */
    TBS_INVALID_INDEX                        = -11,   /* Invalid index, valid index range: 0x1 ~ 0xffffffff */
    TBS_INDEX_OVERFLOW                    = -12,   /* Index overflow, valid index range: 0x1 ~ 0xffffffff */
    TBS_CORRUPT_STRUCT                    = -13,   /* Corrupt struct, meaning struct is not initialized properly */

    TBS_NO_INSTANCE                    = -14,/*没有对应的实例*/
    TBS_MODULE_BUSY                       = -15 , /* 模块忙，暂不处理设置类消息*/

    /*--------------------TR069相关通用错误码返回值定义--------------------------*/
    TR069_ERRNO_UNSUP_FUNC            = 9000,  /* 方法不支持*/
    TR069_ERRNO_REJECT                    = 9001,  /* 拒绝请求, 未说明原因*/
    TR069_ERRNO_CPE_ERR                    = 9002,  /* 内部错误*/
    TR069_ERRNO_INVALID_PARAM        = 9003,  /* 无效参数*/
    TR069_ERRNO_NO_RESOURCE            = 9004,  /* 资源超限（当用于SetParameterValues的关联时，它不得用来指示参数错误）*/
    TR069_ERRNO_INVALID_NAME        = 9005,  /* 无效参数名（与Set/GetParameterValues，GetParameterNames，Set/GetParameterAttributes相关）*/
    TR069_ERRNO_INVALID_TYPE        = 9006,  /* 无效参数类型（与SetParameterValues相关）*/
    TR069_ERRNO_INVALID_VAL            = 9007,  /* 无效参数值（与SetParameterValues相关）*/
    TR069_ERRNO_WRITE_FORBID        = 9008,  /* 试图设置不可写的参数（与SetParameterValues相关）*/
    TR069_ERRNO_NOTI_REQ_REJ        = 9009,  /* 参数变更通知请求被拒绝（与SetParameterAttributes方法相关）*/
    TR069_ERRNO_DOWNLOAD_FAIL        = 9010,  /* 下载失败（与Download或TransferComplete方法相关）*/
    TR069_ERRNO_UPLOAD_FAIL            = 9011,  /* 上载失败（与Upload或TransferComplete方法相关）*/
    TR069_ERRNO_FS_AUTHFAIL            = 9012,  /* 文件传输服务器验证失败（与Upload或TransferComplete方法相关）*/
    TR069_ERRNO_FS_NOTSUPP            = 9013,  /* 不支持的文件传输协议（与Upload或TransferComplete方法相关）*/
    TR069_ERRNO_INVALID_IGMP           =9014,  /* 下载失败：无法加入组播组 (与Download,TransferComplete 或 AutonomousTransferComplete方法相关) */
    TR069_ERRNO_INVALID_URL           = 9015,  /* 下载失败：无法连接服务器 (与Download,TransferComplete 或 AutonomousTransferComplete方法相关) */

    ERR_UNKNOWN                                                  /* 必须是最后一个，添加时在此前面添加错误码 */

};




#define TBS_ERR_BASE_ADDR      1000
#define TBS_ERR_CVT(err, std)  ((((unsigned short)(err)) << 16) | (unsigned short)(std))

/* logic 进程中的模块用该宏确定基址 */
#define TBS_ERR_LOGIC_BASE_ADDR(mid) (TBS_ERR_BASE_ADDR + ((mid & 0x00ff)) * 100)

/* 非logic 进程中的模块用该宏确定基址 */
#define TBS_ERR_OUT_PROC_BASE_ADDR   7000
#define TBS_ERR_PROC_BASE_ADDR(mid) (TBS_ERR_OUT_PROC_BASE_ADDR + ((mid >> 8)) * 100)


#define TBS_ERR_STAND(err)    (unsigned short)(((unsigned long)err) & 0x0000ffff)
#define TBS_ERR_INTERNAL(err)    (unsigned short)(((unsigned long)err) >> 16)


/* 公共 */
#define ERR_COMMON_BEGIN_ADDR  TBS_ERR_LOGIC_BASE_ADDR(0)

#define ERR_NOT_SUPPORT_FUNCTION        TBS_ERR_CVT(ERR_COMMON_BEGIN_ADDR + 1,  TR069_ERRNO_INVALID_VAL)
#define ERR_IP_INVALID_FORMAT           TBS_ERR_CVT(ERR_COMMON_BEGIN_ADDR + 2, TR069_ERRNO_INVALID_VAL)
#define ERR_PORT_INVALID_FORMAT         TBS_ERR_CVT(ERR_COMMON_BEGIN_ADDR + 3, TR069_ERRNO_INVALID_VAL)
#define ERR_PORT_TOO_SMALL              TBS_ERR_CVT(ERR_COMMON_BEGIN_ADDR + 4, TR069_ERRNO_INVALID_VAL)
#define ERR_PORT_TOO_BIG                TBS_ERR_CVT(ERR_COMMON_BEGIN_ADDR + 5, TR069_ERRNO_INVALID_VAL)
#define ERR_PRIORITY_INVALID_VALUE      TBS_ERR_CVT(ERR_COMMON_BEGIN_ADDR + 6, TR069_ERRNO_INVALID_VAL)
#define ERR_PRIORITY_TOO_SMALL          TBS_ERR_CVT(ERR_COMMON_BEGIN_ADDR + 7, TR069_ERRNO_INVALID_VAL)
#define ERR_PRIORITY_TOO_BIG            TBS_ERR_CVT(ERR_COMMON_BEGIN_ADDR + 8, TR069_ERRNO_INVALID_VAL)
#define ERR_MASK_INVALID_FORMAT         TBS_ERR_CVT(ERR_COMMON_BEGIN_ADDR + 9, TR069_ERRNO_INVALID_VAL)
#define ERR_MASK_EMPTY                  TBS_ERR_CVT(ERR_COMMON_BEGIN_ADDR + 10, TR069_ERRNO_INVALID_VAL)
#define ERR_MAKS_ALL_ZERO               TBS_ERR_CVT(ERR_COMMON_BEGIN_ADDR + 11, TR069_ERRNO_INVALID_VAL)
#define ERR_MASK_INVALID_VALUE          TBS_ERR_CVT(ERR_COMMON_BEGIN_ADDR + 12, TR069_ERRNO_INVALID_VAL)
#define ERR_ENABLE_EMPTY                TBS_ERR_CVT(ERR_COMMON_BEGIN_ADDR + 13, TR069_ERRNO_INVALID_VAL)
#define ERR_ENABLE_INVALID_VALUE        TBS_ERR_CVT(ERR_COMMON_BEGIN_ADDR + 14, TR069_ERRNO_INVALID_VAL)
#define ERR_INT_INVALID_VALUE           TBS_ERR_CVT(ERR_COMMON_BEGIN_ADDR + 15, TR069_ERRNO_INVALID_VAL)
#define ERR_UINT_INVALID_VALUE          TBS_ERR_CVT(ERR_COMMON_BEGIN_ADDR + 16, TR069_ERRNO_INVALID_VAL)
#define ERR_MAC_INVALID_VALUE           TBS_ERR_CVT(ERR_COMMON_BEGIN_ADDR + 17, TR069_ERRNO_INVALID_VAL)
#define ERR_IPLIST_TOO_MANY             TBS_ERR_CVT(ERR_COMMON_BEGIN_ADDR + 18, TR069_ERRNO_INVALID_VAL)
#define ERR_IPLIST_INVALID_FORMAT       TBS_ERR_CVT(ERR_COMMON_BEGIN_ADDR + 19, TR069_ERRNO_INVALID_VAL)
#define ERR_MACLIST_INVALID_FORMAT      TBS_ERR_CVT(ERR_COMMON_BEGIN_ADDR + 20, TR069_ERRNO_INVALID_VAL)
#define ERR_MACLIST_TOO_MANY            TBS_ERR_CVT(ERR_COMMON_BEGIN_ADDR + 21, TR069_ERRNO_INVALID_VAL)
#define ERR_INSTANCE_TOO_MANY           TBS_ERR_CVT(ERR_COMMON_BEGIN_ADDR + 22, TR069_ERRNO_INVALID_VAL)
#define ERR_INSTANCE_IMMUTABLE          TBS_ERR_CVT(ERR_COMMON_BEGIN_ADDR + 23, TR069_ERRNO_INVALID_VAL)
#define ERR_INNER_MSG_INVALID           TBS_ERR_CVT(ERR_COMMON_BEGIN_ADDR + 24, TR069_ERRNO_CPE_ERR)
#define ERR_INNER_MSG_REPEATED_NAME     TBS_ERR_CVT(ERR_COMMON_BEGIN_ADDR + 25, TR069_ERRNO_REJECT)
#define ERR_INNER_CACHE_INVALID         TBS_ERR_CVT(ERR_COMMON_BEGIN_ADDR + 26, TR069_ERRNO_REJECT)
#define ERR_USERNAME                    TBS_ERR_CVT(ERR_COMMON_BEGIN_ADDR + 27, TR069_ERRNO_INVALID_VAL)
#define ERR_PASSWORD                    TBS_ERR_CVT(ERR_COMMON_BEGIN_ADDR + 28, TR069_ERRNO_INVALID_VAL)
#define ERR_IP_MASK_NOT_MATCH           TBS_ERR_CVT(ERR_COMMON_BEGIN_ADDR + 29, TR069_ERRNO_INVALID_VAL)
#define ERR_ETH_INVALID_BITRATE         TBS_ERR_CVT(ERR_COMMON_BEGIN_ADDR + 30, TR069_ERRNO_INVALID_VAL)
#define ERR_ETH_INVALID_DUPLEXMODE      TBS_ERR_CVT(ERR_COMMON_BEGIN_ADDR + 31, TR069_ERRNO_INVALID_VAL)
#define ERR_IP_IS_CAST_ADDR             TBS_ERR_CVT(ERR_COMMON_BEGIN_ADDR + 32, TR069_ERRNO_INVALID_VAL)
#define ERR_IP_IS_HOST_ADDR             TBS_ERR_CVT(ERR_COMMON_BEGIN_ADDR + 33, TR069_ERRNO_INVALID_VAL)
#define ERR_IP_ADDR_START_MINOR_END     TBS_ERR_CVT(ERR_COMMON_BEGIN_ADDR + 34, TR069_ERRNO_INVALID_VAL)
#define ERR_IP_ADDR_POOL_OVERLAP        TBS_ERR_CVT(ERR_COMMON_BEGIN_ADDR + 35, TR069_ERRNO_INVALID_VAL)
#define ERR_STR_TOO_LONG                TBS_ERR_CVT(ERR_COMMON_BEGIN_ADDR + 36, TR069_ERRNO_INVALID_VAL)
#define ERR_CAN_NOT_EMPTY               TBS_ERR_CVT(ERR_COMMON_BEGIN_ADDR + 37, TR069_ERRNO_INVALID_VAL)
#define ERR_GET_NODE_VALUE_FAIL         TBS_ERR_CVT(ERR_COMMON_BEGIN_ADDR + 38, TR069_ERRNO_INVALID_VAL)
#define ERR_SET_NODE_VALUE_FAIL         TBS_ERR_CVT(ERR_COMMON_BEGIN_ADDR + 39, TR069_ERRNO_INVALID_VAL)
#define ERR_INVALID_DOMAIN_NAME         TBS_ERR_CVT(ERR_COMMON_BEGIN_ADDR + 40, TR069_ERRNO_INVALID_VAL)
#define ERR_OUT_OF_RANGE                TBS_ERR_CVT(ERR_COMMON_BEGIN_ADDR + 41, TR069_ERRNO_INVALID_VAL)
#define ERR_IPLIST_HAS_REPEAT           TBS_ERR_CVT(ERR_COMMON_BEGIN_ADDR + 42, TR069_ERRNO_INVALID_VAL)
#define ERR_IP_IS_WRONG_NET_SECTION     TBS_ERR_CVT(ERR_COMMON_BEGIN_ADDR + 43, TR069_ERRNO_INVALID_VAL)
#define ERR_IP_IS_CAST_OR_NET_ADDR      TBS_ERR_CVT(ERR_COMMON_BEGIN_ADDR + 44, TR069_ERRNO_INVALID_VAL)
#define ERR_ENABLE_DHCPS_CONFLICT_DHCPR TBS_ERR_CVT(ERR_COMMON_BEGIN_ADDR + 45, TR069_ERRNO_INVALID_VAL)
#define ERR_PORT_RANGE_INVALID          TBS_ERR_CVT(ERR_COMMON_BEGIN_ADDR + 46, TR069_ERRNO_INVALID_VAL)
#define ERR_INVALID_VAL                 TBS_ERR_CVT(ERR_COMMON_BEGIN_ADDR + 47, TR069_ERRNO_INVALID_VAL)
#define ERR_LIST_HAS_REPEAT             TBS_ERR_CVT(ERR_COMMON_BEGIN_ADDR + 48, TR069_ERRNO_INVALID_VAL)
#define ERR_USERNAMEORPASSWORD          TBS_ERR_CVT(ERR_COMMON_BEGIN_ADDR + 49, TR069_ERRNO_INVALID_VAL)


#define ERR_MSG_MID_INVALID             TBS_ERR_CVT(ERR_COMMON_BEGIN_ADDR + 60, TR069_ERRNO_INVALID_VAL)
#define ERR_MSG_SOCKET                  TBS_ERR_CVT(ERR_COMMON_BEGIN_ADDR + 61, TR069_ERRNO_INVALID_VAL)
#define ERR_MSG_PROC_NOT_FOUND          TBS_ERR_CVT(ERR_COMMON_BEGIN_ADDR + 62, TR069_ERRNO_INVALID_VAL)
#define ERR_MSG_SEND_FAIL               TBS_ERR_CVT(ERR_COMMON_BEGIN_ADDR + 63, TR069_ERRNO_INVALID_VAL)
#define ERR_MSG_DSTMID_UNREGED          TBS_ERR_CVT(ERR_COMMON_BEGIN_ADDR + 64, TR069_ERRNO_INVALID_VAL)
#define ERR_MSG_NOT_FULL                TBS_ERR_CVT(ERR_COMMON_BEGIN_ADDR + 65, TR069_ERRNO_INVALID_VAL)
#define ERR_MSG_PART_NOEFFECT           TBS_ERR_CVT(ERR_COMMON_BEGIN_ADDR + 66, TR069_ERRNO_INVALID_VAL)
#define ERR_MSG_PART_INVALID            TBS_ERR_CVT(ERR_COMMON_BEGIN_ADDR + 67, TR069_ERRNO_INVALID_VAL)
#define ERR_MSG_TIMEOUT                 TBS_ERR_CVT(ERR_COMMON_BEGIN_ADDR + 68, TR069_ERRNO_INVALID_VAL)
#define ERR_MSG_PART_LIST_FULL          TBS_ERR_CVT(ERR_COMMON_BEGIN_ADDR + 69, TR069_ERRNO_INVALID_VAL)

#define ERR_MALLOC_FAILED               TBS_ERR_CVT(ERR_COMMON_BEGIN_ADDR + 70, TR069_ERRNO_CPE_ERR)
#define ERR_BUF_NOT_ENOUGH              TBS_ERR_CVT(ERR_COMMON_BEGIN_ADDR + 71, TR069_ERRNO_CPE_ERR)
#define ERR_INTERNAL_ERR                TBS_ERR_CVT(ERR_COMMON_BEGIN_ADDR + 72, TR069_ERRNO_CPE_ERR)
#define ERR_PARA_INVALID                TBS_ERR_CVT(ERR_COMMON_BEGIN_ADDR + 73, TR069_ERRNO_CPE_ERR)
#define ERR_FILE_OPEN                   TBS_ERR_CVT(ERR_COMMON_BEGIN_ADDR + 74, TR069_ERRNO_CPE_ERR)
#define ERR_FILE_READ                   TBS_ERR_CVT(ERR_COMMON_BEGIN_ADDR + 75, TR069_ERRNO_CPE_ERR)
#define ERR_FILE_WRITE                  TBS_ERR_CVT(ERR_COMMON_BEGIN_ADDR + 76, TR069_ERRNO_CPE_ERR)
#define ERR_FILE_CHKSUM                 TBS_ERR_CVT(ERR_COMMON_BEGIN_ADDR + 77, TR069_ERRNO_CPE_ERR)
#define ERR_BUSY                        TBS_ERR_CVT(ERR_COMMON_BEGIN_ADDR + 78, TR069_ERRNO_CPE_ERR)
#define ERR_CREATE_MSG_FAIL             TBS_ERR_CVT(ERR_COMMON_BEGIN_ADDR + 79, TR069_ERRNO_CPE_ERR)
#define ERR_MSG_EXT_MID_LIST_FULL       TBS_ERR_CVT(ERR_COMMON_BEGIN_ADDR + 80, TR069_ERRNO_CPE_ERR)
#define ERR_FILE_OPEN_EXSITED           TBS_ERR_CVT(ERR_COMMON_BEGIN_ADDR + 81, TR069_ERRNO_CPE_ERR)
#define ERR_FILE_WTITE_NOSPACE          TBS_ERR_CVT(ERR_COMMON_BEGIN_ADDR + 82, TR069_ERRNO_CPE_ERR)
#define ERR_FILE_NOT_ALLOWED            TBS_ERR_CVT(ERR_COMMON_BEGIN_ADDR + 83, TR069_ERRNO_CPE_ERR)
#define ERR_FILE_RM_UNKOWN              TBS_ERR_CVT(ERR_COMMON_BEGIN_ADDR + 84, TR069_ERRNO_CPE_ERR)
#define ERR_FILE_OPEN_UNKOWN            TBS_ERR_CVT(ERR_COMMON_BEGIN_ADDR + 85, TR069_ERRNO_CPE_ERR)
#define ERR_FILE_WRITE_UNKOWN           TBS_ERR_CVT(ERR_COMMON_BEGIN_ADDR + 86, TR069_ERRNO_CPE_ERR)
#define ERR_IP_INVALID_RANGE                TBS_ERR_CVT(ERR_COMMON_BEGIN_ADDR + 87, TR069_ERRNO_INVALID_VAL)
/*for ipv6*/
#define ERR_IPV6_INVALID_FORMAT         TBS_ERR_CVT(ERR_COMMON_BEGIN_ADDR + 88, TR069_ERRNO_INVALID_VAL)
#define ERR_IPV6_ADDR_REPEAT            TBS_ERR_CVT(ERR_COMMON_BEGIN_ADDR + 89, TR069_ERRNO_INVALID_VAL)
#define ERR_IPV6_INVALID_PREFIX_LEN     TBS_ERR_CVT(ERR_COMMON_BEGIN_ADDR + 90, TR069_ERRNO_INVALID_VAL)
#define ERR_IPV6_INVALID_DUID           TBS_ERR_CVT(ERR_COMMON_BEGIN_ADDR + 91, TR069_ERRNO_INVALID_VAL)
#define ERR_INVALID_PROTO_TYPE          TBS_ERR_CVT(ERR_COMMON_BEGIN_ADDR + 92, TR069_ERRNO_INVALID_VAL)
#define ERR_IPV6_PROFIXLEN_NOT_MATCH    TBS_ERR_CVT(ERR_COMMON_BEGIN_ADDR + 93, TR069_ERRNO_INVALID_VAL)

/* add by liuyousheng 2011.06.22 for QIMS18215 check digit-map */
#define ERR_VOIP_DIGIT_MAP_INVALID_FORMAT    TBS_ERR_CVT(ERR_COMMON_BEGIN_ADDR + 94, TR069_ERRNO_INVALID_VAL)
/* add end liuyousheng */
/* add by YangP on 20110708 for 检测电话号码长度Ticket #3095 ,QIMS[18127] */
#define ERR_VOIP_URI_LEN                 TBS_ERR_CVT(ERR_COMMON_BEGIN_ADDR + 95, TR069_ERRNO_INVALID_VAL)
/* add end */
/* add by YangP on 20110709 for 会话刷新周期与最小会话刷新周期之间的冲突检测，Q[]18054，T3096 */
#define ERR_VOIP_SessionUpdateTimer_SessionTimerMinSe   TBS_ERR_CVT(ERR_COMMON_BEGIN_ADDR + 96, TR069_ERRNO_INVALID_VAL)
/* add end */
/* add by YangP on 20110730 for Q19312,为PacketizationPeriod 设置输入限制 */
#define ERR_VOIP_PacketizationPeriod    TBS_ERR_CVT(ERR_COMMON_BEGIN_ADDR + 97, TR069_ERRNO_INVALID_VAL)
/* add end */
/* add by YangP on 20110830 for Q20611，URI in different line can not be the same with the other */
#define ERR_VOIP_URI_SAMEURI                 TBS_ERR_CVT(ERR_COMMON_BEGIN_ADDR + 98, TR069_ERRNO_INVALID_VAL)
/* add end */
/* fuhuoping add public in logic */
#define ERR_DESCRIPTION_DUPLICATE       TBS_ERR_CVT(ERR_COMMON_BEGIN_ADDR + 99, TR069_ERRNO_INVALID_VAL)
#define ERR_INVALID_IP_ADDR           	TBS_ERR_CVT(ERR_COMMON_BEGIN_ADDR + 100, TR069_ERRNO_INVALID_VAL)
#define ERR_MSG_GROUP_MID_LIST_FULL     TBS_ERR_CVT(ERR_COMMON_BEGIN_ADDR + 101, TR069_ERRNO_CPE_ERR)
#define ERR_INVALID_FILTER_MODE     TBS_ERR_CVT(ERR_COMMON_BEGIN_ADDR + 102, TR069_ERRNO_CPE_ERR)
#define ERR_INVALID_SCHEDULE_PATH     TBS_ERR_CVT(ERR_COMMON_BEGIN_ADDR + 103, TR069_ERRNO_CPE_ERR)


#ifdef CONFIG_LAST_SAVE_CFG
#define ERR_JFS_NOT_OPEN          TBS_ERR_CVT(ERR_COMMON_BEGIN_ADDR + 105,   TR069_ERRNO_INVALID_VAL)
#define ERR_SAVE_CFG          TBS_ERR_CVT(ERR_COMMON_BEGIN_ADDR + 106,   TR069_ERRNO_INVALID_VAL)
#define ERR_RECOVER_CFG          TBS_ERR_CVT(ERR_COMMON_BEGIN_ADDR + 107,   TR069_ERRNO_INVALID_VAL)
#endif


/* CMM */
#define ERR_CMM_BEGIN_ADDR     TBS_ERR_LOGIC_BASE_ADDR(MID_CMM)

#define ERR_CMM_NOMID          TBS_ERR_CVT(ERR_CMM_BEGIN_ADDR + 1,   TR069_ERRNO_CPE_ERR)
#define ERR_CMM_INVALID_INDEX  TBS_ERR_CVT(ERR_CMM_BEGIN_ADDR + 2,   TR069_ERRNO_CPE_ERR)
#define ERR_CMM_NOLEAF         TBS_ERR_CVT(ERR_CMM_BEGIN_ADDR + 3,   TR069_ERRNO_INVALID_NAME)
#define ERR_CMM_NOITEM         TBS_ERR_CVT(ERR_CMM_BEGIN_ADDR + 4,   TR069_ERRNO_INVALID_PARAM)
#define ERR_CMM_INVALID_PATH   TBS_ERR_CVT(ERR_CMM_BEGIN_ADDR + 5,   TR069_ERRNO_INVALID_NAME)
#define ERR_CMM_TIMEOUT        TBS_ERR_CVT(ERR_CMM_BEGIN_ADDR + 6,   TR069_ERRNO_CPE_ERR)


/* CFG */
#define ERR_CFG_BEGIN_ADDR     (TBS_ERR_LOGIC_BASE_ADDR(MID_CMM) + 50)

#define ERR_CFG_ATTR_STAT         TBS_ERR_CVT(ERR_CFG_BEGIN_ADDR + 1,  TR069_ERRNO_INVALID_NAME)
#define ERR_CFG_PATH_NOT_EXSITED  TBS_ERR_CVT(ERR_CFG_BEGIN_ADDR + 2,  TR069_ERRNO_INVALID_NAME)
#define ERR_CFG_INVALID_OBJ_VAL   TBS_ERR_CVT(ERR_CFG_BEGIN_ADDR + 3,  TR069_ERRNO_INVALID_NAME)
#define ERR_CFG_INVALID_STRING    TBS_ERR_CVT(ERR_CFG_BEGIN_ADDR + 4,  TR069_ERRNO_INVALID_VAL)
#define ERR_CFG_INVALID_INT_0     TBS_ERR_CVT(ERR_CFG_BEGIN_ADDR + 5,  TR069_ERRNO_INVALID_VAL)
#define ERR_CFG_INVALID_INT_01    TBS_ERR_CVT(ERR_CFG_BEGIN_ADDR + 6,  TR069_ERRNO_INVALID_VAL)
#define ERR_CFG_INVALID_INT_A     TBS_ERR_CVT(ERR_CFG_BEGIN_ADDR + 7,  TR069_ERRNO_INVALID_VAL)
#define ERR_CFG_INVALID_UINT_0    TBS_ERR_CVT(ERR_CFG_BEGIN_ADDR + 8,  TR069_ERRNO_INVALID_VAL)
#define ERR_CFG_INVALID_UINT_01   TBS_ERR_CVT(ERR_CFG_BEGIN_ADDR + 9,  TR069_ERRNO_INVALID_VAL)
#define ERR_CFG_INVALID_UINT_A    TBS_ERR_CVT(ERR_CFG_BEGIN_ADDR + 10, TR069_ERRNO_INVALID_VAL)
#define ERR_CFG_INVALID_BOOL      TBS_ERR_CVT(ERR_CFG_BEGIN_ADDR + 11, TR069_ERRNO_INVALID_VAL)
#define ERR_CFG_INVALID_TIME      TBS_ERR_CVT(ERR_CFG_BEGIN_ADDR + 12, TR069_ERRNO_INVALID_VAL)
#define ERR_CFG_INVALID_HEX       TBS_ERR_CVT(ERR_CFG_BEGIN_ADDR + 13, TR069_ERRNO_INVALID_VAL)
#define ERR_CFG_NOT_WRITABLE      TBS_ERR_CVT(ERR_CFG_BEGIN_ADDR + 14, TR069_ERRNO_WRITE_FORBID)
#define ERR_CFG_NOT_IN_ACCESSLIST TBS_ERR_CVT(ERR_CFG_BEGIN_ADDR + 15, TR069_ERRNO_WRITE_FORBID)
#define ERR_CFG_PATH_NOT_INST     TBS_ERR_CVT(ERR_CFG_BEGIN_ADDR + 16, TR069_ERRNO_INVALID_VAL)
#define ERR_CFG_NOT_STANDARD      TBS_ERR_CVT(ERR_CFG_BEGIN_ADDR + 17, TR069_ERRNO_INVALID_VAL)
#define ERR_CFG_INVALID_TYPE      TBS_ERR_CVT(ERR_CFG_BEGIN_ADDR + 18,  TR069_ERRNO_CPE_ERR)
#define ERR_CFG_ITEM_OPT_FAIL     TBS_ERR_CVT(ERR_CFG_BEGIN_ADDR + 19,  TR069_ERRNO_CPE_ERR)
#define ERR_CFG_WILDCARD_QUE_FULL TBS_ERR_CVT(ERR_CFG_BEGIN_ADDR + 20,  TR069_ERRNO_CPE_ERR)

#define ERR_CFG_INVALID_PATH      TBS_ERR_CVT(ERR_CFG_BEGIN_ADDR + 21,  TR069_ERRNO_INVALID_NAME)
#define ERR_CFG_OBJ_INST_FULL     TBS_ERR_CVT(ERR_CFG_BEGIN_ADDR + 22,  TR069_ERRNO_NO_RESOURCE)
#define ERR_CFG_TIME_OUT          TBS_ERR_CVT(ERR_CFG_BEGIN_ADDR + 23,  TR069_ERRNO_NO_RESOURCE)
#define ERR_CFG_FILE_FOTMAT       TBS_ERR_CVT(ERR_CFG_BEGIN_ADDR + 24,  TR069_ERRNO_INVALID_VAL)
#define ERR_CFG_REJECT_ATTR_SET     TBS_ERR_CVT(ERR_CFG_BEGIN_ADDR + 25,  TR069_ERRNO_NOTI_REQ_REJ)


/* AUTH */
#define ERR_AUTH_BEGIN_ADDR         TBS_ERR_LOGIC_BASE_ADDR(MID_AUTH)
#define ERR_AUTH_TYPE               TBS_ERR_CVT(ERR_AUTH_BEGIN_ADDR + 1, TR069_ERRNO_INVALID_VAL)
#define ERR_AUTH_CANNOT_CHANGE_USER              TBS_ERR_CVT(ERR_AUTH_BEGIN_ADDR + 2, TR069_ERRNO_INVALID_VAL)
#define ERR_AUTH_CANNOT_CHANGE_LEVEL             TBS_ERR_CVT(ERR_AUTH_BEGIN_ADDR + 3, TR069_ERRNO_INVALID_VAL)
#define ERR_AUTH_CANNOT_REMOVE_ADMIN             TBS_ERR_CVT(ERR_AUTH_BEGIN_ADDR + 4, TR069_ERRNO_INVALID_VAL)
#define ERR_AUTH_HAVE_SAME_USER             TBS_ERR_CVT(ERR_AUTH_BEGIN_ADDR + 5, TR069_ERRNO_INVALID_VAL)
#define ERR_AUTH_PASSWORD_TOO_LONG TBS_ERR_CVT(ERR_AUTH_BEGIN_ADDR + 6, TR069_ERRNO_INVALID_VAL)
#define ERR_AUTH_USERNAME_TOO_LONG TBS_ERR_CVT(ERR_AUTH_BEGIN_ADDR + 7, TR069_ERRNO_INVALID_VAL)

#define ERR_AUTH_SESSION_FULL           TBS_ERR_CVT(ERR_AUTH_BEGIN_ADDR + 8, TR069_ERRNO_NO_RESOURCE)
#define ERR_AUTH_WRONG_USER             TBS_ERR_CVT(ERR_AUTH_BEGIN_ADDR + 9, TR069_ERRNO_INVALID_VAL)
#define ERR_AUTH_WRONG_PASSWORD         TBS_ERR_CVT(ERR_AUTH_BEGIN_ADDR + 10, TR069_ERRNO_INVALID_VAL)
#define ERR_AUTH_WRONG_USER_OR_PWD      TBS_ERR_CVT(ERR_AUTH_BEGIN_ADDR + 11, TR069_ERRNO_INVALID_VAL)
#define ERR_AUTH_SESSION_TIMEOUT        TBS_ERR_CVT(ERR_AUTH_BEGIN_ADDR + 12, TR069_ERRNO_INVALID_VAL)
#define ERR_AUTH_SESSION_ILLEGAL        TBS_ERR_CVT(ERR_AUTH_BEGIN_ADDR + 13, TR069_ERRNO_INVALID_VAL)
#define ERR_AUTH_LOGIN_FREQUENT         TBS_ERR_CVT(ERR_AUTH_BEGIN_ADDR + 14, TR069_ERRNO_INVALID_VAL)
#define ERR_AUTH_LOGOUT_SUCCESS         TBS_ERR_CVT(ERR_AUTH_BEGIN_ADDR + 15, TR069_ERRNO_INVALID_VAL)
#define ERR_AUTH_OLDPASSWORD_INVALID  TBS_ERR_CVT(ERR_AUTH_BEGIN_ADDR + 16, TR069_ERRNO_INVALID_VAL)

/* PING */
#define ERR_DGN_BEGIN_ADDR     TBS_ERR_LOGIC_BASE_ADDR(MID_DGN)

#define ERR_DGN_INVALID_STATE    TBS_ERR_CVT(ERR_DGN_BEGIN_ADDR + 2, TR069_ERRNO_INVALID_VAL)
#define ERR_DGN_INVALID_INTF     TBS_ERR_CVT(ERR_DGN_BEGIN_ADDR + 3, TR069_ERRNO_INVALID_VAL)
#define ERR_DGN_INVALID_HOST_IP_PART  TBS_ERR_CVT(ERR_DGN_BEGIN_ADDR + 4, TR069_ERRNO_INVALID_VAL)
#define ERR_DGN_INVALID_HOST_IP_OCT   TBS_ERR_CVT(ERR_DGN_BEGIN_ADDR + 5, TR069_ERRNO_INVALID_VAL)
#define ERR_DGN_INVALID_HOST_BEGIN    TBS_ERR_CVT(ERR_DGN_BEGIN_ADDR + 6, TR069_ERRNO_INVALID_VAL)
#define ERR_DGN_INVALID_TIMES    TBS_ERR_CVT(ERR_DGN_BEGIN_ADDR + 7, TR069_ERRNO_INVALID_VAL)
#define ERR_DGN_INVALID_TO       TBS_ERR_CVT(ERR_DGN_BEGIN_ADDR + 8, TR069_ERRNO_INVALID_VAL)
#define ERR_DGN_INVALID_SIZE     TBS_ERR_CVT(ERR_DGN_BEGIN_ADDR + 9, TR069_ERRNO_INVALID_VAL)
#define ERR_DGN_INVALID_DSCP     TBS_ERR_CVT(ERR_DGN_BEGIN_ADDR + 10, TR069_ERRNO_INVALID_VAL)
#define ERR_DGN_NOHOST           TBS_ERR_CVT(ERR_DGN_BEGIN_ADDR + 11, TR069_ERRNO_INVALID_VAL)
#define ERR_DGN_INVALID_HOST_A   TBS_ERR_CVT(ERR_DGN_BEGIN_ADDR + 12, TR069_ERRNO_INVALID_VAL)
#define ERR_DGN_INVALID_HOST_LEN TBS_ERR_CVT(ERR_DGN_BEGIN_ADDR + 13, TR069_ERRNO_INVALID_VAL)

#define ERR_DGN_MSG_FORMAT        TBS_ERR_CVT(ERR_DGN_BEGIN_ADDR + 14, TR069_ERRNO_INVALID_PARAM)
#define ERR_DGN_PATH              TBS_ERR_CVT(ERR_DGN_BEGIN_ADDR + 15, TR069_ERRNO_CPE_ERR)
#define ERR_DGN_NOSTART                     TBS_ERR_CVT(ERR_DGN_BEGIN_ADDR + 16, TR069_ERRNO_CPE_ERR)
#define ERR_DGN_NOITEM                      TBS_ERR_CVT(ERR_DGN_BEGIN_ADDR + 17, TR069_ERRNO_CPE_ERR)
#define ERR_DGN_INVALID_IP_TYPE   			TBS_ERR_CVT(ERR_DGN_BEGIN_ADDR + 18, TR069_ERRNO_CPE_ERR)
#define ERR_DGN_INVALID_INT                 TBS_ERR_CVT(ERR_DGN_BEGIN_ADDR + 19, TR069_ERRNO_INVALID_VAL)

/* CTPING */
#define ERR_CTPING_BEGIN_ADDR     TBS_ERR_LOGIC_BASE_ADDR(MID_CTPING)

#define ERR_CTPING_INVALID_VALUE    TBS_ERR_CVT(ERR_CTPING_BEGIN_ADDR + 2, TR069_ERRNO_INVALID_VAL)

/* COMMON HANDLER*/
#define ERR_FUNC_BEGIN_ADDR     TBS_ERR_LOGIC_BASE_ADDR(MID_CCP)

/* LAN */
#define ERR_LAN_BEGIN_ADDR     TBS_ERR_LOGIC_BASE_ADDR(MID_LAN)

#define ERR_LAN_INVALID_IP_FORMAT      TBS_ERR_CVT(ERR_LAN_BEGIN_ADDR + 1, TR069_ERRNO_INVALID_VAL)
#define ERR_LAN_INVALID_LAN_IP         TBS_ERR_CVT(ERR_LAN_BEGIN_ADDR + 2, TR069_ERRNO_INVALID_VAL)
#define ERR_LAN_MACLIST_TOO_LONG       TBS_ERR_CVT(ERR_LAN_BEGIN_ADDR + 3, TR069_ERRNO_INVALID_VAL)
#define ERR_LAN_INVALID_MACLIST        TBS_ERR_CVT(ERR_LAN_BEGIN_ADDR + 4, TR069_ERRNO_INVALID_VAL)
#define ERR_LAN_IP_MASK_CONFLICT       TBS_ERR_CVT(ERR_LAN_BEGIN_ADDR + 5, TR069_ERRNO_INVALID_VAL)
#define ERR_LAN_IP_CONFLICT            TBS_ERR_CVT(ERR_LAN_BEGIN_ADDR + 6, TR069_ERRNO_INVALID_VAL)
#define ERR_LAN_LAST_INSTANCE          TBS_ERR_CVT(ERR_LAN_BEGIN_ADDR + 7, TR069_ERRNO_INVALID_VAL)
#define ERR_LAN_TOO_MANY_INSTANCE      TBS_ERR_CVT(ERR_LAN_BEGIN_ADDR + 8, TR069_ERRNO_INVALID_VAL)
#define ERR_LAN_SAME_REGION_CONFLICT   TBS_ERR_CVT(ERR_LAN_BEGIN_ADDR + 9, TR069_ERRNO_INVALID_VAL)
#define ERR_LAN_NOT_EXIST                          TBS_ERR_CVT(ERR_LAN_BEGIN_ADDR + 10, TR069_ERRNO_INVALID_VAL)
#define ERR_LAN_NAME_TOO_LONG          TBS_ERR_CVT(ERR_LAN_BEGIN_ADDR + 11, TR069_ERRNO_INVALID_VAL)
#define ERR_LAN_SAME_NAME_CONFLICT     TBS_ERR_CVT(ERR_LAN_BEGIN_ADDR + 12, TR069_ERRNO_INVALID_VAL)
#define ERR_LAN_lINKLOCAL_CONFLICT     TBS_ERR_CVT(ERR_LAN_BEGIN_ADDR + 13, TR069_ERRNO_INVALID_VAL)
#define ERR_LAN_NAME_EMPTY             TBS_ERR_CVT(ERR_LAN_BEGIN_ADDR + 14, TR069_ERRNO_INVALID_VAL)
#define ERR_LAN_INVALID_IPV6_FORMAT    TBS_ERR_CVT(ERR_LAN_BEGIN_ADDR + 15, TR069_ERRNO_INVALID_VAL)


/* WAN */
#define ERR_WAN_BEGIN_ADDR     TBS_ERR_LOGIC_BASE_ADDR(MID_WAN)

#define ERR_WAN_INVALID_INNER_MSG  TBS_ERR_CVT(ERR_WAN_BEGIN_ADDR + 1, TR069_ERRNO_CPE_ERR)
#define ERR_WAN_INVALID_VAL        TBS_ERR_CVT(ERR_WAN_BEGIN_ADDR + 2, TR069_ERRNO_INVALID_VAL)
#define ERR_WAN_INVALID_SVC_LIST         TBS_ERR_CVT(ERR_WAN_BEGIN_ADDR + 3, TR069_ERRNO_INVALID_VAL)
#define ERR_WAN_INVALID_CONN_TYPE        TBS_ERR_CVT(ERR_WAN_BEGIN_ADDR + 4, TR069_ERRNO_INVALID_VAL)
#define ERR_WAN_INVALID_LAN_INTF         TBS_ERR_CVT(ERR_WAN_BEGIN_ADDR + 5, TR069_ERRNO_INVALID_VAL)
#define ERR_WAN_LAN_INTF_REPEAT          TBS_ERR_CVT(ERR_WAN_BEGIN_ADDR + 6, TR069_ERRNO_INVALID_VAL)
#define ERR_WAN_TOO_MORE_BRIDGE          TBS_ERR_CVT(ERR_WAN_BEGIN_ADDR + 7, TR069_ERRNO_INVALID_VAL)
#define ERR_WAN_BRIDGE_ROUTE_MIX         TBS_ERR_CVT(ERR_WAN_BEGIN_ADDR + 8, TR069_ERRNO_INVALID_VAL)
#define ERR_WAN_TR069_BRIDGE             TBS_ERR_CVT(ERR_WAN_BEGIN_ADDR + 9, TR069_ERRNO_INVALID_VAL)
#define ERR_WAN_TR069_LAN                TBS_ERR_CVT(ERR_WAN_BEGIN_ADDR + 10, TR069_ERRNO_INVALID_VAL)
#define ERR_WAN_INVALID_CONN_PRIOR       TBS_ERR_CVT(ERR_WAN_BEGIN_ADDR + 11, TR069_ERRNO_INVALID_VAL)
#define ERR_WAN_INVALID_VLAN_ID          TBS_ERR_CVT(ERR_WAN_BEGIN_ADDR + 11, TR069_ERRNO_INVALID_VAL)
#define ERR_WAN_INVALID_VLAN_PRIO        TBS_ERR_CVT(ERR_WAN_BEGIN_ADDR + 12, TR069_ERRNO_INVALID_VAL)
#define ERR_WAN_NOT_EXIST                TBS_ERR_CVT(ERR_WAN_BEGIN_ADDR + 13, TR069_ERRNO_INVALID_VAL)
#define ERR_WAN_DSL_LINK_CONFLICT        TBS_ERR_CVT(ERR_WAN_BEGIN_ADDR + 14, TR069_ERRNO_INVALID_VAL)
#define ERR_WAN_ETH_LINK_CONFLICT        TBS_ERR_CVT(ERR_WAN_BEGIN_ADDR + 15, TR069_ERRNO_INVALID_VAL)
#define ERR_WAN_TOO_MANY_IP_PPP_INST     TBS_ERR_CVT(ERR_WAN_BEGIN_ADDR + 16, TR069_ERRNO_INVALID_VAL)
#define ERR_WAN_NOREOA_LINK_EXIST        TBS_ERR_CVT(ERR_WAN_BEGIN_ADDR + 17, TR069_ERRNO_INVALID_VAL)
#define ERR_WAN_EOA_LINK_EXIST           TBS_ERR_CVT(ERR_WAN_BEGIN_ADDR + 18, TR069_ERRNO_INVALID_VAL)
#define ERR_WAN_TOO_MANY_PVC             TBS_ERR_CVT(ERR_WAN_BEGIN_ADDR + 19, TR069_ERRNO_INVALID_VAL)
#define ERR_WAN_CANNOT_CHNG_LINK_TYPE    TBS_ERR_CVT(ERR_WAN_BEGIN_ADDR + 20, TR069_ERRNO_INVALID_VAL)
#define ERR_WAN_TOO_MANY_ENABLED_DSL_PPP  TBS_ERR_CVT(ERR_WAN_BEGIN_ADDR + 21, TR069_ERRNO_INVALID_VAL)
#define ERR_WAN_TOO_MANY_ENABLED_ETH_PPP  TBS_ERR_CVT(ERR_WAN_BEGIN_ADDR + 22, TR069_ERRNO_INVALID_VAL)
#define ERR_DSL_TOO_MANY_IP_INST         TBS_ERR_CVT(ERR_WAN_BEGIN_ADDR + 23, TR069_ERRNO_INVALID_VAL)
#define ERR_ETH_TOO_MANY_IP_INST         TBS_ERR_CVT(ERR_WAN_BEGIN_ADDR + 24, TR069_ERRNO_INVALID_VAL)
#define ERR_WAN_TOO_MANY_ENABLED_BR      TBS_ERR_CVT(ERR_WAN_BEGIN_ADDR + 25, TR069_ERRNO_INVALID_VAL)

#define ERR_WAN_CONN_COUNT_FULL          TBS_ERR_CVT(ERR_WAN_BEGIN_ADDR + 26, TR069_ERRNO_INVALID_VAL)
#define ERR_WAN_ATM_UNKNOWN_LINK_TYPE    TBS_ERR_CVT(ERR_ATM_BEGIN_ADDR + 29, TR069_ERRNO_INVALID_VAL)
#define ERR_WAN_VLAN_CONFLICT            TBS_ERR_CVT(ERR_ATM_BEGIN_ADDR + 30, TR069_ERRNO_INVALID_VAL)
#define ERR_WAN_SVC_ONE_MORE_TR069       TBS_ERR_CVT(ERR_WAN_BEGIN_ADDR + 31, TR069_ERRNO_INVALID_VAL)
#define ERR_WAN_UNKNOWN_DSL_TYPE         TBS_ERR_CVT(ERR_WAN_BEGIN_ADDR + 32, TR069_ERRNO_INVALID_VAL)
#define ERR_WAN_REPEAT_VLANID         TBS_ERR_CVT(ERR_WAN_BEGIN_ADDR + 33, TR069_ERRNO_INVALID_VAL)



/* DNS */
#define ERR_DNS_BEGIN_ADDR      TBS_ERR_LOGIC_BASE_ADDR(MID_DNS)
#define ERR_DNS_VALID_DNS_ADDR  TBS_ERR_CVT(ERR_DNS_BEGIN_ADDR + 1, TR069_ERRNO_INVALID_VAL)
#define ERR_DNS_HAS_REPEAT      TBS_ERR_CVT(ERR_DNS_BEGIN_ADDR + 2, TR069_ERRNO_INVALID_VAL)
#define ERR_DNS_CUSTOM_BE_EMPTY TBS_ERR_CVT(ERR_DNS_BEGIN_ADDR + 3, TR069_ERRNO_INVALID_VAL)



/* ETHLAN */
#define ERR_ETHLAN_BEGIN_ADDR   TBS_ERR_LOGIC_BASE_ADDR(MID_ETHLAN)

/* LSVLAN */
#define ERR_LSVLAN_BEGIN_ADDR           TBS_ERR_LOGIC_BASE_ADDR(MID_LSVLAN)
#define ERR_LSVLAN_INVALID_BRIDGENAME   TBS_ERR_CVT(ERR_LSVLAN_BEGIN_ADDR + 1, TR069_ERRNO_INVALID_VAL)
#define ERR_LSVLAN_INVALID_VLANID       TBS_ERR_CVT(ERR_LSVLAN_BEGIN_ADDR + 2, TR069_ERRNO_INVALID_VAL)
#define ERR_LSVLAN_INVALID_FILTERBRREF  TBS_ERR_CVT(ERR_LSVLAN_BEGIN_ADDR + 3, TR069_ERRNO_INVALID_VAL)
#define ERR_LSVLAN_INVALID_FILTERIF     TBS_ERR_CVT(ERR_LSVLAN_BEGIN_ADDR + 4, TR069_ERRNO_INVALID_VAL)
#define ERR_LSVLAN_DEL_FIRST_BRIDGE     TBS_ERR_CVT(ERR_LSVLAN_BEGIN_ADDR + 6, TR069_ERRNO_INVALID_VAL)
#define ERR_LSVLAN_INSTANCE_IN_USE      TBS_ERR_CVT(ERR_LSVLAN_BEGIN_ADDR + 7, TR069_ERRNO_INVALID_VAL)
#define ERR_LSVLAN_BRNAME_CONFLICT      TBS_ERR_CVT(ERR_LSVLAN_BEGIN_ADDR + 8, TR069_ERRNO_INVALID_VAL)
#define ERR_LSVLAN_BRVLAN_CONFLICT      TBS_ERR_CVT(ERR_LSVLAN_BEGIN_ADDR + 9, TR069_ERRNO_INVALID_VAL)
#define ERR_LSVLAN_IF_CONFLICT          TBS_ERR_CVT(ERR_LSVLAN_BEGIN_ADDR + 10, TR069_ERRNO_INVALID_VAL)
#define ERR_LSVLAN_WLAN_IF_TAGGED       TBS_ERR_CVT(ERR_LSVLAN_BEGIN_ADDR  + 11, TR069_ERRNO_INVALID_VAL)
#define ERR_LSVLAN_BEGIN_NAME_NON       TBS_ERR_CVT(ERR_LSVLAN_BEGIN_ADDR  + 12, TR069_ERRNO_INVALID_VAL)

/*LPVLAN*/
/*由于errcode长度不能超过4位,因此目前MID号超过0x55的，
在定义错误码的时候需要想办法插在前面去，而不能完全依靠模块号来定义*/
#define ERR_LPVLAN_BEGIN_ADDR           (TBS_ERR_LOGIC_BASE_ADDR(MID_LSVLAN)+30)//此处借用LSVLAN的错误号资源
#define ERR_LPVLAN_INVALID_VLAN_ID      TBS_ERR_CVT(ERR_LPVLAN_BEGIN_ADDR + 1, TR069_ERRNO_INVALID_VAL)
#define ERR_LPVLAN_INVALID_VLAN_ID_LIST TBS_ERR_CVT(ERR_LPVLAN_BEGIN_ADDR + 2, TR069_ERRNO_INVALID_VAL)
#define ERR_LPVLAN_TOO_MANY_VLAN        TBS_ERR_CVT(ERR_LPVLAN_BEGIN_ADDR + 3, TR069_ERRNO_INVALID_VAL)


#define ERR_VLAN_BEGIN_ADDR                     TBS_ERR_LOGIC_BASE_ADDR(MID_VLAN)
#define ERR_VLAN_BRIDGENAME_HAS_ILLEGAL_W       TBS_ERR_CVT(ERR_VLAN_BEGIN_ADDR + 1, TR069_ERRNO_INVALID_VAL)
#define ERR_VLAN_BRIDGENAME_TOO_LONG            TBS_ERR_CVT(ERR_VLAN_BEGIN_ADDR + 2, TR069_ERRNO_INVALID_VAL)
#define ERR_VLAN_INVALID_VLANID                 TBS_ERR_CVT(ERR_VLAN_BEGIN_ADDR + 3, TR069_ERRNO_INVALID_VAL)
#define ERR_VLAN_INVALID_FILTERBRREF            TBS_ERR_CVT(ERR_VLAN_BEGIN_ADDR + 4, TR069_ERRNO_INVALID_VAL)
#define ERR_VLAN_INVALID_FILTERIF               TBS_ERR_CVT(ERR_VLAN_BEGIN_ADDR + 5, TR069_ERRNO_INVALID_VAL)
#define ERR_VLAN_DEL_FIRST_BRIDGE               TBS_ERR_CVT(ERR_VLAN_BEGIN_ADDR + 6, TR069_ERRNO_INVALID_VAL)
#define ERR_VLAN_INSTANCE_IN_USE                TBS_ERR_CVT(ERR_VLAN_BEGIN_ADDR + 7, TR069_ERRNO_INVALID_VAL)
#define ERR_VLAN_BRNAME_CONFLICT                TBS_ERR_CVT(ERR_VLAN_BEGIN_ADDR + 8, TR069_ERRNO_INVALID_VAL)
#define ERR_VLAN_BRVLAN_CONFLICT                TBS_ERR_CVT(ERR_VLAN_BEGIN_ADDR + 9, TR069_ERRNO_INVALID_VAL)
#define ERR_VLAN_IF_CONFLICT                    TBS_ERR_CVT(ERR_VLAN_BEGIN_ADDR + 10, TR069_ERRNO_INVALID_VAL)
#define ERR_VLAN_WLAN_IF_TAGGED                 TBS_ERR_CVT(ERR_VLAN_BEGIN_ADDR  + 11, TR069_ERRNO_INVALID_VAL)
#define ERR_VLAN_INVALID_VLANID_FILTER          TBS_ERR_CVT(ERR_VLAN_BEGIN_ADDR + 12, TR069_ERRNO_INVALID_VAL)
#define ERR_VLAN_INVALID_ETH_TYPE_FILTER_LIST   TBS_ERR_CVT(ERR_VLAN_BEGIN_ADDR + 13, TR069_ERRNO_INVALID_VAL)
#define ERR_VLAN_INVALID_SRC_MAC_FILTER_LIST    TBS_ERR_CVT(ERR_VLAN_BEGIN_ADDR + 14, TR069_ERRNO_INVALID_VAL)
#define ERR_VLAN_INVALID_MARKING_IF             TBS_ERR_CVT(ERR_VLAN_BEGIN_ADDR + 15, TR069_ERRNO_INVALID_VAL)
#define ERR_VLAN_INVALID_DST_MAC_FILTER_LIST    TBS_ERR_CVT(ERR_VLAN_BEGIN_ADDR + 16, TR069_ERRNO_INVALID_VAL)
#define ERR_VLAN_INVALID_MARKING_VLANID_MARK    TBS_ERR_CVT(ERR_VLAN_BEGIN_ADDR + 17, TR069_ERRNO_INVALID_VAL)
#define ERR_VLAN_INVALID_MARKING_BR_REF         TBS_ERR_CVT(ERR_VLAN_BEGIN_ADDR + 18, TR069_ERRNO_INVALID_VAL)
#define ERR_VLAN_INVALID_INPUT_POINTER          TBS_ERR_CVT(ERR_VLAN_BEGIN_ADDR + 19, TR069_ERRNO_INVALID_VAL)
#define ERR_VLAN_BR_NOT_EXIST                   TBS_ERR_CVT(ERR_VLAN_BEGIN_ADDR + 20, TR069_ERRNO_INVALID_VAL)
#define ERR_VLAN_BR_INVALID_EXCLUSIVITY_ORDER   TBS_ERR_CVT(ERR_VLAN_BEGIN_ADDR + 21, TR069_ERRNO_INVALID_VAL)
#define ERR_VLAN_BR_RANGE_EXCLUSIVITY_ORDER     TBS_ERR_CVT(ERR_VLAN_BEGIN_ADDR + 22, TR069_ERRNO_INVALID_VAL)

/* IPCONN */
#define ERR_IPCONN_BEGIN_ADDR             TBS_ERR_LOGIC_BASE_ADDR(MID_IPCONN)
#define ERR_IPCONN_NAME_TOO_LONG          TBS_ERR_CVT(ERR_IPCONN_BEGIN_ADDR + 1, TR069_ERRNO_INVALID_VAL)
#define ERR_IPCONN_NAME_INVALID           TBS_ERR_CVT(ERR_IPCONN_BEGIN_ADDR + 2, TR069_ERRNO_INVALID_VAL)
#define ERR_IPCONN_ADDR_TYPE_INVALID      TBS_ERR_CVT(ERR_IPCONN_BEGIN_ADDR + 3, TR069_ERRNO_INVALID_VAL)
#define ERR_IPCONN_ACTIVE_CONN_OVER       TBS_ERR_CVT(ERR_IPCONN_BEGIN_ADDR + 4, TR069_ERRNO_INVALID_VAL)
#define ERR_IPCONN_WAN_CONN_OVER          TBS_ERR_CVT(ERR_IPCONN_BEGIN_ADDR + 5, TR069_ERRNO_INVALID_VAL)
#define ERR_IPCONN_WAN_IPCONN_OVER        TBS_ERR_CVT(ERR_IPCONN_BEGIN_ADDR + 6, TR069_ERRNO_INVALID_VAL)
#define ERR_IPCONN_IP_GATEWAY_SAME        TBS_ERR_CVT(ERR_IPCONN_BEGIN_ADDR + 7, TR069_ERRNO_INVALID_VAL)
#define ERR_IPCONN_NAME_EXISTS            TBS_ERR_CVT(ERR_IPCONN_BEGIN_ADDR + 8, TR069_ERRNO_INVALID_VAL)
#define ERR_IPCONN_PPPOA_ADD_IP_INST      TBS_ERR_CVT(ERR_IPCONN_BEGIN_ADDR + 9, TR069_ERRNO_INVALID_VAL)
#define ERR_IPCONN_CONNTYPE_INVALID       TBS_ERR_CVT(ERR_IPCONN_BEGIN_ADDR + 10, TR069_ERRNO_INVALID_VAL)
#define ERR_IPCONN_IP_GATEWAY_NOT_MATCH   TBS_ERR_CVT(ERR_IPCONN_BEGIN_ADDR + 11, TR069_ERRNO_INVALID_VAL)
#define ERR_IPCONN_CONNTYPE_CONFLICT      TBS_ERR_CVT(ERR_IPCONN_BEGIN_ADDR + 12, TR069_ERRNO_INVALID_VAL)
#define ERR_IPCONN_TOO_MANY_IPOA_INST     TBS_ERR_CVT(ERR_IPCONN_BEGIN_ADDR + 15, TR069_ERRNO_INVALID_VAL)
#define ERR_IPCONN_TOO_MANY_IPOE_INST     TBS_ERR_CVT(ERR_IPCONN_BEGIN_ADDR + 16, TR069_ERRNO_INVALID_VAL)
#define ERR_IPCONN_MTU_INVALID            TBS_ERR_CVT(ERR_IPCONN_BEGIN_ADDR + 17, TR069_ERRNO_INVALID_VAL)
#define ERR_IPCONN_GATEWAY_MASK_NOT_MATCH TBS_ERR_CVT(ERR_IPCONN_BEGIN_ADDR + 18, TR069_ERRNO_INVALID_VAL)

/* DHCPS */
#define ERR_DHCPS_BEGIN_ADDR    TBS_ERR_LOGIC_BASE_ADDR(MID_DHCPS)
#define ERR_DHCPS_INVALID_CLASS_ID    TBS_ERR_CVT(ERR_DHCPS_BEGIN_ADDR + 1, TR069_ERRNO_INVALID_VAL)
#define ERR_DHCPS_EXIST_CLASS_ID    TBS_ERR_CVT(ERR_DHCPS_BEGIN_ADDR + 2, TR069_ERRNO_INVALID_VAL)
#define ERR_DHCPS_IFIP_ADDRPOOL_UNMATCH TBS_ERR_CVT(ERR_DHCPS_BEGIN_ADDR + 3, TR069_ERRNO_INVALID_VAL)
#define ERR_DHCPS_LEASE_TIME_OUT_RANGE TBS_ERR_CVT(ERR_DHCPS_BEGIN_ADDR + 4, TR069_ERRNO_INVALID_VAL)
#define ERR_DHCPS_MACIP_OVERLAP  TBS_ERR_CVT(ERR_DHCPS_BEGIN_ADDR + 5, TR069_ERRNO_INVALID_VAL)
#define ERR_DHCPS_MACIP_OUTSIDE_POOL  TBS_ERR_CVT(ERR_DHCPS_BEGIN_ADDR + 6, TR069_ERRNO_INVALID_VAL)
#define ERR_DHCPS_MACIP_IS_LANIP  TBS_ERR_CVT(ERR_DHCPS_BEGIN_ADDR + 7, TR069_ERRNO_INVALID_VAL)
#define ERR_DHCPS_MAC_INVALID  TBS_ERR_CVT(ERR_DHCPS_BEGIN_ADDR + 8, TR069_ERRNO_INVALID_VAL)
#define ERR_DHCPS_IP_IN_PPPOEPROXY TBS_ERR_CVT(ERR_DHCPS_BEGIN_ADDR + 9, TR069_ERRNO_INVALID_VAL)
#define ERR_DHCPS_CPEIP_CONFLICT_DHCP_POLL_IPADDR TBS_ERR_CVT(ERR_DHCPS_BEGIN_ADDR + 10, TR069_ERRNO_INVALID_VAL)

/* pppoe */
#define ERR_PPPOE_BEGIN_ADDR     TBS_ERR_LOGIC_BASE_ADDR(MID_PPPOE)

#define ERR_PPPOE_NO_RESOURSE   TBS_ERR_CVT(ERR_PPPOE_BEGIN_ADDR + 1, TR069_ERRNO_NO_RESOURCE)
#define ERR_PPPOE_INVALID_VAL		TBS_ERR_CVT(ERR_PPPOE_BEGIN_ADDR + 2, TR069_ERRNO_INVALID_VAL)
#define ERR_PPPOE_INVALID_PATH	TBS_ERR_CVT(ERR_PPPOE_BEGIN_ADDR + 3, TR069_ERRNO_INVALID_PARAM)
#define ERR_PPPOE_EXCEED_CONNECTION_NUM    TBS_ERR_CVT(ERR_PPPOE_BEGIN_ADDR + 4, TR069_ERRNO_NO_RESOURCE)
#define ERR_PPPOE_INVALID_INSTANCE	TBS_ERR_CVT(ERR_PPPOE_BEGIN_ADDR + 5, TR069_ERRNO_CPE_ERR)
#define ERR_PPPOE_ENABLE_INVALID	TBS_ERR_CVT(ERR_PPPOE_BEGIN_ADDR + 6, TR069_ERRNO_INVALID_VAL)
#define ERR_PPPOE_USERNAME_INVALID	TBS_ERR_CVT(ERR_PPPOE_BEGIN_ADDR + 7, TR069_ERRNO_INVALID_VAL)
#define ERR_PPPOE_USERNAME_OVERLENTH	TBS_ERR_CVT(ERR_PPPOE_BEGIN_ADDR + 8, TR069_ERRNO_INVALID_VAL)
#define ERR_PPPOE_USERNAME_EMPTY	 TBS_ERR_CVT(ERR_PPPOE_BEGIN_ADDR + 9, TR069_ERRNO_INVALID_VAL)
#define ERR_PPPOE_PASSWD_INVALID		TBS_ERR_CVT(ERR_PPPOE_BEGIN_ADDR + 10, TR069_ERRNO_INVALID_VAL)
#define ERR_PPPOE_PASSWD_OVERLENTH	TBS_ERR_CVT(ERR_PPPOE_BEGIN_ADDR + 11, TR069_ERRNO_INVALID_VAL)
#define ERR_PPPOE_PASSWD_EMPTY		TBS_ERR_CVT(ERR_PPPOE_BEGIN_ADDR + 12, TR069_ERRNO_INVALID_VAL)
#define ERR_PPPOE_CONNETNAME_INVALID		TBS_ERR_CVT(ERR_PPPOE_BEGIN_ADDR + 13, TR069_ERRNO_INVALID_VAL)
#define ERR_PPPOE_CONNETNAME_OVERLENTH	TBS_ERR_CVT(ERR_PPPOE_BEGIN_ADDR + 14, TR069_ERRNO_INVALID_VAL)
#define ERR_PPPOE_AUTH_INVALID	TBS_ERR_CVT(ERR_PPPOE_BEGIN_ADDR + 15, TR069_ERRNO_INVALID_VAL)
#define ERR_PPPOE_MRU_INVALID		TBS_ERR_CVT(ERR_PPPOE_BEGIN_ADDR + 16, TR069_ERRNO_INVALID_VAL)
#define ERR_PPPOE_TRIGGER_INVALID		TBS_ERR_CVT(ERR_PPPOE_BEGIN_ADDR + 17, TR069_ERRNO_INVALID_VAL)
#define ERR_PPPOE_CONNACTION_INVALID		TBS_ERR_CVT(ERR_PPPOE_BEGIN_ADDR + 18, TR069_ERRNO_INVALID_VAL)
#define ERR_PPPOE_LCPECHO_INVALID		TBS_ERR_CVT(ERR_PPPOE_BEGIN_ADDR + 19, TR069_ERRNO_INVALID_VAL)
#define ERR_PPPOE_ACTIVE_CONN_OVER	TBS_ERR_CVT(ERR_PPPOE_BEGIN_ADDR + 20, TR069_ERRNO_INVALID_VAL)
#define ERR_PPPOE_INVALID_INNER_MSG	TBS_ERR_CVT(ERR_PPPOE_BEGIN_ADDR + 21, TR069_ERRNO_CPE_ERR)
#define ERR_PPPOE_INVALID_MATCH_INDEX 	TBS_ERR_CVT(ERR_PPPOE_BEGIN_ADDR + 22, TR069_ERRNO_CPE_ERR)
#define ERR_PPPOE_NO_PPPSESSION     TBS_ERR_CVT(ERR_PPPOE_BEGIN_ADDR + 23, TR069_ERRNO_REJECT)
#define ERR_PPPOE_NO_PPPSESSION_IDX     TBS_ERR_CVT(ERR_PPPOE_BEGIN_ADDR + 24, TR069_ERRNO_INVALID_VAL)
#define ERR_PPPOE_ERROR_PPPSESSION_VAL  TBS_ERR_CVT(ERR_PPPOE_BEGIN_ADDR + 25, TR069_ERRNO_INVALID_VAL)
#define ERR_PPPOE_NAME_REPEATED        TBS_ERR_CVT(ERR_PPPOE_BEGIN_ADDR + 26, TR069_ERRNO_NO_RESOURCE)
#define ERR_PPPOE_PROXY_CONFLICT        TBS_ERR_CVT(ERR_PPPOE_BEGIN_ADDR + 27, TR069_ERRNO_INVALID_VAL)
#define ERR_PPPOE_PROXY_USER_OVER        TBS_ERR_CVT(ERR_PPPOE_BEGIN_ADDR + 28, TR069_ERRNO_INVALID_VAL)
#define ERR_PPPOE_IDLE_INVALID        TBS_ERR_CVT(ERR_PPPOE_BEGIN_ADDR + 29, TR069_ERRNO_INVALID_VAL)
#define ERR_PPPOE_IPOA_ADD_PPP_INST    TBS_ERR_CVT(ERR_PPPOE_BEGIN_ADDR + 30, TR069_ERRNO_INVALID_VAL)
#define ERR_PPPOE_PROXY_LANINTF        TBS_ERR_CVT(ERR_PPPOE_BEGIN_ADDR + 31, TR069_ERRNO_INVALID_VAL)
#define ERR_PPPOE_IDLEDISCONNTIME_INVALID        TBS_ERR_CVT(ERR_PPPOE_BEGIN_ADDR + 32, TR069_ERRNO_NO_RESOURCE)
#define ERR_PPPOE_MTU_INVALID               TBS_ERR_CVT(ERR_PPPOE_BEGIN_ADDR + 33, TR069_ERRNO_INVALID_VAL)
#define ERR_PPPOE_ACNAME_INVALID            TBS_ERR_CVT(ERR_PPPOE_BEGIN_ADDR + 34, TR069_ERRNO_INVALID_VAL)
#define ERR_PPPOE_SERVICENAME_INVALID       TBS_ERR_CVT(ERR_PPPOE_BEGIN_ADDR + 35, TR069_ERRNO_INVALID_VAL)
#define ERR_PPPOE_CONNTYPE_ERROR			TBS_ERR_CVT(ERR_PPPOE_BEGIN_ADDR + 36,TR069_ERRNO_INVALID_VAL)
#define ERR_PPPOE_TOO_MANY_PPPOA_INST  TBS_ERR_CVT(ERR_PPPOE_BEGIN_ADDR + 37, TR069_ERRNO_INVALID_VAL)
#define ERR_PPPOE_TOO_MANY_PPPOE_INST  TBS_ERR_CVT(ERR_PPPOE_BEGIN_ADDR + 38, TR069_ERRNO_INVALID_VAL)
#define ERR_PPPOE_APN_INVALID               TBS_ERR_CVT(ERR_PPPOE_BEGIN_ADDR + 39, TR069_ERRNO_INVALID_VAL)
#define ERR_PPPOE_APN_EMPTY                 TBS_ERR_CVT(ERR_PPPOE_BEGIN_ADDR + 40, TR069_ERRNO_INVALID_VAL)
#define ERR_PPPOE_APN_OVERLENTH             TBS_ERR_CVT(ERR_PPPOE_BEGIN_ADDR + 41, TR069_ERRNO_INVALID_VAL)
#define ERR_PPPOE_DIALNUMBER_INVALID        TBS_ERR_CVT(ERR_PPPOE_BEGIN_ADDR + 42, TR069_ERRNO_INVALID_VAL)
#define ERR_PPPOE_DIALNUMBER_EMPTY          TBS_ERR_CVT(ERR_PPPOE_BEGIN_ADDR + 43, TR069_ERRNO_INVALID_VAL)
#define ERR_PPPOE_DIALNUMBER_OVERLENTH      TBS_ERR_CVT(ERR_PPPOE_BEGIN_ADDR + 44, TR069_ERRNO_INVALID_VAL)
#define ERR_PPPOE_TOO_MANY_PPPOU_INST       TBS_ERR_CVT(ERR_PPPOE_BEGIN_ADDR + 45, TR069_ERRNO_INVALID_VAL)
#define ERR_PPPOE_LCPECHO_RETRY_INVALID		TBS_ERR_CVT(ERR_PPPOE_BEGIN_ADDR + 46, TR069_ERRNO_INVALID_VAL)
#define ERR_PPPOE_IDLEDELAYTIME_INVALID  	TBS_ERR_CVT(ERR_PPPOE_BEGIN_ADDR + 47, TR069_ERRNO_INVALID_VAL)
#define ERR_PPPOE_IDLEDELAYTIME_EMPTY  		TBS_ERR_CVT(ERR_PPPOE_BEGIN_ADDR + 48, TR069_ERRNO_INVALID_VAL)
#define ERR_PPPOE_IDLEDELAYTIME_DIVIDE  	TBS_ERR_CVT(ERR_PPPOE_BEGIN_ADDR + 49, TR069_ERRNO_INVALID_VAL)
#define ERR_PPPOE_IP6_MTU_INVALID               TBS_ERR_CVT(ERR_PPPOE_BEGIN_ADDR + 50, TR069_ERRNO_INVALID_VAL)
#define ERR_PPPOE_IP6_MRU_INVALID               TBS_ERR_CVT(ERR_PPPOE_BEGIN_ADDR + 51, TR069_ERRNO_INVALID_VAL)


/*QOS*/
#define ERR_QOS_BEGIN_ADDR    TBS_ERR_LOGIC_BASE_ADDR(MID_QOS)
#ifdef CONFIG_APPS_LOGIC_QOS_IMQ
#define ERR_QOS_INVALID_IF_PATH              TBS_ERR_CVT(ERR_QOS_BEGIN_ADDR + 1, TR069_ERRNO_INVALID_VAL)
#define ERR_QOS_INVALID_COMMITTED_RATE       TBS_ERR_CVT(ERR_QOS_BEGIN_ADDR + 2, TR069_ERRNO_INVALID_VAL)
#define ERR_QOS_INVALID_PEAK_RATE            TBS_ERR_CVT(ERR_QOS_BEGIN_ADDR + 3, TR069_ERRNO_INVALID_VAL)
#define ERR_QOS_INVALID_BURST_SIZE           TBS_ERR_CVT(ERR_QOS_BEGIN_ADDR + 4, TR069_ERRNO_INVALID_VAL)
#define ERR_QOS_INVALID_QUE_SCHED_TYPE       TBS_ERR_CVT(ERR_QOS_BEGIN_ADDR + 5, TR069_ERRNO_INVALID_VAL)
#define ERR_QOS_INVALID_QUE_IF               TBS_ERR_CVT(ERR_QOS_BEGIN_ADDR + 6, TR069_ERRNO_INVALID_VAL)
#define ERR_QOS_QUE_IF_NOT_EXIST             TBS_ERR_CVT(ERR_QOS_BEGIN_ADDR + 7, TR069_ERRNO_INVALID_VAL)
#define ERR_QOS_INVALID_QUE_LEN              TBS_ERR_CVT(ERR_QOS_BEGIN_ADDR + 8, TR069_ERRNO_INVALID_VAL)
#define ERR_QOS_INVALID_QUE_LEN_TYPE         TBS_ERR_CVT(ERR_QOS_BEGIN_ADDR + 9, TR069_ERRNO_INVALID_VAL)
#define ERR_QOS_INVALID_QUE_WEIGHT           TBS_ERR_CVT(ERR_QOS_BEGIN_ADDR + 10, TR069_ERRNO_INVALID_VAL)
#define ERR_QOS_INVALID_QUE_PRIO             TBS_ERR_CVT(ERR_QOS_BEGIN_ADDR + 11, TR069_ERRNO_INVALID_VAL)
#define ERR_QOS_INVALID_QUE_CAR              TBS_ERR_CVT(ERR_QOS_BEGIN_ADDR + 12, TR069_ERRNO_INVALID_VAL)
#define ERR_QOS_INVALID_DROP_ALGORITHM       TBS_ERR_CVT(ERR_QOS_BEGIN_ADDR + 13, TR069_ERRNO_INVALID_VAL)
#define ERR_QOS_INVALID_CLS_DIRECTION        TBS_ERR_CVT(ERR_QOS_BEGIN_ADDR + 14, TR069_ERRNO_INVALID_VAL)
#define ERR_QOS_INVALID_CLASS_IF             TBS_ERR_CVT(ERR_QOS_BEGIN_ADDR + 15, TR069_ERRNO_INVALID_VAL)
#define ERR_QOS_INVALID_CLS_EGRESS_IF        TBS_ERR_CVT(ERR_QOS_BEGIN_ADDR + 16, TR069_ERRNO_INVALID_VAL)
#define ERR_QOS_INVALID_ETH_TYPE             TBS_ERR_CVT(ERR_QOS_BEGIN_ADDR + 17, TR069_ERRNO_INVALID_VAL)
#define ERR_QOS_INVALID_ETH_PRIO             TBS_ERR_CVT(ERR_QOS_BEGIN_ADDR + 18, TR069_ERRNO_INVALID_VAL)
#define ERR_QOS_INVALID_VLAN_ID              TBS_ERR_CVT(ERR_QOS_BEGIN_ADDR + 19, TR069_ERRNO_INVALID_VAL)
#define ERR_QOS_INVALID_IP_LEN               TBS_ERR_CVT(ERR_QOS_BEGIN_ADDR + 20, TR069_ERRNO_INVALID_VAL)
#define ERR_QOS_INVALID_DSCP                 TBS_ERR_CVT(ERR_QOS_BEGIN_ADDR + 21, TR069_ERRNO_INVALID_VAL)
#define ERR_QOS_INVALID_TOS                  TBS_ERR_CVT(ERR_QOS_BEGIN_ADDR + 22, TR069_ERRNO_INVALID_VAL)
#define ERR_QOS_INVALID_PROTOCOL             TBS_ERR_CVT(ERR_QOS_BEGIN_ADDR + 23, TR069_ERRNO_INVALID_VAL)
#define ERR_QOS_INVALID_PORT                 ERR_PORT_TOO_BIG
#define ERR_QOS_INVALID_CLASS_QUE            TBS_ERR_CVT(ERR_QOS_BEGIN_ADDR + 24, TR069_ERRNO_INVALID_VAL)
#define ERR_QOS_QUEUE_NOT_EXIST              TBS_ERR_CVT(ERR_QOS_BEGIN_ADDR + 25, TR069_ERRNO_INVALID_VAL)
#define ERR_QOS_INVALID_APP_NAME             TBS_ERR_CVT(ERR_QOS_BEGIN_ADDR + 26, TR069_ERRNO_INVALID_VAL)
#define ERR_QOS_INVALID_APP_QUEUE            TBS_ERR_CVT(ERR_QOS_BEGIN_ADDR + 27, TR069_ERRNO_INVALID_VAL)
#define ERR_QOS_SHAPE_RATE_CONFLICT          TBS_ERR_CVT(ERR_QOS_BEGIN_ADDR + 28, TR069_ERRNO_INVALID_VAL)
#define ERR_QOS_QUEUE_LEN_CONFLICT           TBS_ERR_CVT(ERR_QOS_BEGIN_ADDR + 29, TR069_ERRNO_INVALID_VAL)
#define ERR_QOS_QUEUE_WEIGHT_CONFLICT        TBS_ERR_CVT(ERR_QOS_BEGIN_ADDR + 30, TR069_ERRNO_INVALID_VAL)
#define ERR_QOS_QUEUE_PRIO_CONFLICT          TBS_ERR_CVT(ERR_QOS_BEGIN_ADDR + 31, TR069_ERRNO_INVALID_VAL)
#define ERR_QOS_IP_LENGTH_CONFLICT           TBS_ERR_CVT(ERR_QOS_BEGIN_ADDR + 32, TR069_ERRNO_INVALID_VAL)
#define ERR_QOS_PORT_CONFLICT                TBS_ERR_CVT(ERR_QOS_BEGIN_ADDR + 33, TR069_ERRNO_INVALID_VAL)
#define ERR_QOS_APP_NAME_CONFLICT            TBS_ERR_CVT(ERR_QOS_BEGIN_ADDR + 34, TR069_ERRNO_INVALID_VAL)
#define ERR_QOS_QUEUE_CAR_CONFLICT           TBS_ERR_CVT(ERR_QOS_BEGIN_ADDR + 35, TR069_ERRNO_INVALID_VAL)
#define ERR_QOS_INVALID_IP_ADDR              TBS_ERR_CVT(ERR_QOS_BEGIN_ADDR + 36, TR069_ERRNO_INVALID_VAL)
#define ERR_QOS_INVALID_PREFIX_LEN           TBS_ERR_CVT(ERR_QOS_BEGIN_ADDR + 37, TR069_ERRNO_INVALID_VAL)
#define ERR_QOS_INVALID_IP_PROTO_TYPE        TBS_ERR_CVT(ERR_QOS_BEGIN_ADDR + 38, TR069_ERRNO_INVALID_VAL)
#define ERR_QOS_SRCIP_CONFLICT               TBS_ERR_CVT(ERR_QOS_BEGIN_ADDR + 39, TR069_ERRNO_INVALID_VAL)
#define ERR_QOS_DSTIP_CONFLICT               TBS_ERR_CVT(ERR_QOS_BEGIN_ADDR + 40, TR069_ERRNO_INVALID_VAL)
#define ERR_QOS_INVALID_FLOW_LABEL           TBS_ERR_CVT(ERR_QOS_BEGIN_ADDR + 41, TR069_ERRNO_INVALID_VAL)
#define ERR_QOS_INVALID_TRAFFIC_CLASS        TBS_ERR_CVT(ERR_QOS_BEGIN_ADDR + 42, TR069_ERRNO_INVALID_VAL)
#else
#define ERR_QOS_INVALID_IF_PATH              TBS_ERR_CVT(ERR_QOS_BEGIN_ADDR + 1, TR069_ERRNO_INVALID_VAL)
#define ERR_QOS_INVALID_UP_SHAPE_RATE        TBS_ERR_CVT(ERR_QOS_BEGIN_ADDR + 2, TR069_ERRNO_INVALID_VAL)
#define ERR_QOS_INVALID_DOWN_SHAPE_RATE      TBS_ERR_CVT(ERR_QOS_BEGIN_ADDR + 3, TR069_ERRNO_INVALID_VAL)
#define ERR_QOS_INVALID_QUE_PRIO             TBS_ERR_CVT(ERR_QOS_BEGIN_ADDR + 4, TR069_ERRNO_INVALID_VAL)
#define ERR_QOS_INVALID_QUE_SCH_ALGORITHM    TBS_ERR_CVT(ERR_QOS_BEGIN_ADDR + 5, TR069_ERRNO_INVALID_VAL)
#define ERR_QOS_INVALID_QUE_IF               TBS_ERR_CVT(ERR_QOS_BEGIN_ADDR + 6, TR069_ERRNO_INVALID_VAL)
#define ERR_QOS_QUE_IF_NOT_EXIST             TBS_ERR_CVT(ERR_QOS_BEGIN_ADDR + 7, TR069_ERRNO_INVALID_VAL)
#define ERR_QOS_INVALID_QUE_LEN              TBS_ERR_CVT(ERR_QOS_BEGIN_ADDR + 8, TR069_ERRNO_INVALID_VAL)
#define ERR_QOS_INVALID_QUE_LEN_TYPE         TBS_ERR_CVT(ERR_QOS_BEGIN_ADDR + 9, TR069_ERRNO_INVALID_VAL)
#define ERR_QOS_INVALID_QUE_WEIGHT           TBS_ERR_CVT(ERR_QOS_BEGIN_ADDR + 10, TR069_ERRNO_INVALID_VAL)
#define ERR_QOS_INVALID_DROP_ALGORITHM       TBS_ERR_CVT(ERR_QOS_BEGIN_ADDR + 11, TR069_ERRNO_INVALID_VAL)
#define ERR_QOS_INVALID_CLASS_TYPE           TBS_ERR_CVT(ERR_QOS_BEGIN_ADDR + 12, TR069_ERRNO_INVALID_VAL)
#define ERR_QOS_INVALID_CLASS_IF             TBS_ERR_CVT(ERR_QOS_BEGIN_ADDR + 13, TR069_ERRNO_INVALID_VAL)
#define ERR_QOS_INVALID_ETH_TYPE             TBS_ERR_CVT(ERR_QOS_BEGIN_ADDR + 14, TR069_ERRNO_INVALID_VAL)
#define ERR_QOS_INVALID_ETH_PRIO             TBS_ERR_CVT(ERR_QOS_BEGIN_ADDR + 15, TR069_ERRNO_INVALID_VAL)
#define ERR_QOS_INVALID_VLAN_ID              TBS_ERR_CVT(ERR_QOS_BEGIN_ADDR + 16, TR069_ERRNO_INVALID_VAL)
#define ERR_QOS_INVALID_IP_LEN               TBS_ERR_CVT(ERR_QOS_BEGIN_ADDR + 17, TR069_ERRNO_INVALID_VAL)
#define ERR_QOS_INVALID_DSCP                 TBS_ERR_CVT(ERR_QOS_BEGIN_ADDR + 18, TR069_ERRNO_INVALID_VAL)
#define ERR_QOS_INVALID_PROTOCOL             TBS_ERR_CVT(ERR_QOS_BEGIN_ADDR + 19, TR069_ERRNO_INVALID_VAL)
#define ERR_QOS_INVALID_PORT                 TBS_ERR_CVT(ERR_QOS_BEGIN_ADDR + 20, TR069_ERRNO_INVALID_VAL)
#define ERR_QOS_INVALID_CLASS_QUE            TBS_ERR_CVT(ERR_QOS_BEGIN_ADDR + 21, TR069_ERRNO_INVALID_VAL)
#define ERR_QOS_CLASS_QUE_NOT_EXIST          TBS_ERR_CVT(ERR_QOS_BEGIN_ADDR + 22, TR069_ERRNO_INVALID_VAL)
#define ERR_QOS_SHAPE_RATE_CONFLICT          TBS_ERR_CVT(ERR_QOS_BEGIN_ADDR + 23, TR069_ERRNO_INVALID_VAL)
#define ERR_QOS_QUEUE_LEN_CONFLICT           TBS_ERR_CVT(ERR_QOS_BEGIN_ADDR + 24, TR069_ERRNO_INVALID_VAL)
#define ERR_QOS_QUEUE_WEIGHT_CONFLICT        TBS_ERR_CVT(ERR_QOS_BEGIN_ADDR + 25, TR069_ERRNO_INVALID_VAL)
#define ERR_QOS_QUEUE_PRIO_CONFLICT          TBS_ERR_CVT(ERR_QOS_BEGIN_ADDR + 26, TR069_ERRNO_INVALID_VAL)
#define ERR_QOS_IP_LENGTH_CONFLICT           TBS_ERR_CVT(ERR_QOS_BEGIN_ADDR + 27, TR069_ERRNO_INVALID_VAL)
#define ERR_QOS_PORT_CONFLICT                TBS_ERR_CVT(ERR_QOS_BEGIN_ADDR + 28, TR069_ERRNO_INVALID_VAL)
#define ERR_QOS_WMMMARK_CONFLICT             TBS_ERR_CVT(ERR_QOS_BEGIN_ADDR + 29, TR069_ERRNO_INVALID_VAL)
#define ERR_QOS_INVALID_DSL_UP_SHAPE_RATE    TBS_ERR_CVT(ERR_QOS_BEGIN_ADDR + 30, TR069_ERRNO_INVALID_VAL)
#define ERR_QOS_INVALID_DSL_DOWN_SHAPE_RATE  TBS_ERR_CVT(ERR_QOS_BEGIN_ADDR + 31, TR069_ERRNO_INVALID_VAL)
#endif
/* SNTP */
#define ERR_SNTP_BEGIN_ADDR   TBS_ERR_LOGIC_BASE_ADDR(MID_SNTP)

#define ERR_SNTP_INVALID_UP_INTERVAL        TBS_ERR_CVT(ERR_SNTP_BEGIN_ADDR + 1, TR069_ERRNO_INVALID_VAL)
#define ERR_SNTP_INVALID_RETRY_INTERVAL     TBS_ERR_CVT(ERR_SNTP_BEGIN_ADDR + 2, TR069_ERRNO_INVALID_VAL)
#define ERR_SNTP_INVALID_NTP_SERVER         TBS_ERR_CVT(ERR_SNTP_BEGIN_ADDR + 3, TR069_ERRNO_INVALID_VAL)
#define ERR_SNTP_INVALID_LOCAL_TZ           TBS_ERR_CVT(ERR_SNTP_BEGIN_ADDR + 4, TR069_ERRNO_INVALID_VAL)
#define ERR_SNTP_INVALID_LOCAL_TZ_NAME      TBS_ERR_CVT(ERR_SNTP_BEGIN_ADDR + 5, TR069_ERRNO_INVALID_VAL)
#define ERR_SNTP_INVALID_DATA_TIME          TBS_ERR_CVT(ERR_SNTP_BEGIN_ADDR + 6, TR069_ERRNO_INVALID_VAL)
#define ERR_SNTP_NULL_NTPSERVER_STR         TBS_ERR_CVT(ERR_SNTP_BEGIN_ADDR + 7, TR069_ERRNO_INVALID_VAL)
#define ERR_SNTP_NTPSERVERS_CONFLICT        TBS_ERR_CVT(ERR_SNTP_BEGIN_ADDR + 8, TR069_ERRNO_INVALID_VAL)
#define ERR_SNTP_DST_CONFLICT               TBS_ERR_CVT(ERR_SNTP_BEGIN_ADDR + 9, TR069_ERRNO_INVALID_VAL)
#define ERR_SNTP_INVALID_DATA_YEAR          TBS_ERR_CVT(ERR_SNTP_BEGIN_ADDR + 10,TR069_ERRNO_INVALID_VAL)

/* dynamic route */
#if 0
#define ERR_DYNAMIC_BEGIN_ADDR  TBS_ERR_LOGIC_BASE_ADDR(MID_DYNAMIC_ROUTING)


#define ERR_DYNAMIC_INVALID_VAL                 TBS_ERR_CVT(ERR_DYNAMIC_BEGIN_ADDR + 1, TR069_ERRNO_INVALID_VAL)
#define ERR_DYNAMIC_INVALID_CONFIG_FILE         TBS_ERR_CVT(ERR_DYNAMIC_BEGIN_ADDR + 2, TR069_ERRNO_CPE_ERR)
#define ERR_DYNAMIC_INVALID_INNER_PARA    TBS_ERR_CVT(ERR_DYNAMIC_BEGIN_ADDR + 3, TR069_ERRNO_CPE_ERR)
#define ERR_DYNAMIC_VERSION_INVALID             TBS_ERR_CVT(ERR_DYNAMIC_BEGIN_ADDR + 4, TR069_ERRNO_INVALID_VAL)
#define ERR_DYNAMIC_INVALID_WAN             TBS_ERR_CVT(ERR_DYNAMIC_BEGIN_ADDR + 5, TR069_ERRNO_CPE_ERR)
#define ERR_DYNAMIC_INVALID_PC_MSG              TBS_ERR_CVT(ERR_DYNAMIC_BEGIN_ADDR + 6, TR069_ERRNO_CPE_ERR)
#endif

/* dynamic route */
#define ERR_DROUTE_BEGIN_ADDR               TBS_ERR_LOGIC_BASE_ADDR(MID_DROUTE)

#define ERR_DROUTE_INVALID_VAL              TBS_ERR_CVT(ERR_DROUTE_BEGIN_ADDR + 1, TR069_ERRNO_INVALID_VAL)
#define ERR_DROUTE_INVALID_CONFIG_FILE      TBS_ERR_CVT(ERR_DROUTE_BEGIN_ADDR + 2, TR069_ERRNO_CPE_ERR)
#define ERR_DROUTE_INVALID_INNER_PARA       TBS_ERR_CVT(ERR_DROUTE_BEGIN_ADDR + 3, TR069_ERRNO_CPE_ERR)
#define ERR_DROUTE_VERSION_INVALID          TBS_ERR_CVT(ERR_DROUTE_BEGIN_ADDR + 4, TR069_ERRNO_INVALID_VAL)
#define ERR_DROUTE_INVALID_WAN              TBS_ERR_CVT(ERR_DROUTE_BEGIN_ADDR + 5, TR069_ERRNO_CPE_ERR)
#define ERR_DROUTE_INVALID_PC_MSG           TBS_ERR_CVT(ERR_DROUTE_BEGIN_ADDR + 6, TR069_ERRNO_CPE_ERR)
#define ERR_DROUTE_INVALID_INSTANCE         TBS_ERR_CVT(ERR_DROUTE_BEGIN_ADDR + 7, TR069_ERRNO_CPE_ERR)
#define ERR_DROUTE_INVALID_PATH             TBS_ERR_CVT(ERR_DROUTE_BEGIN_ADDR + 8, TR069_ERRNO_INVALID_VAL)
#define ERR_DROUTE_NO_RESOURSE              TBS_ERR_CVT(ERR_DROUTE_BEGIN_ADDR + 9, TR069_ERRNO_CPE_ERR)
#define ERR_DROUTE_ENABLE_INVALID           TBS_ERR_CVT(ERR_DROUTE_BEGIN_ADDR + 10, TR069_ERRNO_INVALID_VAL)
#define ERR_DROUTE_G_ENABLE_INVALID         TBS_ERR_CVT(ERR_DROUTE_BEGIN_ADDR + 11, TR069_ERRNO_INVALID_VAL)
#define ERR_DROUTE_L_ENABLE_INVALID         TBS_ERR_CVT(ERR_DROUTE_BEGIN_ADDR + 12, TR069_ERRNO_INVALID_VAL)
#define ERR_DROUTE_INTERFACE_NAME_INVALID   TBS_ERR_CVT(ERR_DROUTE_BEGIN_ADDR + 13, TR069_ERRNO_INVALID_VAL)
#define ERR_DROUTE_OPERATE_INVALID          TBS_ERR_CVT(ERR_DROUTE_BEGIN_ADDR + 14, TR069_ERRNO_INVALID_VAL)
#define ERR_DROUTE_INTERFACE_CONFLICT       TBS_ERR_CVT(ERR_DROUTE_BEGIN_ADDR + 15, TR069_ERRNO_CPE_ERR)
#define ERR_DROUTE_INTERFACE                TBS_ERR_CVT(ERR_DROUTE_BEGIN_ADDR + 16, TR069_ERRNO_CPE_ERR)
#define ERR_DROUTE_INVALID_DIRECTION        TBS_ERR_CVT(ERR_DROUTE_BEGIN_ADDR + 17, TR069_ERRNO_CPE_ERR)


/* static route */

#define ERR_STATIC_BEGIN_ADDR  TBS_ERR_LOGIC_BASE_ADDR(MID_STATIC_ROUTING)

#define ERR_STATIC_INVALID_INSTANCE                TBS_ERR_CVT(ERR_STATIC_BEGIN_ADDR + 1, TR069_ERRNO_CPE_ERR)
#define ERR_STATIC_INTERFACE                       TBS_ERR_CVT(ERR_STATIC_BEGIN_ADDR + 2, TR069_ERRNO_CPE_ERR)
#define ERR_STATIC_NO_RESOURSE                     TBS_ERR_CVT(ERR_STATIC_BEGIN_ADDR + 3, TR069_ERRNO_NO_RESOURCE)
#define ERR_STATIC_INVALID_VAL                     TBS_ERR_CVT(ERR_STATIC_BEGIN_ADDR + 4, TR069_ERRNO_INVALID_VAL)
#define ERR_STATIC_ENABLE_INVALID                  TBS_ERR_CVT(ERR_STATIC_BEGIN_ADDR + 5, TR069_ERRNO_INVALID_VAL)
#define ERR_STATIC_INVALID_PATH                    TBS_ERR_CVT(ERR_STATIC_BEGIN_ADDR + 6, TR069_ERRNO_INVALID_PARAM)
#define ERR_STATIC_INVALID_DEFAULT_PARA            TBS_ERR_CVT(ERR_STATIC_BEGIN_ADDR + 7, TR069_ERRNO_INVALID_VAL)
#define ERR_STATIC_INVALID_ROUTE_PARA              TBS_ERR_CVT(ERR_STATIC_BEGIN_ADDR + 8, TR069_ERRNO_CPE_ERR)
#define ERR_STATIC_INVALID_PARA                    TBS_ERR_CVT(ERR_STATIC_BEGIN_ADDR + 9, TR069_ERRNO_CPE_ERR)
#define ERR_STATIC_DEL_INSTANCE                    TBS_ERR_CVT(ERR_STATIC_BEGIN_ADDR + 10, TR069_ERRNO_CPE_ERR)
#define ERR_STATIC_INVALID_METRIC                  TBS_ERR_CVT(ERR_STATIC_BEGIN_ADDR + 11, TR069_ERRNO_INVALID_VAL)
#define ERR_STATIC_INVALID_IP                      TBS_ERR_CVT(ERR_STATIC_BEGIN_ADDR + 12, TR069_ERRNO_INVALID_VAL)
#define ERR_STATIC_IP_EMPTY                        TBS_ERR_CVT(ERR_STATIC_BEGIN_ADDR + 13, TR069_ERRNO_INVALID_VAL)
#define ERR_STATIC_INVALID_MASK                    TBS_ERR_CVT(ERR_STATIC_BEGIN_ADDR + 14, TR069_ERRNO_INVALID_VAL)
#define ERR_STATIC_MASK_EMPTY                      TBS_ERR_CVT(ERR_STATIC_BEGIN_ADDR + 15, TR069_ERRNO_INVALID_VAL)
#define ERR_STATIC_INVALID_GATEWAY                 TBS_ERR_CVT(ERR_STATIC_BEGIN_ADDR + 16, TR069_ERRNO_INVALID_VAL)
#define ERR_STATIC_METRIC_OUT_LIMITED              TBS_ERR_CVT(ERR_STATIC_BEGIN_ADDR + 17, TR069_ERRNO_INVALID_VAL)
#define ERR_STATIC_INVALID_LOGFILE                 TBS_ERR_CVT(ERR_STATIC_BEGIN_ADDR + 18, TR069_ERRNO_CPE_ERR)
#define ERR_STATIC_BRIDGECONN_AS_DEFAULTROUT       TBS_ERR_CVT(ERR_STATIC_BEGIN_ADDR + 19, TR069_ERRNO_INVALID_VAL)
#define ERR_STATIC_IPV6CONN_AS_IPV4DEFAULTROUT     TBS_ERR_CVT(ERR_STATIC_BEGIN_ADDR + 20, TR069_ERRNO_INVALID_VAL)
#define ERR_STATIC_IP_NOT_MATCH_MASK               TBS_ERR_CVT(ERR_STATIC_BEGIN_ADDR + 21, TR069_ERRNO_CPE_ERR)
#define ERR_STATIC_MANAGERCONN_AS_DEFAULTROUT      TBS_ERR_CVT(ERR_STATIC_BEGIN_ADDR + 22, TR069_ERRNO_INVALID_VAL)
#define ERR_STATIC_INVALID_INTERFACE               TBS_ERR_CVT(ERR_STATIC_BEGIN_ADDR + 23, TR069_ERRNO_INVALID_VAL)
#define ERR_STATIC_DUPLICATE_ROUTING               TBS_ERR_CVT(ERR_STATIC_BEGIN_ADDR + 24, TR069_ERRNO_INVALID_VAL)
#define ERR_STATIC_DUPLICATE_DESTIP               TBS_ERR_CVT(ERR_STATIC_BEGIN_ADDR + 25, TR069_ERRNO_INVALID_VAL)

#define ERR_SROUTE_BEGIN_ADDR               TBS_ERR_LOGIC_BASE_ADDR(MID_SROUTE)

#define ERR_SROUTE_INVALID_INSTANCE         TBS_ERR_CVT(ERR_SROUTE_BEGIN_ADDR + 1, TR069_ERRNO_CPE_ERR)
#define ERR_SROUTE_INTERFACE                TBS_ERR_CVT(ERR_SROUTE_BEGIN_ADDR + 2, TR069_ERRNO_CPE_ERR)
#define ERR_SROUTE_NO_RESOURSE              TBS_ERR_CVT(ERR_SROUTE_BEGIN_ADDR + 3, TR069_ERRNO_NO_RESOURCE)
#define ERR_SROUTE_INVALID_VAL              TBS_ERR_CVT(ERR_SROUTE_BEGIN_ADDR + 4, TR069_ERRNO_INVALID_VAL)
#define ERR_SROUTE_ENABLE_INVALID           TBS_ERR_CVT(ERR_SROUTE_BEGIN_ADDR + 5, TR069_ERRNO_INVALID_VAL)
#define ERR_SROUTE_INVALID_PATH             TBS_ERR_CVT(ERR_SROUTE_BEGIN_ADDR + 6, TR069_ERRNO_INVALID_PARAM)
#define ERR_SROUTE_INVALID_DEFAULT_PARA     TBS_ERR_CVT(ERR_SROUTE_BEGIN_ADDR + 7, TR069_ERRNO_INVALID_VAL)
#define ERR_SROUTE_INVALID_ROUTE_PARA       TBS_ERR_CVT(ERR_SROUTE_BEGIN_ADDR + 8, TR069_ERRNO_CPE_ERR)
#define ERR_SROUTE_INVALID_PARA             TBS_ERR_CVT(ERR_SROUTE_BEGIN_ADDR + 9, TR069_ERRNO_CPE_ERR)
#define ERR_SROUTE_DEL_INSTANCE             TBS_ERR_CVT(ERR_SROUTE_BEGIN_ADDR + 10, TR069_ERRNO_CPE_ERR)
#define ERR_SROUTE_INVALID_METRIC           TBS_ERR_CVT(ERR_SROUTE_BEGIN_ADDR + 11, TR069_ERRNO_INVALID_VAL)
#define ERR_SROUTE_INVALID_IP               TBS_ERR_CVT(ERR_SROUTE_BEGIN_ADDR + 12, TR069_ERRNO_INVALID_VAL)
#define ERR_SROUTE_IP_EMPTY                 TBS_ERR_CVT(ERR_SROUTE_BEGIN_ADDR + 13, TR069_ERRNO_INVALID_VAL)
#define ERR_SROUTE_INVALID_MASK             TBS_ERR_CVT(ERR_SROUTE_BEGIN_ADDR + 14, TR069_ERRNO_INVALID_VAL)
#define ERR_SROUTE_MASK_EMPTY               TBS_ERR_CVT(ERR_SROUTE_BEGIN_ADDR + 15, TR069_ERRNO_INVALID_VAL)
#define ERR_SROUTE_INVALID_GATEWAY          TBS_ERR_CVT(ERR_SROUTE_BEGIN_ADDR + 16, TR069_ERRNO_INVALID_VAL)
#define ERR_SROUTE_METRIC_OUT_LIMITED       TBS_ERR_CVT(ERR_SROUTE_BEGIN_ADDR + 17, TR069_ERRNO_INVALID_VAL)
#define ERR_SROUTE_INVALID_LOGFILE          TBS_ERR_CVT(ERR_SROUTE_BEGIN_ADDR + 18, TR069_ERRNO_CPE_ERR)
#define ERR_SROUTE_BRIDGECONN_AS_DEFAULTROUT       TBS_ERR_CVT(ERR_SROUTE_BEGIN_ADDR + 19, TR069_ERRNO_INVALID_VAL)
#define ERR_SROUTE_IPV6CONN_AS_IPV4DEFAULTROUT     TBS_ERR_CVT(ERR_SROUTE_BEGIN_ADDR + 20, TR069_ERRNO_INVALID_VAL)
#define ERR_SROUTE_IP_NOT_MATCH_MASK               TBS_ERR_CVT(ERR_SROUTE_BEGIN_ADDR + 21, TR069_ERRNO_CPE_ERR)
#define ERR_SROUTE_MANAGERCONN_AS_DEFAULTROUT TBS_ERR_CVT(ERR_SROUTE_BEGIN_ADDR + 22,TR069_ERRNO_INVALID_VAL)

/* IPV6 static routing */
#define ERR_V6SROUTE_BEGIN_ADDR                  TBS_ERR_LOGIC_BASE_ADDR(MID_V6SROUTE)
#define ERR_V6SROUTE_ENABLE_INVALID              TBS_ERR_CVT(ERR_V6SROUTE_BEGIN_ADDR + 1, TR069_ERRNO_INVALID_VAL)
#define ERR_V6SROUTE_BAD_PREFIX                  TBS_ERR_CVT(ERR_V6SROUTE_BEGIN_ADDR + 2, TR069_ERRNO_INVALID_VAL)
#define ERR_V6SROUTE_BAD_METRIC                  TBS_ERR_CVT(ERR_V6SROUTE_BEGIN_ADDR + 3, TR069_ERRNO_INVALID_VAL)
#define ERR_V6SROUTE_BAD_ADDR                    TBS_ERR_CVT(ERR_V6SROUTE_BEGIN_ADDR + 4, TR069_ERRNO_INVALID_VAL)
#define ERR_V6SROUTE_REPEAT                   TBS_ERR_CVT(ERR_V6SROUTE_BEGIN_ADDR + 5, TR069_ERRNO_INVALID_VAL)
#define ERR_V6SROUTE_GET_FAIL                   TBS_ERR_CVT(ERR_V6SROUTE_BEGIN_ADDR + 6, TR069_ERRNO_INVALID_VAL)
#define ERR_V6ROUTE_IP_NULL                   TBS_ERR_CVT(ERR_V6SROUTE_BEGIN_ADDR + 7, TR069_ERRNO_INVALID_VAL)
#define ERR_V6ROUTE_COUNT_ERROR                   TBS_ERR_CVT(ERR_V6SROUTE_BEGIN_ADDR + 8, TR069_ERRNO_INVALID_VAL)
#define ERR_V6SROUTE_BAD_INTERFACE                TBS_ERR_CVT(ERR_V6SROUTE_BEGIN_ADDR + 9, TR069_ERRNO_INVALID_VAL)

/*policy route*/
#define ERR_POLICY_BEGIN_ADDR  TBS_ERR_LOGIC_BASE_ADDR(MID_PROUTE)

#define ERR_PROUTE_WANPATH_CONFLICT           TBS_ERR_CVT(ERR_POLICY_BEGIN_ADDR + 1, TR069_ERRNO_CPE_ERR)
#define ERR_PROUTE_LANPATH_CONFLICT           TBS_ERR_CVT(ERR_POLICY_BEGIN_ADDR + 2, TR069_ERRNO_CPE_ERR)
#define ERR_PROUTE_INVALID_INNER_PARA     TBS_ERR_CVT(ERR_POLICY_BEGIN_ADDR + 3, TR069_ERRNO_CPE_ERR)




/* SNMPC */
#define ERR_SNMPC_BEGIN_ADDR    TBS_ERR_LOGIC_BASE_ADDR(MID_SNMPC)
#define ERR_SNMPC_INVALID_VERSION               TBS_ERR_CVT(ERR_SNMPC_BEGIN_ADDR + 1, TR069_ERRNO_INVALID_VAL)


/* Firewall */
#define ERR_FW_BEGIN_ADDR       TBS_ERR_LOGIC_BASE_ADDR(MID_FIREWALL)
#define ERR_FW_RULES_OVER                       TBS_ERR_CVT(ERR_FW_BEGIN_ADDR + 1, TR069_ERRNO_NO_RESOURCE)
#define ERR_FW_RULE_EXISTS                      TBS_ERR_CVT(ERR_FW_BEGIN_ADDR + 2, TR069_ERRNO_NO_RESOURCE)
#define ERR_FW_SRC_IP_EMPTY                      TBS_ERR_CVT(ERR_FW_BEGIN_ADDR + 3, TR069_ERRNO_NO_RESOURCE)
#define ERR_FW_DEST_IP_EMPTY                      TBS_ERR_CVT(ERR_FW_BEGIN_ADDR + 4, TR069_ERRNO_NO_RESOURCE)

/* IPT */
#define ERR_IPT_BEGIN_ADDR      TBS_ERR_LOGIC_BASE_ADDR(MID_IPT)

#define ERR_IPT_INVALID_NATTYPE TBS_ERR_CVT(ERR_IPT_BEGIN_ADDR + 1, TR069_ERRNO_INVALID_VAL)
#define ERR_IPT_CONFLICT_DMZ    TBS_ERR_CVT(ERR_IPT_BEGIN_ADDR + 2, TR069_ERRNO_INVALID_VAL)
#define ERR_IPT_INVALID_SVCTYPE TBS_ERR_CVT(ERR_IPT_BEGIN_ADDR + 3, TR069_ERRNO_INVALID_VAL)
#define ERR_IPT_CONFLICT_SVCTYPE TBS_ERR_CVT(ERR_IPT_BEGIN_ADDR + 4, TR069_ERRNO_INVALID_VAL)

/* wlan */
#define ERR_WLAN_BEGIN_ADDR     TBS_ERR_LOGIC_BASE_ADDR(MID_WLAN)

#define ERR_WLAN_NO_RESOURSE   TBS_ERR_CVT(ERR_WLAN_BEGIN_ADDR + 1, TR069_ERRNO_NO_RESOURCE)
#define ERR_WLAN_INVALID_VAL		TBS_ERR_CVT(ERR_WLAN_BEGIN_ADDR + 2, TR069_ERRNO_INVALID_VAL)
#define ERR_WLAN_INVALID_PATH	TBS_ERR_CVT(ERR_WLAN_BEGIN_ADDR + 3, TR069_ERRNO_INVALID_PARAM)
#define ERR_WLAN_VAL_EMPTY    TBS_ERR_CVT(ERR_WLAN_BEGIN_ADDR + 4, TR069_ERRNO_NO_RESOURCE)
#define ERR_WLAN_EXCEED_VAP_NUM    TBS_ERR_CVT(ERR_WLAN_BEGIN_ADDR + 5, TR069_ERRNO_NO_RESOURCE)
#define ERR_WLAN_INVALID_INSTANCE	TBS_ERR_CVT(ERR_WLAN_BEGIN_ADDR + 6, TR069_ERRNO_CPE_ERR)
#define ERR_WLAN_INVALID_VAPIDX	TBS_ERR_CVT(ERR_WLAN_BEGIN_ADDR + 7, TR069_ERRNO_INVALID_VAL)
#define ERR_WLAN_IN_OOB     TBS_ERR_CVT(ERR_WLAN_BEGIN_ADDR + 8, TR069_ERRNO_INVALID_VAL)
#define ERR_WLAN_NAME_REPEATED        TBS_ERR_CVT(ERR_WLAN_BEGIN_ADDR + 9, TR069_ERRNO_NO_RESOURCE)
#define ERR_WLAN_INVALID_SSID    TBS_ERR_CVT(ERR_WLAN_BEGIN_ADDR + 10, TR069_ERRNO_INVALID_VAL)
#define ERR_WLAN_INVALID_SESSION	TBS_ERR_CVT(ERR_WLAN_BEGIN_ADDR + 11, TR069_ERRNO_REJECT)
#define ERR_WLAN_DELETE_MANAGEMENT_VAP  TBS_ERR_CVT(ERR_WLAN_BEGIN_ADDR + 12, TR069_ERRNO_REJECT)
#define ERR_WLAN_INVALID_SSID_LENGTH   TBS_ERR_CVT(ERR_WLAN_BEGIN_ADDR + 13, TR069_ERRNO_INVALID_VAL)
#define ERR_WLAN_CONFLICT_ENCMODES_STANDARD TBS_ERR_CVT(ERR_WLAN_BEGIN_ADDR + 14, TR069_ERRNO_INVALID_VAL)
#define ERR_WLAN_CONFLICT_ENCMODES_STANDARD_1 TBS_ERR_CVT(ERR_WLAN_BEGIN_ADDR + 15, TR069_ERRNO_INVALID_VAL)
#define ERR_WLAN_CONFLICT_ENCMODES_STANDARD_2 TBS_ERR_CVT(ERR_WLAN_BEGIN_ADDR + 16, TR069_ERRNO_INVALID_VAL)
#define ERR_WLAN_CONFLICT_ENCMODES_STANDARD_3 TBS_ERR_CVT(ERR_WLAN_BEGIN_ADDR + 17, TR069_ERRNO_INVALID_VAL)
#define ERR_WLAN_CONFLICT_ENCMODES_STANDARD_4 TBS_ERR_CVT(ERR_WLAN_BEGIN_ADDR + 18, TR069_ERRNO_INVALID_VAL)
#define ERR_WLAN_CONFLICT_ENCMODES_STANDARD_5 TBS_ERR_CVT(ERR_WLAN_BEGIN_ADDR + 19, TR069_ERRNO_INVALID_VAL)
#define ERR_WLAN_CONFLICT_ENCMODES_STANDARD_6 TBS_ERR_CVT(ERR_WLAN_BEGIN_ADDR + 20, TR069_ERRNO_INVALID_VAL)
#define ERR_WLAN_CONFLICT_ENCMODES_STANDARD_7 TBS_ERR_CVT(ERR_WLAN_BEGIN_ADDR + 21, TR069_ERRNO_INVALID_VAL)
#define ERR_WLAN_CONFLICT_ENCMODES_STANDARD_8 TBS_ERR_CVT(ERR_WLAN_BEGIN_ADDR + 22, TR069_ERRNO_INVALID_VAL)
//由于wlanWDS模块要求可以将MAC设为全零，故其公用模块的MAC错误报错信息不能用于WDS模块，故加此条信息
#define ERR_WLAN_INVALID_MAC_VALUE	TBS_ERR_CVT(ERR_WLAN_BEGIN_ADDR + 23, TR069_ERRNO_INVALID_VAL)
#define ERR_WLAN_INVALID_MAXSTATION_NUM TBS_ERR_CVT(ERR_WLAN_BEGIN_ADDR + 24, TR069_ERRNO_INVALID_VAL)
#define ERR_WLAN_GET_CHANNEL_AUTOCHANNEL TBS_ERR_CVT(ERR_WLAN_BEGIN_ADDR + 25, TR069_ERRNO_INVALID_VAL)
#define ERR_WLAN_CONFLICT_CHANNEL_AUTOCHANNEL TBS_ERR_CVT(ERR_WLAN_BEGIN_ADDR + 26, TR069_ERRNO_INVALID_VAL)
#define ERR_WLAN_SSID_DISABLE TBS_ERR_CVT(ERR_WLAN_BEGIN_ADDR + 27, TR069_ERRNO_REJECT)

/*tr069be*/
#define ERR_TR069BE_BEGIN_ADDR    TBS_ERR_LOGIC_BASE_ADDR(MID_TR069BE)

#define ERR_TR069BE_INVALID_URL    TBS_ERR_CVT(ERR_TR069BE_BEGIN_ADDR+1, TR069_ERRNO_INVALID_VAL)
#define ERROR_TR069_INVALID_CAFILE   TBS_ERR_CVT(ERR_TR069BE_BEGIN_ADDR+2, TR069_ERRNO_INVALID_VAL)
#define ERR_TR069BE_INVALID_UPLOAD_URL   TBS_ERR_CVT(ERR_TR069BE_BEGIN_ADDR+3, TR069_ERRNO_INVALID_URL)
#define ERR_TR069BE_INVALID_DOWNLOAD_URL   TBS_ERR_CVT(ERR_TR069BE_BEGIN_ADDR+4, TR069_ERRNO_INVALID_URL)

/* PortMapping */
#define ERR_PTMP_BEGIN_ADDR      TBS_ERR_LOGIC_BASE_ADDR(MID_PORTMAPPING)

#define ERR_PTMP_INVALID_DURATION    TBS_ERR_CVT(ERR_PTMP_BEGIN_ADDR + 1, TR069_ERRNO_INVALID_VAL)
#define ERR_PTMP_INVALID_PROTOCOL    TBS_ERR_CVT(ERR_PTMP_BEGIN_ADDR + 2, TR069_ERRNO_INVALID_VAL)
#define ERR_PTMP_INVALID_DESCRIPTION TBS_ERR_CVT(ERR_PTMP_BEGIN_ADDR + 3, TR069_ERRNO_INVALID_VAL)
#define ERR_PTMP_CONFLICT_PORTRANGE  TBS_ERR_CVT(ERR_PTMP_BEGIN_ADDR + 4, TR069_ERRNO_INVALID_VAL)
#define ERR_PTMP_CONFLICT_TUPLE      TBS_ERR_CVT(ERR_PTMP_BEGIN_ADDR + 5, TR069_ERRNO_INVALID_VAL)
#define ERR_PTMP_CONFLICT_PORTRANGE_7547  TBS_ERR_CVT(ERR_PTMP_BEGIN_ADDR + 6, TR069_ERRNO_INVALID_VAL)
#define ERR_PTMP_INVALID_HOST_NAME TBS_ERR_CVT(ERR_PTMP_BEGIN_ADDR + 7, TR069_ERRNO_INVALID_VAL)
#define ERR_PTMP_NOTINSAMESUBNET     TBS_ERR_CVT(ERR_PTMP_BEGIN_ADDR + 8, TR069_ERRNO_INVALID_VAL)
#define ERR_PORT_HAS_OCCUPIED        TBS_ERR_CVT(ERR_PTMP_BEGIN_ADDR + 9, TR069_ERRNO_INVALID_VAL)
     //由于ulInternPort值有最大值，判断后需给出提示信息，故加如下这一行
#define ERR_PTMP_CONFLICT_PORTRANGE_ulInternPort TBS_ERR_CVT(ERR_PTMP_BEGIN_ADDR + 10, TR069_ERRNO_INVALID_VAL)
#define ERR_PTMP_WRONG_HOST_IP TBS_ERR_CVT(ERR_PTMP_BEGIN_ADDR + 11, TR069_ERRNO_INVALID_VAL)
#define ERR_PTMP_CONFLICT_PORTRANGE_HTTP  TBS_ERR_CVT(ERR_PTMP_BEGIN_ADDR + 12, TR069_ERRNO_INVALID_VAL)
#define ERR_PTMP_CONFLICT_PORTRANGE_SNMP  TBS_ERR_CVT(ERR_PTMP_BEGIN_ADDR + 13, TR069_ERRNO_INVALID_VAL)
#define ERR_PTMP_CONFLICT_PORTRANGE_SSH  TBS_ERR_CVT(ERR_PTMP_BEGIN_ADDR + 14, TR069_ERRNO_INVALID_VAL)
#define ERR_PTMP_CONFLICT_PORTRANGE_TELNET  TBS_ERR_CVT(ERR_PTMP_BEGIN_ADDR + 15, TR069_ERRNO_INVALID_VAL)
#define ERR_PTMP_CONFLICT_PORTRANGE_TFTP  TBS_ERR_CVT(ERR_PTMP_BEGIN_ADDR + 16, TR069_ERRNO_INVALID_VAL)
#define ERR_PTMP_CONFLICT_PORTRANGE_DNS  TBS_ERR_CVT(ERR_PTMP_BEGIN_ADDR + 17, TR069_ERRNO_INVALID_VAL)
#define ERR_PTMP_CONFLICT_PORTRANGE_HTTPS  TBS_ERR_CVT(ERR_PTMP_BEGIN_ADDR + 18, TR069_ERRNO_INVALID_VAL)
#define ERR_PTMP_CONFLICT_PORTRANGE_TR069  TBS_ERR_CVT(ERR_PTMP_BEGIN_ADDR + 19, TR069_ERRNO_INVALID_VAL)
#define ERR_PTMP_CONFLICT_PORTRANGE_FTP  TBS_ERR_CVT(ERR_PTMP_BEGIN_ADDR + 20, TR069_ERRNO_INVALID_VAL)

/* usb 3g pin */
#define ERR_USB3G_PIN_MNGR		TBS_ERR_LOGIC_BASE_ADDR(MID_USB3G)

#define ERR_USB3G_INVALID_PIN_LENGTH    TBS_ERR_CVT(ERR_USB3G_PIN_MNGR + 1, TR069_ERRNO_INVALID_VAL)
#define ERR_USB3G_INVALID_PUK_LENGTH    TBS_ERR_CVT(ERR_USB3G_PIN_MNGR + 2, TR069_ERRNO_INVALID_VAL)
#define ERR_USB3G_INVALID_PINPUKCODE    TBS_ERR_CVT(ERR_USB3G_PIN_MNGR + 3, TR069_ERRNO_INVALID_VAL)

/* URL FILTER */
#define ERR_URLFILTER_BEGIN_ADDR    TBS_ERR_LOGIC_BASE_ADDR(MID_URLFILTER)

#define ERR_URLFILTER_INVALID_INNER_PARA    TBS_ERR_CVT(ERR_URLFILTER_BEGIN_ADDR+1, TR069_ERRNO_CPE_ERR)
#define ERR_URLFILTER_INVALID_VAL           TBS_ERR_CVT(ERR_URLFILTER_BEGIN_ADDR+2, TR069_ERRNO_INVALID_VAL)
#define ERR_URLFILTER_ENABLE_EMPTY          TBS_ERR_CVT(ERR_URLFILTER_BEGIN_ADDR+3, TR069_ERRNO_INVALID_VAL)
#define ERR_URLFILTER_ENABLE_INVALID        TBS_ERR_CVT(ERR_URLFILTER_BEGIN_ADDR+4, TR069_ERRNO_INVALID_VAL)
#define ERR_URLFILTER_INVALID_CONFIG_FILE   TBS_ERR_CVT(ERR_URLFILTER_BEGIN_ADDR+5, TR069_ERRNO_CPE_ERR)
#define ERR_URLFILTER_MODE_EMPTY            TBS_ERR_CVT(ERR_URLFILTER_BEGIN_ADDR+6, TR069_ERRNO_INVALID_VAL)
#define ERR_URLFILTER_MODE_INVALID          TBS_ERR_CVT(ERR_URLFILTER_BEGIN_ADDR+7, TR069_ERRNO_INVALID_VAL)
#define ERR_URLFILTER_URL_CONFLICT          TBS_ERR_CVT(ERR_URLFILTER_BEGIN_ADDR+8, TR069_ERRNO_NO_RESOURCE)
#define ERR_URLFILTER_URLNUMBER_OVER		TBS_ERR_CVT(ERR_URLFILTER_BEGIN_ADDR+9, TR069_ERRNO_NO_RESOURCE)
#define ERR_URLFILTER_URL_LENGTH_OVER       TBS_ERR_CVT(ERR_URLFILTER_BEGIN_ADDR+10, TR069_ERRNO_INVALID_VAL)
#define ERR_URLFILTER_URL_ERROR				TBS_ERR_CVT(ERR_URLFILTER_BEGIN_ADDR+11, TR069_ERRNO_INVALID_VAL)
#define ERR_URLFILTER_INVALID_FILTERMODE     TBS_ERR_CVT(ERR_URLFILTER_BEGIN_ADDR + 12, TR069_ERRNO_CPE_ERR)
#define ERR_URLFILTER_INVALID_TIME           TBS_ERR_CVT(ERR_URLFILTER_BEGIN_ADDR + 13, TR069_ERRNO_CPE_ERR)
#define ERR_URLFILTER_INVALID_DAY            TBS_ERR_CVT(ERR_URLFILTER_BEGIN_ADDR + 14, TR069_ERRNO_CPE_ERR)
#define ERR_URLFILTER_TIME_CONFLICT          TBS_ERR_CVT(ERR_URLFILTER_BEGIN_ADDR + 15, TR069_ERRNO_CPE_ERR)
#define ERR_URLFILTER_MAC_CONFLICT           TBS_ERR_CVT(ERR_URLFILTER_BEGIN_ADDR + 16, TR069_ERRNO_CPE_ERR)
#define ERR_URLFILTER_SCHEDULE_MODE           TBS_ERR_CVT(ERR_URLFILTER_BEGIN_ADDR + 17, TR069_ERRNO_CPE_ERR)
#define ERR_URLFILTER_SCHEDULE_PATH           TBS_ERR_CVT(ERR_URLFILTER_BEGIN_ADDR + 18, TR069_ERRNO_CPE_ERR)
#define ERR_URLFILTER_INVALID_NAME           TBS_ERR_CVT(ERR_URLFILTER_BEGIN_ADDR + 19, TR069_ERRNO_CPE_ERR)

/*
#define ERR_URLFILTER_INVALID_FILTERMODE     TBS_ERR_CVT(ERR_URLFILTER_BEGIN_ADDR + 12, TR069_ERRNO_CPE_ERR)
#define ERR_URLFILTER_INVALID_TIME           TBS_ERR_CVT(ERR_URLFILTER_BEGIN_ADDR + 13, TR069_ERRNO_CPE_ERR)
#define ERR_URLFILTER_INVALID_DAY            TBS_ERR_CVT(ERR_URLFILTER_BEGIN_ADDR + 14, TR069_ERRNO_CPE_ERR)
#define ERR_URLFILTER_TIME_CONFLICT          TBS_ERR_CVT(ERR_URLFILTER_BEGIN_ADDR + 15, TR069_ERRNO_CPE_ERR)
#define ERR_URLFILTER_MAC_CONFLICT           TBS_ERR_CVT(ERR_URLFILTER_BEGIN_ADDR + 16, TR069_ERRNO_CPE_ERR)
*/
/* ACL */
#define ERR_ACL_BEGIN_ADDR                  TBS_ERR_LOGIC_BASE_ADDR(MID_ACL)
#define ERR_ACL_RULES_OVER                  TBS_ERR_CVT(ERR_ACL_BEGIN_ADDR + 1, TR069_ERRNO_NO_RESOURCE)
#define ERR_ACL_RULE_EXISTS                 TBS_ERR_CVT(ERR_ACL_BEGIN_ADDR + 2, TR069_ERRNO_INVALID_VAL)
#define ERR_ACL_PORT_BE_ZERO                TBS_ERR_CVT(ERR_ACL_BEGIN_ADDR + 3, TR069_ERRNO_INVALID_VAL)
#define ERR_ACL_PORT_CANOT_ZERO             TBS_ERR_CVT(ERR_ACL_BEGIN_ADDR + 4, TR069_ERRNO_INVALID_VAL)
#define ERR_ACL_PORT_IN_USE                 TBS_ERR_CVT(ERR_ACL_BEGIN_ADDR + 5, TR069_ERRNO_INVALID_VAL)

/* ATM */
#define ERR_ATM_BEGIN_ADDR                  TBS_ERR_LOGIC_BASE_ADDR(MID_ATM)
#define ERR_ATM_PVC                         TBS_ERR_CVT(ERR_ATM_BEGIN_ADDR + 1, TR069_ERRNO_NO_RESOURCE)
#define ERR_ATM_VPI                         TBS_ERR_CVT(ERR_ATM_BEGIN_ADDR + 2, TR069_ERRNO_INVALID_VAL)
#define ERR_ATM_VCI                         TBS_ERR_CVT(ERR_ATM_BEGIN_ADDR + 3, TR069_ERRNO_INVALID_VAL)
#define ERR_ATM_UNKNOWN_ENCAP               TBS_ERR_CVT(ERR_ATM_BEGIN_ADDR + 4, TR069_ERRNO_INVALID_VAL)
#define ERR_ATM_UNKNOWN_QOS_TYPE            TBS_ERR_CVT(ERR_ATM_BEGIN_ADDR + 5, TR069_ERRNO_INVALID_VAL)
#define ERR_ATM_PCR                         TBS_ERR_CVT(ERR_ATM_BEGIN_ADDR + 6, TR069_ERRNO_INVALID_VAL)
#define ERR_ATM_MBS                         TBS_ERR_CVT(ERR_ATM_BEGIN_ADDR + 7, TR069_ERRNO_INVALID_VAL)
#define ERR_ATM_SCR                         TBS_ERR_CVT(ERR_ATM_BEGIN_ADDR + 8, TR069_ERRNO_INVALID_VAL)
#define ERR_ATM_MIN_PCR                     TBS_ERR_CVT(ERR_ATM_BEGIN_ADDR + 9, TR069_ERRNO_INVALID_VAL)
#define ERR_ATM_PVC_CONFLICT                TBS_ERR_CVT(ERR_ATM_BEGIN_ADDR + 10, TR069_ERRNO_INVALID_VAL)
#define ERR_ATM_VLAN_ID                     TBS_ERR_CVT(ERR_ATM_BEGIN_ADDR + 11, TR069_ERRNO_INVALID_VAL)
#define ERR_ATM_VLAN_PRIORITY               TBS_ERR_CVT(ERR_ATM_BEGIN_ADDR + 12, TR069_ERRNO_INVALID_VAL)
#define ERR_ATM_VLAN_ID_CONFLICT            TBS_ERR_CVT(ERR_ATM_BEGIN_ADDR + 13, TR069_ERRNO_INVALID_VAL)
#define ERR_ATM_UNKNOWN_LINK_TYPE           TBS_ERR_CVT(ERR_ATM_BEGIN_ADDR + 14, TR069_ERRNO_INVALID_VAL)

/*FTPCLIENT */
#define ERR_FTPCLIENT_BEGIN_ADDR            TBS_ERR_LOGIC_BASE_ADDR(MID_FTPCLIENT)
#define ERR_FTPCLIENT_INVALID_URL           TBS_ERR_CVT(ERR_FTPCLIENT_BEGIN_ADDR + 1, TR069_ERRNO_INVALID_VAL)
#define ERR_FTPCLIENT_INVALID_USB           TBS_ERR_CVT(ERR_FTPCLIENT_BEGIN_ADDR + 2, TR069_ERRNO_INVALID_VAL)
#define ERR_FTPCLIENT_INVALID_PATH          TBS_ERR_CVT(ERR_FTPCLIENT_BEGIN_ADDR + 3, TR069_ERRNO_INVALID_VAL)
#define ERR_FTPCLIENT_NOSPACE               TBS_ERR_CVT(ERR_FTPCLIENT_BEGIN_ADDR + 4, TR069_ERRNO_CPE_ERR)
#define ERR_FTPCLIENT_SIZE                  TBS_ERR_CVT(ERR_FTPCLIENT_BEGIN_ADDR + 5, TR069_ERRNO_CPE_ERR)
#define ERR_FTPCLIENT_CONN_REFUSE           TBS_ERR_CVT(ERR_FTPCLIENT_BEGIN_ADDR + 6, TR069_ERRNO_CPE_ERR)
#define ERR_FTPCLIENT_DOWN_ING              TBS_ERR_CVT(ERR_FTPCLIENT_BEGIN_ADDR + 7, TR069_ERRNO_CPE_ERR)
#define ERR_FTPCLIENT_DOWN_FINISHED         TBS_ERR_CVT(ERR_FTPCLIENT_BEGIN_ADDR + 8, TR069_ERRNO_CPE_ERR)
#define ERR_FTPCLIENT_DOWN_FAIL             TBS_ERR_CVT(ERR_FTPCLIENT_BEGIN_ADDR + 9, TR069_ERRNO_CPE_ERR)

/*LOGGER*/
#define ERR_LOGGER_BEGIN_ADDR               TBS_ERR_LOGIC_BASE_ADDR(MID_LOG)
#define ERR_LOGGER_UPLOAD_FAILED            TBS_ERR_CVT(ERR_LOGGER_BEGIN_ADDR+1, TR069_ERRNO_UPLOAD_FAIL)
#define ERR_LOGGER_INVALID_TFTP_SERVER      TBS_ERR_CVT(ERR_LOGGER_BEGIN_ADDR+2, TR069_ERRNO_INVALID_VAL)
#define ERR_LOGGER_CLEAR_FAILED             TBS_ERR_CVT(ERR_LOGGER_BEGIN_ADDR+3, TR069_ERRNO_CPE_ERR)
#define ERR_LOGGER_EMPTY_TFTP_SERVER        TBS_ERR_CVT(ERR_LOGGER_BEGIN_ADDR+4, TR069_ERRNO_INVALID_VAL)
#define ERR_LOGGER_INVALID_SERVER           TBS_ERR_CVT(ERR_LOGGER_BEGIN_ADDR+5, TR069_ERRNO_INVALID_VAL)


/* PC */
#define ERR_PC_BEGIN_ADDR  TBS_ERR_PROC_BASE_ADDR(MID_PC)

#define ERR_PC_PCB_NOT_FOUND                 TBS_ERR_CVT(ERR_PC_BEGIN_ADDR + 1, TR069_ERRNO_CPE_ERR)
#define ERR_PC_PCB_FULL                      TBS_ERR_CVT(ERR_PC_BEGIN_ADDR + 2, TR069_ERRNO_CPE_ERR)
#define ERR_PC_NO_EXECV                      TBS_ERR_CVT(ERR_PC_BEGIN_ADDR + 3, TR069_ERRNO_CPE_ERR)
#define ERR_PC_FORK_FAIL                     TBS_ERR_CVT(ERR_PC_BEGIN_ADDR + 4, TR069_ERRNO_CPE_ERR)
#define ERR_PC_REGCOMP                       TBS_ERR_CVT(ERR_PC_BEGIN_ADDR + 5, TR069_ERRNO_CPE_ERR)
#define ERR_PC_COMID                         TBS_ERR_CVT(ERR_PC_BEGIN_ADDR + 6, TR069_ERRNO_CPE_ERR)

/* UPNP */
#define ERR_UPNP_BEGIN_ADDR TBS_ERR_LOGIC_BASE_ADDR(MID_UPNP)

#define ERR_UPNP_SRCIP_EXIST                 TBS_ERR_CVT(ERR_UPNP_BEGIN_ADDR + 1, TR069_ERRNO_INVALID_VAL)

/* DDNS */
#define ERR_DDNS_BEGIN_ADDR  TBS_ERR_LOGIC_BASE_ADDR(MID_DDNS)

#define ERR_DDNS_INVALID_DDNSPROVIDER        TBS_ERR_CVT(ERR_DDNS_BEGIN_ADDR + 1, TR069_ERRNO_CPE_ERR)
#define ERR_DDNS_INVALID_HOSTNAME            TBS_ERR_CVT(ERR_DDNS_BEGIN_ADDR + 2, TR069_ERRNO_CPE_ERR)
#define ERR_DDNS_HOSTNAME_LENGTH_OVER        TBS_ERR_CVT(ERR_DDNS_BEGIN_ADDR + 3, TR069_ERRNO_CPE_ERR)
#define ERR_DDNS_INVALID_WAN_CONN_SID        TBS_ERR_CVT(ERR_DDNS_BEGIN_ADDR + 4, TR069_ERRNO_CPE_ERR)
#define ERR_DDNS_INVALID_USERNAME            TBS_ERR_CVT(ERR_DDNS_BEGIN_ADDR + 5, TR069_ERRNO_CPE_ERR)
#define ERR_DDNS_USERNAME_LENGTH_OVER        TBS_ERR_CVT(ERR_DDNS_BEGIN_ADDR + 6, TR069_ERRNO_CPE_ERR)
#define ERR_DDNS_INVALID_PASSWORD            TBS_ERR_CVT(ERR_DDNS_BEGIN_ADDR + 7, TR069_ERRNO_CPE_ERR)
#define ERR_DDNS_PASSWORD_LENGTH_OVER        TBS_ERR_CVT(ERR_DDNS_BEGIN_ADDR + 8, TR069_ERRNO_CPE_ERR)
#define ERR_DDNS_INVALID_EMAIL               TBS_ERR_CVT(ERR_DDNS_BEGIN_ADDR + 9, TR069_ERRNO_CPE_ERR)
#define ERR_DDNS_EMAIL_LENGTH_OVER           TBS_ERR_CVT(ERR_DDNS_BEGIN_ADDR + 10, TR069_ERRNO_CPE_ERR)
#define ERR_DDNS_INVALID_KEY                 TBS_ERR_CVT(ERR_DDNS_BEGIN_ADDR + 11, TR069_ERRNO_CPE_ERR)
#define ERR_DDNS_KEY_LENGTH_OVER             TBS_ERR_CVT(ERR_DDNS_BEGIN_ADDR + 12, TR069_ERRNO_CPE_ERR)
#define ERR_DDNS_HOSTNAME_CONFLICT           TBS_ERR_CVT(ERR_DDNS_BEGIN_ADDR + 13, TR069_ERRNO_CPE_ERR)
#define ERR_DDNS_INVALID_DDNS_HOST            TBS_ERR_CVT(ERR_DDNS_BEGIN_ADDR + 14, TR069_ERRNO_CPE_ERR)
#define ERR_DDNS_DDNS_HOST_LENGTH_OVER        TBS_ERR_CVT(ERR_DDNS_BEGIN_ADDR + 15, TR069_ERRNO_CPE_ERR)
#define ERR_DDNS_PRIVODER_CONFLICT           TBS_ERR_CVT(ERR_DDNS_BEGIN_ADDR + 16, TR069_ERRNO_CPE_ERR)

/* SUPP */
#define ERR_SUPP_BEGIN_ADDR   TBS_ERR_LOGIC_BASE_ADDR(MID_SUPP)

#define ERR_SUPP_USERNAME_OR_PASSWORD_BE_EMPTY  TBS_ERR_CVT(ERR_SUPP_BEGIN_ADDR + 1, TR069_ERRNO_INVALID_VAL)

/* MACFILTER */
#define ERR_MACFILTER_BEGIN_ADDR  TBS_ERR_LOGIC_BASE_ADDR(MID_MACFILTER)
#define ERR_MACFILTER_INVALID_FILTERMODE     TBS_ERR_CVT(ERR_MACFILTER_BEGIN_ADDR + 1, TR069_ERRNO_CPE_ERR)
#define ERR_MACFILTER_INVALID_TIME           TBS_ERR_CVT(ERR_MACFILTER_BEGIN_ADDR + 2, TR069_ERRNO_CPE_ERR)
#define ERR_MACFILTER_INVALID_DAY            TBS_ERR_CVT(ERR_MACFILTER_BEGIN_ADDR + 3, TR069_ERRNO_CPE_ERR)
#define ERR_MACFILTER_TIME_CONFLICT          TBS_ERR_CVT(ERR_MACFILTER_BEGIN_ADDR + 4, TR069_ERRNO_CPE_ERR)
#define ERR_MACFILTER_MAC_CONFLICT           TBS_ERR_CVT(ERR_MACFILTER_BEGIN_ADDR + 5, TR069_ERRNO_CPE_ERR)
#define ERR_MACFILTER_INVALID_INNER_PARA     TBS_ERR_CVT(ERR_MACFILTER_BEGIN_ADDR + 6, TR069_ERRNO_CPE_ERR)
#define ERR_MACFILTER_INVALID_NAME     TBS_ERR_CVT(ERR_MACFILTER_BEGIN_ADDR + 7, TR069_ERRNO_CPE_ERR)
#define ERR_MACFILTER_SCHEDULE_MODE     TBS_ERR_CVT(ERR_MACFILTER_BEGIN_ADDR + 8, TR069_ERRNO_CPE_ERR)
#define ERR_MACFILTER_SCHEDULE_PATH     TBS_ERR_CVT(ERR_MACFILTER_BEGIN_ADDR + 9, TR069_ERRNO_CPE_ERR)

/*IpFilter*/
#define ERR_IPFILTER_BEGIN_ADDR  TBS_ERR_LOGIC_BASE_ADDR(MID_IPFILTER)
#define ERR_IPFILTER_INVALID_FILTERMODE     TBS_ERR_CVT(ERR_IPFILTER_BEGIN_ADDR + 1, TR069_ERRNO_CPE_ERR)
#define ERR_IPFILTER_INVALID_NAME     TBS_ERR_CVT(ERR_IPFILTER_BEGIN_ADDR + 2, TR069_ERRNO_CPE_ERR)
#define ERR_IPFILTER_SCHEDULE_PATH     TBS_ERR_CVT(ERR_IPFILTER_BEGIN_ADDR + 3, TR069_ERRNO_CPE_ERR)

/* PORTTRIGGER */
#define ERR_PORTTRIGGER_BEGIN_ADDR          TBS_ERR_PROC_BASE_ADDR(MID_PORTTRIGGER)

/*RADVD*/
#define ERR_RADVD_BEGIN_ADDR  TBS_ERR_LOGIC_BASE_ADDR(MID_RAD)
#define ERR_HEX_FORMAT_WRONG     TBS_ERR_CVT(ERR_RADVD_BEGIN_ADDR + 1, TR069_ERRNO_CPE_ERR)
#define ERR_GLOBALID_OUT_OF_RANGE     TBS_ERR_CVT(ERR_RADVD_BEGIN_ADDR + 2, TR069_ERRNO_CPE_ERR)
#define ERR_CONFIG_TYPE_INVALID_VALUE     TBS_ERR_CVT(ERR_RADVD_BEGIN_ADDR + 3, TR069_ERRNO_CPE_ERR)
#define ERR_ROUTE_LIFETIME_OUT_OF_RANGE     TBS_ERR_CVT(ERR_RADVD_BEGIN_ADDR + 4, TR069_ERRNO_CPE_ERR)
#define ERR_ROUTE_PREFERENCE_INVALID_VALUE     TBS_ERR_CVT(ERR_RADVD_BEGIN_ADDR + 5, TR069_ERRNO_CPE_ERR)
#define ERR_IPV6_ADDRESS    TBS_ERR_CVT(ERR_RADVD_BEGIN_ADDR + 6, TR069_ERRNO_CPE_ERR)
#define ERR_SUBNET_ID_OUT_OF_RANGE     TBS_ERR_CVT(ERR_RADVD_BEGIN_ADDR + 7, TR069_ERRNO_CPE_ERR)
#define ERR_INVALID_PREFIX_LEN     TBS_ERR_CVT(ERR_RADVD_BEGIN_ADDR + 8, TR069_ERRNO_CPE_ERR)
#define ERR_INVALID_PREFIX     TBS_ERR_CVT(ERR_RADVD_BEGIN_ADDR + 9, TR069_ERRNO_CPE_ERR)
#define ERR_NOT_NEED_CHANGE TBS_ERR_CVT(ERR_RADVD_BEGIN_ADDR + 20, TR069_ERRNO_CPE_ERR)
#define ERR_FLAG_CONF_TYPE_INVALID TBS_ERR_CVT(ERR_RADVD_BEGIN_ADDR + 21, TR069_ERRNO_CPE_ERR)
#define ERR_INVALID_MO_FLAG TBS_ERR_CVT(ERR_RADVD_BEGIN_ADDR + 22, TR069_ERRNO_CPE_ERR)
#define ERR_INVALID_RA_MAX_INTERVAL TBS_ERR_CVT(ERR_RADVD_BEGIN_ADDR + 23, TR069_ERRNO_CPE_ERR)
#define ERR_INVALID_RA_MIN_INTERVAL TBS_ERR_CVT(ERR_RADVD_BEGIN_ADDR + 24, TR069_ERRNO_CPE_ERR)
#define ERR_RADVD_VALID_LIFE_TIME_SMALLER TBS_ERR_CVT(ERR_RADVD_BEGIN_ADDR + 25, TR069_ERRNO_CPE_ERR)



/*V6CONN*/
#define ERR_V6CONN_BEGIN_ADDR               TBS_ERR_LOGIC_BASE_ADDR(MID_V6CONN)
#define ERR_V6CONN_INVALID_STATIC_ADDR      TBS_ERR_CVT(ERR_V6CONN_BEGIN_ADDR + 1, TR069_ERRNO_INVALID_VAL)
#define ERR_V6CONN_INVALID_DNS_ADDR         TBS_ERR_CVT(ERR_V6CONN_BEGIN_ADDR + 2, TR069_ERRNO_INVALID_VAL)
#define ERR_V6CONN_INVALID_ROUTER_ADDR      TBS_ERR_CVT(ERR_V6CONN_BEGIN_ADDR + 3, TR069_ERRNO_INVALID_VAL)
#define ERR_V6CONN_INVALID_ADDR_CONF_TYPE   TBS_ERR_CVT(ERR_V6CONN_BEGIN_ADDR + 4, TR069_ERRNO_INVALID_VAL)
#define ERR_V6CONN_INVALID_ROUTER_CONF_TYPE TBS_ERR_CVT(ERR_V6CONN_BEGIN_ADDR + 5, TR069_ERRNO_INVALID_VAL)
#define ERR_V6CONN_INVALID_DUID_CONF_TYPE   TBS_ERR_CVT(ERR_V6CONN_BEGIN_ADDR + 6, TR069_ERRNO_INVALID_VAL)
#define ERR_V6CONN_INVALID_PREFIX_ADDR      TBS_ERR_CVT(ERR_V6CONN_BEGIN_ADDR + 7, TR069_ERRNO_INVALID_VAL)
#define ERR_V6CONN_PREFIX_ADDR_LEN_CONFLICT TBS_ERR_CVT(ERR_V6CONN_BEGIN_ADDR + 8, TR069_ERRNO_INVALID_VAL)
#define ERR_V6CONN_STATIC_ADDR_LEN_CONFLICT TBS_ERR_CVT(ERR_V6CONN_BEGIN_ADDR + 9, TR069_ERRNO_INVALID_VAL)

/* TRACERT*/
#define ERR_TRACERT_BEGIN_ADDR          TBS_ERR_LOGIC_BASE_ADDR(MID_TRACERT)
#define ERR_TRACERT_NOSTART             TBS_ERR_CVT(ERR_TRACERT_BEGIN_ADDR + 1, TR069_ERRNO_CPE_ERR)
#define ERR_TRACERT_BUSY                TBS_ERR_CVT(ERR_TRACERT_BEGIN_ADDR + 2, TR069_ERRNO_CPE_ERR)
#define ERR_TRACERT_INVALID_INTF            TBS_ERR_CVT(ERR_TRACERT_BEGIN_ADDR + 3, TR069_ERRNO_INVALID_VAL)
#define ERR_TRACERT_INVALID_HOST_IP_PART    TBS_ERR_CVT(ERR_TRACERT_BEGIN_ADDR + 4, TR069_ERRNO_INVALID_VAL)
#define ERR_TRACERT_INVALID_HOST_IP_OCT     TBS_ERR_CVT(ERR_TRACERT_BEGIN_ADDR + 5, TR069_ERRNO_INVALID_VAL)
#define ERR_TRACERT_INVALID_HOST_BEGIN      TBS_ERR_CVT(ERR_TRACERT_BEGIN_ADDR + 6, TR069_ERRNO_INVALID_VAL)
#define ERR_TRACERT_INVALID_HOST_A          TBS_ERR_CVT(ERR_TRACERT_BEGIN_ADDR + 7, TR069_ERRNO_INVALID_VAL)
#define ERR_TRACERT_INVALID_HOST_LEN        TBS_ERR_CVT(ERR_TRACERT_BEGIN_ADDR + 8, TR069_ERRNO_INVALID_VAL)
#define ERR_TRACERT_NOHOST                  TBS_ERR_CVT(ERR_TRACERT_BEGIN_ADDR + 9, TR069_ERRNO_INVALID_VAL)
#define ERR_TRACERT_INVALID_IP_TYPE         TBS_ERR_CVT(ERR_TRACERT_BEGIN_ADDR + 10, TR069_ERRNO_INVALID_VAL)


/* Schedule */
#define ERR_SCHEDULE_BEGIN_ADDR    TBS_ERR_LOGIC_BASE_ADDR(MID_SCHED)

#define ERR_SCHEDULE_INVALID_NAME    TBS_ERR_CVT(ERR_SCHEDULE_BEGIN_ADDR+1, TR069_ERRNO_CPE_ERR)
#define ERR_SCHEDULE_INVALID_STARTTIME           TBS_ERR_CVT(ERR_SCHEDULE_BEGIN_ADDR+2, TR069_ERRNO_INVALID_VAL)
#define ERR_SCHEDULE_INVALID_ENDTIME          TBS_ERR_CVT(ERR_SCHEDULE_BEGIN_ADDR+3, TR069_ERRNO_INVALID_VAL)
#define ERR_SCHEDULE_INVALID_SPICIFIEDDAY        TBS_ERR_CVT(ERR_SCHEDULE_BEGIN_ADDR+4, TR069_ERRNO_INVALID_VAL)
#define ERR_SCHEDULE_INVALID_ENABLEALLDAYS        TBS_ERR_CVT(ERR_SCHEDULE_BEGIN_ADDR+5, TR069_ERRNO_INVALID_VAL)
#define ERR_SCHEDULE_INVALID_SCHEDULEDAYS        TBS_ERR_CVT(ERR_SCHEDULE_BEGIN_ADDR+6, TR069_ERRNO_INVALID_VAL)
#define ERR_SCHEDULE_INVALID_ENABLEALLTIME        TBS_ERR_CVT(ERR_SCHEDULE_BEGIN_ADDR+7, TR069_ERRNO_INVALID_VAL)
#define ERR_SCHEDULE_TIME_CONFLICT        TBS_ERR_CVT(ERR_SCHEDULE_BEGIN_ADDR+8, TR069_ERRNO_INVALID_VAL)
#define ERR_SCHEDULE_NAME_CONFLICT        TBS_ERR_CVT(ERR_SCHEDULE_BEGIN_ADDR+9, TR069_ERRNO_INVALID_VAL)

/* IGMP */
#define ERR_IGMP_BEGIN_ADDR				TBS_ERR_LOGIC_BASE_ADDR(MID_IGMP)
#define ERR_IGMP_MULTICAST_IP_CONFLICT	TBS_ERR_CVT(ERR_IGMP_BEGIN_ADDR+1, TR069_ERRNO_INVALID_VAL);

/* Diagnostics */
#define ERR_DG_BEGIN_ADDR                   TBS_ERR_LOGIC_BASE_ADDR(MID_DIAG)
#define ERR_DG_INVALID_STATE                TBS_ERR_CVT(ERR_DG_BEGIN_ADDR + 1, TR069_ERRNO_INVALID_VAL)
#define ERR_DG_INVALID_INTERFACE            TBS_ERR_CVT(ERR_DG_BEGIN_ADDR + 2, TR069_ERRNO_INVALID_VAL)
#define ERR_DG_PVC_TOO_MUCH                 TBS_ERR_CVT(ERR_DG_BEGIN_ADDR + 3, TR069_ERRNO_INVALID_VAL)
#define ERR_DG_PVC_INVALID                  TBS_ERR_CVT(ERR_DG_BEGIN_ADDR + 4, TR069_ERRNO_INVALID_VAL)

/*DHCP6S*/
#define ERR_DHCP6S_BEGIN_ADDR               TBS_ERR_LOGIC_BASE_ADDR(MID_DHCP6S)
#define ERR_DHCP6S_LIFE_TIME_OUT_RANGE      TBS_ERR_CVT(ERR_DHCP6S_BEGIN_ADDR + 1, TR069_ERRNO_INVALID_VAL)
#define ERR_DHCP6S_START_ADDR_BIGGER        TBS_ERR_CVT(ERR_DHCP6S_BEGIN_ADDR + 2, TR069_ERRNO_INVALID_VAL)
#define ERR_DHCP6S_INVALID_LIFE_TIME        TBS_ERR_CVT(ERR_DHCP6S_BEGIN_ADDR + 3, TR069_ERRNO_INVALID_VAL)
#define ERR_DHCP6S_VALID_LIFE_TIME_SMALLER  TBS_ERR_CVT(ERR_DHCP6S_BEGIN_ADDR + 4, TR069_ERRNO_INVALID_VAL)
#define ERR_DHCP6S_RANGE_ERROR              TBS_ERR_CVT(ERR_DHCP6S_BEGIN_ADDR + 5, TR069_ERRNO_INVALID_VAL)



#define ERR_WANPROXY_BEGIN_ADDR         TBS_ERR_LOGIC_BASE_ADDR(MID_WAN_PROXY)
#define ERR_WANP_V6_IP_VLANID        TBS_ERR_CVT(ERR_WANPROXY_BEGIN_ADDR + 1, TR069_ERRNO_CPE_ERR)

/* Default Gateway */
#define ERR_DFGW_BEGIN_ADDR                            TBS_ERR_LOGIC_BASE_ADDR(MID_DEFAULTGW)
#define ERR_DEGW_EMPTY_IP                                TBS_ERR_CVT(ERR_DFGW_BEGIN_ADDR+1,TR069_ERRNO_INVALID_VAL)
#define ERR_DEGW_INVALID_IP                              TBS_ERR_CVT(ERR_DFGW_BEGIN_ADDR+2,TR069_ERRNO_INVALID_VAL)
#define ERR_DEGW_EMPTY_USERINIF                                TBS_ERR_CVT(ERR_DFGW_BEGIN_ADDR+3,TR069_ERRNO_INVALID_VAL)
#define ERR_DEGW_INVALID_USERINIF                                TBS_ERR_CVT(ERR_DFGW_BEGIN_ADDR+4,TR069_ERRNO_INVALID_VAL)
#define ERR_DEGW_EMPTY_SELECT                                TBS_ERR_CVT(ERR_DFGW_BEGIN_ADDR+5,TR069_ERRNO_INVALID_VAL)
#define ERR_DEGW_INVALID_SELECT                                TBS_ERR_CVT(ERR_DFGW_BEGIN_ADDR+6,TR069_ERRNO_INVALID_VAL)

/* IP ACL */
#define ERR_IP_ACL_BEGIN_ADDR                            TBS_ERR_LOGIC_BASE_ADDR(MID_IP_ACL)
#define ERR_IP_ACL_EMPTY_IP                                TBS_ERR_CVT(ERR_IP_ACL_BEGIN_ADDR+1,TR069_ERRNO_INVALID_VAL)
#define ERR_IP_ACL_INVALID_IP                              TBS_ERR_CVT(ERR_IP_ACL_BEGIN_ADDR+2,TR069_ERRNO_INVALID_VAL)
#define ERR_IP_ACL_IP_ZERO                              TBS_ERR_CVT(ERR_IP_ACL_BEGIN_ADDR+3,TR069_ERRNO_INVALID_VAL)
#define ERR_IP_ACL_IP_SAME                              TBS_ERR_CVT(ERR_IP_ACL_BEGIN_ADDR+4,TR069_ERRNO_INVALID_VAL)

/* SAMBA */
#define ERR_SAMBA_BEGIN_ADDR      TBS_ERR_LOGIC_BASE_ADDR(MID_SAMBA)
#define ERR_SAMBA_CONFLICT_DIR      TBS_ERR_CVT(ERR_SAMBA_BEGIN_ADDR + 1, TR069_ERRNO_INVALID_VAL)
#define ERR_SAMBA_CONFLICT_USER     TBS_ERR_CVT(ERR_SAMBA_BEGIN_ADDR + 2, TR069_ERRNO_INVALID_VAL)

/* cpu 内存nat*/
#define ERR_OS_INFO_BEGIN_ADDR TBS_ERR_LOGIC_BASE_ADDR(MID_OS_INFO)

/* IPTUNNEL */
#define ERR_IPTUNNEL_BEGIN_ADDR               TBS_ERR_LOGIC_BASE_ADDR(MID_IPTUNNEL)
#define ERR_IPTUNNEL_NO_RESOURSE              TBS_ERR_CVT(ERR_IPTUNNEL_BEGIN_ADDR + 1, TR069_ERRNO_NO_RESOURCE)
#define ERR_IPTUNNEL_VAL_EMPTY                TBS_ERR_CVT(ERR_IPTUNNEL_BEGIN_ADDR + 2, TR069_ERRNO_INVALID_VAL)
#define ERR_IPTUNNEL_NAME_OVERLENGTH          TBS_ERR_CVT(ERR_IPTUNNEL_BEGIN_ADDR + 3, TR069_ERRNO_INVALID_VAL)
#define ERR_IPTUNNEL_VALID_STRING             TBS_ERR_CVT(ERR_IPTUNNEL_BEGIN_ADDR + 4, TR069_ERRNO_INVALID_VAL)
#define ERR_IPTUNNEL_EXIST_NAME               TBS_ERR_CVT(ERR_IPTUNNEL_BEGIN_ADDR + 5, TR069_ERRNO_INVALID_VAL)
#define ERR_IPTUNNEL_EXIST_WAN_IF             TBS_ERR_CVT(ERR_IPTUNNEL_BEGIN_ADDR + 6, TR069_ERRNO_INVALID_VAL)
#define ERR_IPTUNNEL_NOEXIST_WAN_IF           TBS_ERR_CVT(ERR_IPTUNNEL_BEGIN_ADDR + 7, TR069_ERRNO_INVALID_VAL)
#define ERR_IPTUNNEL_WRONY_IPV6_MODLE         TBS_ERR_CVT(ERR_IPTUNNEL_BEGIN_ADDR + 8, TR069_ERRNO_INVALID_VAL)
#define ERR_IPTUNNEL_WRONY_MASKLEN_EMPTY      TBS_ERR_CVT(ERR_IPTUNNEL_BEGIN_ADDR + 9, TR069_ERRNO_INVALID_VAL)
#define ERR_IPTUNNEL_WRONY_MASKLEN            TBS_ERR_CVT(ERR_IPTUNNEL_BEGIN_ADDR + 10, TR069_ERRNO_INVALID_VAL)
#define ERR_IPTUNNEL_INVALID_PARA             TBS_ERR_CVT(ERR_IPTUNNEL_BEGIN_ADDR + 11, TR069_ERRNO_CPE_ERR)
#define ERR_IPTUNNEL_IP_EMPTY                 TBS_ERR_CVT(ERR_IPTUNNEL_BEGIN_ADDR + 12, TR069_ERRNO_INVALID_VAL)
#define ERR_IPTUNNEL_INVALID_IP               TBS_ERR_CVT(ERR_IPTUNNEL_BEGIN_ADDR + 13, TR069_ERRNO_INVALID_VAL)

/* Upgrader */
#define ERR_UPG_BEGIN_ADDR                      TBS_ERR_LOGIC_BASE_ADDR(MID_UPG)
#define ERR_UPG_GENERAL_ERROR                   TBS_ERR_CVT(ERR_UPG_BEGIN_ADDR+1 , TR069_ERRNO_CPE_ERR)
#define ERR_INIT_MODULE_ERROR                   TBS_ERR_CVT(ERR_UPG_BEGIN_ADDR+2 , TR069_ERRNO_CPE_ERR)
#define ERR_DESTROY_MODULE_ERROR                TBS_ERR_CVT(ERR_UPG_BEGIN_ADDR+3 , TR069_ERRNO_CPE_ERR)
#define ERR_REQUEST_METHOD_ERROR                TBS_ERR_CVT(ERR_UPG_BEGIN_ADDR+4 , TR069_ERRNO_CPE_ERR)
#define ERR_CONTENT_TYPE_ERROR                  TBS_ERR_CVT(ERR_UPG_BEGIN_ADDR+5 , TR069_ERRNO_CPE_ERR)
#define ERR_CONTENT_LENGTH_ERROR                TBS_ERR_CVT(ERR_UPG_BEGIN_ADDR+6 , TR069_ERRNO_CPE_ERR)
#define ERR_INVALID_VARIABLE_ERROR              TBS_ERR_CVT(ERR_UPG_BEGIN_ADDR+7 , TR069_ERRNO_CPE_ERR)
#define ERR_NO_VARIABLE_ERROR                   TBS_ERR_CVT(ERR_UPG_BEGIN_ADDR+8 , TR069_ERRNO_CPE_ERR)
#define ERR_MIN_CONTENT_LENGTH_ERROR            TBS_ERR_CVT(ERR_UPG_BEGIN_ADDR+9 , TR069_ERRNO_CPE_ERR)
#define ERR_MAX_CONTENT_LENGTH_ERROR            TBS_ERR_CVT(ERR_UPG_BEGIN_ADDR+10, TR069_ERRNO_CPE_ERR)
#define ERR_FOPEN_LOG_ERROR                     TBS_ERR_CVT(ERR_UPG_BEGIN_ADDR+11, TR069_ERRNO_CPE_ERR)
#define ERR_FOPEN_FW_ERROR                      TBS_ERR_CVT(ERR_UPG_BEGIN_ADDR+12, TR069_ERRNO_CPE_ERR)
#define ERR_OPERATE_FW_ERROR                    TBS_ERR_CVT(ERR_UPG_BEGIN_ADDR+13, TR069_ERRNO_CPE_ERR)
#define ERR_FILE_TYPE_ERROR                     TBS_ERR_CVT(ERR_UPG_BEGIN_ADDR+14, TR069_ERRNO_CPE_ERR)
#define ERR_FILE_SIZE_ERROR                     TBS_ERR_CVT(ERR_UPG_BEGIN_ADDR+15, TR069_ERRNO_CPE_ERR)
#define ERR_FILE_PRODUCT_ERROR                  TBS_ERR_CVT(ERR_UPG_BEGIN_ADDR+16, TR069_ERRNO_CPE_ERR)
#define ERR_FILE_CRC_ERROR                      TBS_ERR_CVT(ERR_UPG_BEGIN_ADDR+17, TR069_ERRNO_CPE_ERR)
#define ERR_FILE_UPLOAD_ERROR                   TBS_ERR_CVT(ERR_UPG_BEGIN_ADDR+18, TR069_ERRNO_CPE_ERR)
#define ERR_AUTH_ERROR                          TBS_ERR_CVT(ERR_UPG_BEGIN_ADDR+19, TR069_ERRNO_CPE_ERR)
#define ERR_UPG_TIMEOUT                         TBS_ERR_CVT(ERR_UPG_BEGIN_ADDR+20, TR069_ERRNO_CPE_ERR)
#define ERR_ITEMS_LENGTH_ERROR                  TBS_ERR_CVT(ERR_UPG_BEGIN_ADDR+21, TR069_ERRNO_CPE_ERR)
#define ERR_INCOMPATIBLE_IMG_ERROR              TBS_ERR_CVT(ERR_UPG_BEGIN_ADDR+22, TR069_ERRNO_CPE_ERR)

typedef struct
{
    int iErrNo;
    char *pcEnglish;
    char *pcChinese;
} ST_TBS_ERR_TABLE;


/* 用来判断返回值是否正常*/
#define RET_SUCCEED(ret) (ret == TBS_SUCCESS)
#define RET_FAILED(ret)  (ret != TBS_SUCCESS)

const char *tbsstrerr (int errnum);
int tbserr2tr069(int tbserrno);

const char* tbsGetMsgTypeName(unsigned short usMsgType);
const char* tbsGetMIDName(unsigned short usMID);


#endif /*__TBS_TBSERROR_H__*/
