COPTS	= -O2 -g
CFLAGS	= $(COPTS) -I. -I../.. -I../../.. -I../../../include -fPIC
LDFLAGS	= -shared
INSTALL	= install
#***************************************************************************

DESTDIR = $(ROOTDIR)/romfs/usr
LIBDIR = $(DESTDIR)/lib/pppd/$(VERSION)
VERSION = $(shell awk -F '"' '/VERSION/ { print $$2; }' ../../patchlevel.h)

ifneq ($(KERNEL_HEADERS),)
CFLAGS = $(COPTS) -I. -I../../.. -I$(ROOTDIR)/$(KERNEL_HEADERS)/include -fPIC
else
CFLAGS = $(COPTS) -I. -I../../.. -I$(ROOTDIR)/$(LINUXDIR)/include -fPIC
endif

PLUGINS := pptp.so

all: $(PLUGINS)
	$(INSTALL) -d -m 755 $(LIBDIR)
	$(INSTALL) -c -m 4550 $(PLUGINS) $(LIBDIR)
	
OBJS = dirutil.o pptp.o pptp_ctrl.o util.o \
       orckit_quirks.o pptp_callmgr.o pptp_quirks.o vector.o

%.so: $(OBJS)
	$(CC) $(CFLAGS) -o $@ -shared $^ $(LIBS)

install: all


clean:
	rm -f *.o *.so

%.o: %.c
	$(CC) $(CFLAGS) -c -o $@ $<
