/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 12077 $ of $ 
 *
 * $Id: //WIFI_SOC/MP/SDK_5_0_0_0/RT288x_SDK/source/user/net-snmp-5.5.pre2/agent/mibgroup/etherlike-mib/dot3StatsTable/dot3StatsTable_data_set.h#1 $
 */
#ifndef DOT3STATSTABLE_DATA_SET_H
#define DOT3STATSTABLE_DATA_SET_H

#ifdef __cplusplus
extern          "C" {
#endif

    /*
     *********************************************************************
     * SET function declarations
     */

    /*
     *********************************************************************
     * SET Table declarations
     */


#ifdef __cplusplus
}
#endif
#endif                          /* DOT3STATSTABLE_DATA_SET_H */
