#SRCDIR=mDNSResponder-107.6
SRCDIR=mDNSResponder-320.5.1

.PHONY: all build clean

all: build


build:
	cd $(SRCDIR); \
	make all

clean:
	cd $(SRCDIR); \
	make clean

romfs:
	cd $(SRCDIR); \
	make romfs
