
all:
	$(MAKE) -C mDNSPosix os=linux SAResponder        
	                                                                                           
romfs:
	$(MAKE) -C mDNSPosix os=linux romfs

clean:
	$(MAKE) -C mDNSPosix os=linux clean
