nb_vfy :
	${CC}  -o $@ nb_vfy.c    -L$(ROOTDIR)/user/supermesh/lib  -L$(ROOTDIR)/user/mosquitto-1.3.1/lib -L$(ROOTDIR)/user/openssl-1.0.2j/ -L$(ROOTDIR)/user/openssl-1.0.2j/lib -lapson_nbapi -lapson_mqtt_api -lmosquitto -lssl -lcrypto -lapsonpb -lgcc_s
	# -lapsond_sbapi -lapsond_vendor_sbapi  -lapsonpb  -lazlog -lc

