/* This file is automatically generated by configure.  Do not modify by hand. */
  if (should_init("snmp_mib")) init_snmp_mib();
  if (should_init("system_mib")) init_system_mib();
  if (should_init("sysORTable")) init_sysORTable();
  if (should_init("vacm_vars")) init_vacm_vars();
  if (should_init("vacm_context")) init_vacm_context();
