.PHONY: all romfs clean

all: 
	@python2.7 genFilesByDM.py  SelfDefinedPrefix=X_BC0304_  dbVersion[DataModel.xls,20063] dbVersion[FwcmdModel.xls,19529] dbVersion[InternalModel.xls,20124] dbVersion[PmFileModel.xls,17971] dbVersion[SonDataModel.xls,19371] dbVersion[TraceMdtModel.xls,18892] $(TRDMDIR)/01.common/dm_lib/_script/excel_files/DataModel.xls $(TRDMDIR)/01.common/dm_lib/_script/excel_files/FwcmdModel.xls $(TRDMDIR)/01.common/dm_lib/_script/excel_files/InternalModel.xls $(TRDMDIR)/01.common/dm_lib/_script/excel_files/PmFileModel.xls $(TRDMDIR)/01.common/dm_lib/_script/excel_files/SonDataModel.xls $(TRDMDIR)/01.common/dm_lib/_script/excel_files/TraceMdtModel.xls

romfs:
	
clean:
